'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {createLocalAccounts}=require('../lib/accounts'),store=require('../lib/store'),M=require('../skins/tracer/model');
const password='correct horse battery staple';
test('avatar symbols default to black and accept all twelve zodiac signs with independent colors',async t=>{
  const {service}=await fixture(t),created=await service.register(registration());
  assert.equal(created.user.profile.avatar.iconColor,'#000000');
  for(const value of ['aries','taurus','gemini','cancer','leo','virgo','libra','scorpio','sagittarius','capricorn','aquarius','pisces']){
    const {user}=await service.updateProfile(created.token,{nickname:'Avatar test',avatar:{kind:'preset',value,color:'#c2ade2',iconColor:'#AB12EF'}});
    assert.deepEqual(user.profile.avatar,{kind:'preset',value,color:'#c2ade2',iconColor:'#ab12ef'});
  }
  const {user}=await service.updateProfile(created.token,{nickname:'Avatar test',avatar:{kind:'preset',value:'leo',color:'#c2ade2'}});
  assert.equal(user.profile.avatar.iconColor,'#000000');
  await assert.rejects(service.updateProfile(created.token,{nickname:'Avatar test',avatar:{kind:'preset',value:'leo',color:'#c2ade2',iconColor:'url(https://example.com)'}}),{code:'invalid-avatar'});
});
async function fixture(t,options){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tracer-account-test-'));t.after(async()=>{assert.ok(path.basename(dir).startsWith('tracer-account-test-'));await fs.rm(dir,{recursive:true,force:true});});return{dir,service:createLocalAccounts(dir,options)};}
const registration=(email='owner@example.com')=>({email,password,profile:{nickname:'小月亮',bio:'我的空间',workspaceName:'月光工作室'}});
test('local registration normalizes email, persists only hashed secrets and survives restart',async t=>{const{dir,service}=await fixture(t),created=await service.register(registration(' OWNER@EXAMPLE.COM '),'Windows Chrome/123');assert.equal(created.user.email,'owner@example.com');assert.equal(created.user.emailVerified,false);assert.equal(created.user.profile.nickname,'小月亮');assert.equal(created.recoveryCode.length,55);const raw=await fs.readFile(path.join(dir,'.accounts/identity.json'),'utf8');assert.ok(!raw.includes(password));assert.ok(!raw.includes(created.token));assert.ok(!raw.includes(created.recoveryCode));const restored=createLocalAccounts(dir);assert.equal((await restored.context(created.token)).user.id,created.user.id);assert.equal((await restored.context('')).scope,'guest');assert.equal((await restored.context('bad-token')).scope,'locked');await assert.rejects(service.register(registration()),{code:'email-in-use'});});
test('concurrent registrations for one normalized email create exactly one identity',async t=>{const{service}=await fixture(t);const outcomes=await Promise.allSettled([service.register(registration()),service.register(registration('OWNER@example.com'))]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);assert.equal(outcomes.filter(r=>r.status==='rejected')[0].reason.code,'email-in-use');});
test('invalid passwords and unknown email have the same login error; throttling bounds retries',async t=>{const{service}=await fixture(t);await service.register(registration());await assert.rejects(service.login({email:'absent@example.com',password}),{code:'invalid-credentials'});for(let n=0;n<12;n++)await assert.rejects(service.login({email:'owner@example.com',password:'incorrect-password'}),{code:'invalid-credentials'});await assert.rejects(service.login({email:'owner@example.com',password}),{code:'try-again-later'});});
test('session logout, expiry and revocation never fall through to guest access',async t=>{let time=Date.now();const{service}=await fixture(t,{now:()=>time,sessionLifetime:10000}),first=await service.register(registration()),second=await service.login({email:first.user.email,password});const sessions=await service.sessions(first.token);assert.equal(sessions.sessions.length,2);await service.revoke(first.token,'others');assert.equal((await service.context(second.token)).scope,'locked');await service.logout(first.token);assert.equal((await service.context(first.token)).scope,'locked');const third=await service.login({email:first.user.email,password});time+=11000;assert.equal((await service.context(third.token)).scope,'locked');await assert.rejects(service.exportData(third.token),{code:'session-expired'});});
test('password change invalidates other sessions and returns a rotated current session',async t=>{const{service}=await fixture(t),first=await service.register(registration()),other=await service.login({email:first.user.email,password});await assert.rejects(service.changePassword(first.token,{currentPassword:'wrong',newPassword:'new long password'}),{code:'invalid-credentials'});const next=await service.changePassword(first.token,{currentPassword:password,newPassword:'new long password'});assert.equal((await service.context(first.token)).scope,'locked');assert.equal((await service.context(other.token)).scope,'locked');assert.equal((await service.context(next.token)).user.id,first.user.id);await assert.rejects(service.login({email:first.user.email,password}),{code:'invalid-credentials'});await service.login({email:first.user.email,password:'new long password'});});
test('recovery code reset is one-time, rotates recovery and invalidates sessions',async t=>{const{service}=await fixture(t),created=await service.register(registration());await assert.rejects(service.recover({email:created.user.email,recoveryCode:'bad',newPassword:'new password 12345'}),{code:'invalid-recovery'});const next=await service.recover({email:created.user.email,recoveryCode:created.recoveryCode,newPassword:'new password 12345'});assert.notEqual(next.recoveryCode,created.recoveryCode);assert.equal((await service.context(created.token)).scope,'locked');await assert.rejects(service.recover({email:created.user.email,recoveryCode:created.recoveryCode,newPassword:password}),{code:'invalid-recovery'});await service.login({email:created.user.email,password:'new password 12345'});});
test('profile and exported records cannot expose or overwrite authentication fields',async t=>{const{service}=await fixture(t),created=await service.register(registration());const result=await service.updateProfile(created.token,{nickname:'新名字',bio:'<script>not HTML</script>',workspaceName:'Quiet',avatar:{kind:'preset',value:'leaf',color:'#9ccad9'},password:'attacker',id:'fake'});assert.equal(result.user.id,created.user.id);assert.equal(result.user.profile.nickname,'新名字');await service.login({email:created.user.email,password});const exported=JSON.stringify(await service.exportData(created.token));assert.ok(!exported.includes(created.token));assert.ok(!exported.includes(created.recoveryCode));assert.ok(!exported.includes('recoveryHash'));assert.ok(!exported.includes('scrypt'));await assert.rejects(service.updateProfile(created.token,{nickname:'test',avatar:{kind:'image',value:'data:image/svg+xml,<svg/>'}}),{code:'invalid-avatar'});});
test('guest import preserves source and can claim the same economy only once',async t=>{const{dir,service}=await fixture(t),one=await service.register(registration()),two=await service.register(registration('two@example.com'));const workspace=M.emptyWorkspace();M.addTask(workspace,{title:'Original guest task'});await store.writeStore(dir,'workspace',JSON.stringify(workspace));assert.equal((await service.guestPreview(one.token)).available,true);await service.importGuest(one.token);assert.equal((await store.readStore(dir,'workspace')).tasks[0].title,'Original guest task');assert.equal((await service.exportData(one.token)).workspace.tasks[0].title,'Original guest task');assert.equal((await service.importGuest(one.token)).alreadyImported,true);await assert.rejects(service.importGuest(two.token),{code:'guest-already-imported'});assert.equal((await service.exportData(two.token)).workspace,null);assert.equal((await service.collection(one.token)).accountId,one.user.id);assert.deepEqual((await service.collection(two.token)).items,[]);});
test('guest import refuses to overwrite an existing account workspace',async t=>{const{dir,service}=await fixture(t),created=await service.register(registration()),source=M.emptyWorkspace(),own=M.emptyWorkspace();M.addTask(source,{title:'Guest'});M.addTask(own,{title:'Own'});await store.writeStore(dir,'workspace',JSON.stringify(source));await store.writeStore(service.directory(created.user.id),'workspace',JSON.stringify(own));assert.equal((await service.guestPreview(created.token)).available,false);await assert.rejects(service.importGuest(created.token),{code:'account-not-empty'});assert.equal((await service.exportData(created.token)).workspace.tasks[0].title,'Own');});
test('an interrupted guest import can be retried without duplicating records or reopening its claim',async t=>{const{dir,service}=await fixture(t),created=await service.register(registration()),source=M.emptyWorkspace();M.addTask(source,{title:'Imported once'});await store.writeStore(dir,'workspace',JSON.stringify(source));await service.importGuest(created.token);const file=path.join(dir,'.accounts/identity.json'),identity=JSON.parse(await fs.readFile(file,'utf8'));identity.guestImport.state='pending';await fs.writeFile(file,JSON.stringify(identity));const status=await service.guestPreview(created.token);assert.equal(status.pendingImport,true);assert.equal(status.available,true);assert.equal(status.alreadyImported,false);await service.importGuest(created.token);assert.equal((await service.exportData(created.token)).workspace.tasks.length,1);assert.equal((await service.guestPreview(created.token)).alreadyImported,true);});
test('corrupt identity fails closed and does not reset or overwrite the database',async t=>{const{dir,service}=await fixture(t),created=await service.register(registration()),file=path.join(dir,'.accounts/identity.json');await fs.writeFile(file,'{corrupt');await assert.rejects(service.context(created.token),{code:'account-storage-unavailable'});await assert.rejects(service.register(registration('other@example.com')),{code:'account-storage-unavailable'});assert.equal(await fs.readFile(file,'utf8'),'{corrupt');assert.throws(()=>service.directory('../../guest'),{code:'invalid-account'});});
