'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),fsp=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tracer-account-http-'));
process.env.DOCS_PORTAL_DATA_DIR=dir;process.env.DOCS_PORTAL_STATE_FILE=path.join(dir,'bookmarks.json');process.env.DOCS_PORTAL_SKIN='tracer';
const{server}=require('../server');let origin;
test.before(()=>new Promise(resolve=>server.listen(0,'127.0.0.1',()=>{origin='http://127.0.0.1:'+server.address().port;resolve();})));
test.after(async()=>{await new Promise(resolve=>server.close(resolve));assert.ok(path.basename(dir).startsWith('tracer-account-http-'));await fsp.rm(dir,{recursive:true,force:true});});
async function call(route,{cookie,scope='guest',data,method,headers={}}={}){const r=await fetch(origin+route,{method:method||(data===undefined?'GET':'POST'),headers:{'x-tracer-account':'1','x-tracer-scope':scope,...(cookie?{cookie}:{}),...(data===undefined?{}:{'content-type':'application/json'}),...headers},body:data===undefined?undefined:JSON.stringify(data)});const text=await r.text();let body;try{body=JSON.parse(text);}catch{body=text;}return{status:r.status,body,cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers};}
const register=email=>call('/api/account/register',{data:{email,password:'long test password',profile:{nickname:'Test User'}}});
test('wallpaper API debits persisted harvest coins, protects receipts from stale saves and requires ownership',async()=>{
  const a=await register('shop@example.com'),own={cookie:a.cookie,scope:a.body.user.id},G=require('../public/task-garden'),M=require('../skins/tracer/model'),workspace=M.emptyWorkspace();
  for(let i=0;i<8;i++){const t={id:'harvest'+i,title:'Harvest',status:'doing',projectId:null,createdAt:100,updatedAt:100};workspace.tasks.push(t);G.taskChanged(workspace,t,100,n=>n===10000?1000:4);t.status='done';t.doneAt=t.updatedAt=101;G.taskChanged(workspace,t,101);G.harvest(workspace,t.id,102);}G.sell(workspace,'peach',8,200);
  assert.equal((await call('/api/store/workspace',{...own,method:'PUT',data:workspace})).status,200);
  const buy=await call('/api/account/wallpaper-purchase',{...own,data:{itemId:'s01',price:0}});assert.equal(buy.status,200);assert.equal(buy.body.collection.balance,160);assert.equal(buy.body.collection.catalog.length,42);
  assert.equal((await call('/api/account/wallpaper-purchase',{...own,data:{itemId:'s01'}})).body.alreadyOwned,true);
  assert.equal((await call('/api/account/wallpaper-equip',{...own,data:{slot:'background',itemId:'s02'}})).status,409);
  assert.equal((await call('/api/account/wallpaper-equip',{...own,data:{slot:'background',itemId:'s01'}})).status,200);
  assert.equal((await call('/api/store/workspace',{...own,method:'PUT',data:workspace})).status,200);
  const persisted=(await call('/api/account/collection',own)).body;assert.equal(persisted.appearance.backgroundItemId,'s01');assert.equal(persisted.balance,160);
  const stale=JSON.parse(JSON.stringify(workspace));assert.equal(G.buyFarm(stale,'cyber',400).ok,true);assert.equal((await call('/api/store/workspace',{...own,method:'PUT',data:stale})).status,409);
  assert.equal((await call('/api/account/wallpaper-purchase',{...own,scope:'guest',data:{itemId:'s02'}})).status,409);
  const asset=await fetch(origin+persisted.catalog[0].asset);assert.equal(asset.status,200);assert.match(asset.headers.get('content-type'),/image\/png/);
});
test('registration uses HttpOnly SameSite cookies and never returns bearer credentials',async()=>{const r=await register('one@example.com');assert.equal(r.status,200);assert.ok(r.cookie);assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/SameSite=Strict/);assert.equal(r.body.token,undefined);assert.equal((await call('/api/account/session',{cookie:r.cookie})).body.scope,r.body.user.id);});
test('two accounts and guest have distinct workspaces, bookmarks, configuration and collections',async()=>{const a=await register('two@example.com'),b=await register('three@example.com'),one={cookie:a.cookie,scope:a.body.user.id},two={cookie:b.cookie,scope:b.body.user.id};const empty=require('../skins/tracer/model').emptyWorkspace();const task=require('../skins/tracer/model').addTask(empty,{title:'Only account A'});assert.equal((await call('/api/store/workspace',{...one,method:'PUT',data:empty})).status,200);assert.equal((await call('/api/store/workspace',one)).body.tasks[0].id,task.id);assert.equal((await call('/api/store/workspace',two)).body,null);assert.equal((await call('/api/store/workspace')).body,null);await call('/api/state',{...one,data:{bookmark:'A'}});assert.equal((await call('/api/state',two)).body.bookmark,undefined);assert.equal((await call('/api/state',one)).body.bookmark,'A');const status=await call('/api/ai/personal-status',{...two,headers:{'x-tracer-ai':'1'}});assert.equal(status.status,200);assert.equal(status.body.hasKey,false);assert.equal((await call('/api/account/collection',two)).body.accountId,b.body.user.id);});
test('stale tabs and sendBeacon cannot write guest or account A data into account B',async()=>{const a=await register('four@example.com'),b=await register('five@example.com');const stale={cookie:b.cookie,scope:a.body.user.id};assert.equal((await call('/api/store/workspace',{...stale,data:{tasks:[]}})).status,409);const r=await fetch(origin+'/api/store/workspace?__tracer_account='+a.body.user.id,{method:'POST',headers:{cookie:b.cookie},body:'{"tasks":[]}'});assert.equal(r.status,409);assert.equal((await call('/api/account/profile',{...stale,data:{nickname:'Intruder'}})).status,409);assert.equal((await call('/api/account/export',stale)).status,409);assert.equal((await call('/api/store/workspace',{cookie:b.cookie,scope:b.body.user.id})).body,null);});
test('cross-origin account/data mutations and missing request markers are rejected',async()=>{const registered=await register('six@example.com'),own={cookie:registered.cookie,scope:registered.body.user.id};assert.equal((await call('/api/account/profile',{...own,data:{nickname:'Intruder'},headers:{origin:'https://evil.example'}})).status,403);assert.equal((await call('/api/store/other',{...own,data:{secret:1},headers:{'sec-fetch-site':'cross-site'}})).status,403);const raw=await fetch(origin+'/api/account/register',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(raw.status,403);assert.equal((await call('/api/store/identity',own)).body,null);});
test('expired cookie blocks data, but can be cleared to return explicitly to guest',async()=>{const r=await register('seven@example.com'),own={cookie:r.cookie,scope:r.body.user.id};await call('/api/account/logout',{...own,data:{}});assert.equal((await call('/api/store/workspace',own)).status,401);const bootstrap=await call('/account-context.js',own);assert.ok(bootstrap.body.includes('"scope":"locked"'));const cleared=await call('/api/account/logout',{cookie:r.cookie,scope:'locked',data:{}});assert.equal(cleared.status,200);assert.match(cleared.headers.get('set-cookie'),/Max-Age=0/);});
