'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib');
const Images=require('../lib/pet-image'),Pet=require('../skins/tracer/pet-model'),Workspace=require('../skins/tracer/model'),Store=require('../lib/store'),{createLocalAccounts}=require('../lib/accounts');
function crc(bytes) { let value = 0xffffffff; for (const byte of bytes) { value ^= byte; for(let i=0;i<8;i++) value=value&1?0xedb88320^(value>>>1):value>>>1; } return (value^0xffffffff)>>>0; }
function chunk(type, value) { const result=Buffer.alloc(value.length+12); result.writeUInt32BE(value.length);result.write(type,4);value.copy(result,8);result.writeUInt32BE(crc(result.subarray(4,-4)),result.length-4);return result; }
function png(edge=1, metadata='', color=120) {
  const header=Buffer.alloc(13);header.writeUInt32BE(edge);header.writeUInt32BE(edge,4);header[8]=8;header[9]=6;
  const pixels=Buffer.alloc(edge*(1+edge*4));
  for(let y=0;y<edge;y++) for(let x=0;x<edge;x++) pixels.set([color,160,140,255],y*(edge*4+1)+1+x*4);
  return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),...(metadata?[chunk('tEXt',Buffer.from('Comment\0'+metadata))]:[]),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);
}

async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tracer-companion-backup-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const bytes=png(1),url=await Images.storeGenerated(dir,bytes),state=Pet.fresh(1),id='custom_'+'a'.repeat(32);state.customs=[{id,name:'Synthetic buddy',kind:'creature',personality:'Calm',image:url}];state.unlocked.push('miso','garden_neon_orchid_shiny',id);state.selected=id;state.pets[id]={food:62,energy:81,joy:73,bond:68,sleeping:false};await Store.writeStore(dir,'workspace',JSON.stringify(Workspace.emptyWorkspace()));const service=createLocalAccounts(dir),backup=(await service.backupExport('',{preferences:{'tracer.pet.v1':JSON.stringify(state)}})).backup;return{dir,bytes,url,state,id,service,backup};}
test('v2 restores exact custom artwork, rare unlocks and relationship state after provider restart',async t=>{const f=await fixture(t);assert.equal(f.backup.payload.version,2);assert.equal(f.backup.payload.assets.length,1);await fs.unlink(path.join(f.dir,'.pet-art',f.url.split('/').at(-1)));const service=createLocalAccounts(f.dir),inspection=await service.backupInspect('',{backup:f.backup});await service.backupRestore('',{backup:f.backup,expected:inspection.expected,currentPreferences:{},confirm:true});assert.deepEqual(await Images.readAsset(f.dir,f.url),f.bytes);const w=await Store.readStore(f.dir,'workspace'),state=JSON.parse(w.meta.backupRestore.preferences['tracer.pet.v1']);assert.equal(state.selected,f.id);assert.equal(state.pets[f.id].bond,68);assert(state.unlocked.includes('garden_neon_orchid_shiny'));assert.equal(state.customs[0].image,f.url);assert.equal((await service.backupList('')).snapshots.length,1);});
test('damaged resource is rejected without touching workspace or existing artwork',async t=>{const f=await fixture(t),damaged=structuredClone(f.backup);damaged.payload.assets[0].data='AAAA';await assert.rejects(f.service.backupInspect('',{backup:damaged}),{code:'backup-checksum-mismatch'});assert.deepEqual(await Images.readAsset(f.dir,f.url),f.bytes);assert.equal((await Store.readStore(f.dir,'workspace')).meta.backupRestore,undefined);});
test('failed final workspace write rolls back only newly restored assets',async t=>{const f=await fixture(t);await fs.unlink(path.join(f.dir,'.pet-art',f.url.split('/').at(-1)));const inspection=await f.service.backupInspect('',{backup:f.backup}),original=Store.writeStore;Store.writeStore=async()=>{throw Error('synthetic disk failure')};try{await assert.rejects(f.service.backupRestore('',{backup:f.backup,expected:inspection.expected,currentPreferences:{},confirm:true}),{code:'backup-storage-unavailable'});}finally{Store.writeStore=original;}assert.equal(await Images.readAsset(f.dir,f.url),null);assert.equal((await Store.readStore(f.dir,'workspace')).meta.backupRestore,undefined);});

test('all sixteen animated companion pages preserve order and exact bytes',async t=>{const f=await fixture(t),pages=[];for(let i=0;i<16;i++)pages.push(await Images.storeGenerated(f.dir,png(768,'',120+i)));f.state.customs[0].image=pages[0];f.state.customs[0].animation={version:2,pages};const backup=(await f.service.backupExport('',{preferences:{'tracer.pet.v1':JSON.stringify(f.state)}})).backup;assert.equal(backup.payload.assets.length,16);for(const url of pages)await fs.unlink(path.join(f.dir,'.pet-art',url.split('/').at(-1)));const inspection=await f.service.backupInspect('',{backup});await f.service.backupRestore('',{backup,expected:inspection.expected,currentPreferences:{},confirm:true});const state=JSON.parse((await Store.readStore(f.dir,'workspace')).meta.backupRestore.preferences['tracer.pet.v1']);assert.deepEqual(state.customs[0].animation.pages,pages);for(let i=0;i<16;i++)assert.deepEqual(await Images.readAsset(f.dir,pages[i]),png(768,'',120+i));});

test('missing artwork refuses export instead of creating a partial companion backup',async t=>{const f=await fixture(t);await fs.unlink(path.join(f.dir,'.pet-art',f.url.split('/').at(-1)));await assert.rejects(f.service.backupExport('',{preferences:{'tracer.pet.v1':JSON.stringify(f.state)}}),{code:'backup-art-missing',status:409});assert.equal((await Store.readStore(f.dir,'workspace')).meta.backupRestore,undefined);});
