'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const F=require('../public/fishing-model'),A=require('../skins/tracer/fishing-aquatic-renderer'),R=require('../skins/tracer/fishing-rod-renderer');
const fish=F.catalog.fish.filter(f=>f.expansion===2),rods=F.catalog.rods.filter(r=>r.expansion===2);
test('expansion has fifty habitat-assigned creatures and seventy-five independently obtainable rods',()=>{assert.equal(fish.length,50);assert.equal(rods.length,75);assert.deepEqual(['common','rare','epic','legendary'].map(q=>fish.filter(f=>f.rarity===q).length),[22,18,8,2]);assert.deepEqual(['basic','myriad','journey','threekingdoms'].map(p=>rods.filter(r=>r.collection===p).length),[10,10,10,45]);for(const f of fish){assert(A.styles[f.id]);assert(F.catalog.spots.some(s=>s.habitats.includes(f.habitat)));}for(const r of rods){const pools=F.catalog.rodPools.filter(p=>p.rodIds.includes(r.id)||p.hiddenRodId===r.id);assert.equal(pools.length,1,r.id);assert.equal(pools[0].id,r.collection);}});
test('visible limb plans distinguish crabs, hermits, turtles and cephalopods',()=>{assert.equal(A.anatomy('rivercrab').walkingPairs,4);assert.equal(A.anatomy('icekingcrab').walkingPairs,3);assert.equal(A.anatomy('hermitcrab').walkingPairs,2);assert.equal(A.anatomy('crayfish').walkingPairs,4);assert.equal(A.anatomy('cuttlefish').arms,8);assert.equal(A.anatomy('cuttlefish').tentacles,2);assert.equal(A.anatomy('moonoctopus').arms,8);assert.equal(A.anatomy('chambernautilus').tentacles,90);for(const id of ['reedturtle','softshell','axolotl'])assert.equal(A.anatomy(id).limbs,4);});
test('walking, paddling and abdominal chains retain fixed bone lengths for a complete movement cycle',()=>{let checks=0;const distance=(p,q)=>Math.hypot(...p.map((n,i)=>n-q[i]));for(const f of fish)for(let frame=0;frame<121;frame++){const rig=A.articulation(f.id,frame/12,frame%2*.6),plan=A.anatomy(f.id);assert.equal(rig.legs.length,plan.walkingPairs*2);assert.equal(rig.paddles.length,plan.limbs);for(const leg of rig.legs)for(let j=0;j<2;j++){assert(Math.abs(distance(leg.points[j],leg.points[j+1])-leg.length)<1e-8,f.id+' rigid leg');checks++;}for(const limb of rig.paddles)for(let j=0;j<2;j++)assert(Math.abs(distance(limb.points[j],limb.points[j+1])-limb.lengths[j])<1e-8,f.id+' fixed paddle');for(let j=0;j<plan.abdominalJoints;j++)assert(Math.abs(distance(rig.abdomen[j],rig.abdomen[j+1])-.176)<1e-8,f.id+' abdominal joint');}assert(checks>10000);});
test('reduced motion freezes anatomy and bottom dwellers retain appropriate travel speeds',()=>{for(const f of fish)assert.deepEqual(A.articulation(f.id,0,.3,true),A.articulation(f.id,42,.3,true),f.id);assert.equal(A.travelRate('cockle'),0);assert(A.travelRate('seaurchin')<A.travelRate('rivercrab')/5);assert(A.travelRate('lotussnail')<A.travelRate('dace')/10);assert(A.bounds('cuttlefish')[0]>1.6);});
test('all new rods fit the live canvas at full load and retain a practical software fallback',()=>{for(const r of rods){const mesh=R.buildMesh(r.id,true);assert(mesh.triangles<28000,r.id+' software budget '+mesh.triangles);assert(mesh.vertices.every(Number.isFinite),r.id);for(const bend of[-.24,0,.24])for(let at=0;at<mesh.vertices.length;at+=14){const p=R.deformed([mesh.vertices[at],mesh.vertices[at+1],mesh.vertices[at+2]],bend);assert(p.x>-126&&p.x<376.8&&p.y>-126&&p.y<544,r.id+' clipping');}}});
test('all thirty-two new apparition assets are packaged PNGs matching their provenance hashes',()=>{const manifest=require('../docs/fishing-expansion-art-manifest.json');const rows=Array.isArray(manifest)?manifest:manifest.assets;assert.equal(rows.length,32);for(const row of rows){const bytes=fs.readFileSync(path.resolve(__dirname,'..',row.path));assert.equal(bytes.subarray(1,4).toString(),'PNG');assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),row.sha256,row.id);assert(row.prompt.length>100);assert.equal(row.transparentBackground,true);}});
test('historical unversioned imperial seal keeps tension reduction; the live catalogue describes its new reward skill',()=>{const session=id=>{const s=F.createSession(null,{rodId:id,seed:13});F.stepSession(s,{},900);F.stepSession(s,{release:true},0);for(let n=0;n<2000&&s.phase!=='bite';n++)F.stepSession(s,{},16);F.stepSession(s,{hook:true},0);assert.equal(s.phase,'reeling');return s;};const a=session('emperorjade'),b=session('zhugeliang');let verified=false;for(let frame=0;frame<300&&a.phase==='reeling'&&b.phase==='reeling';frame++){const beforeA=a.tension,beforeB=b.tension,input={holding:true};F.stepSession(a,input,16);F.stepSession(b,input,16);const da=a.tension-beforeA,db=b.tension-beforeB;if(db>0&&b.tension<.99){assert(Math.abs(da/db-.75)<1e-9);verified=true;break;}}assert(verified);assert(F.catalog.rods.find(r=>r.id==='emperorjade').effectDescription[1].includes('32.5%'));assert(!F.catalog.rods.find(r=>r.id==='sutrabundle').effectDescription[1].includes('25%'));});

test('rules 2 catches from the original 56-species roster survive expansion without rewriting',()=>{const saved=require('./fixtures/fishing-rules2.json').fishing;assert.deepEqual(F.validate(structuredClone(saved)),saved);assert(saved.casts.every(c=>c.rules===2));assert(saved.catches.length===3);const changed=structuredClone(saved);changed.casts.forEach(c=>c.rules=3);assert.throws(()=>F.validate(changed),'versioned old seeds must not be silently reinterpreted');});

test('new aquatic residents stay inside the glass and bottom dwellers plant their feet above the sand',()=>{const M=require('../skins/tracer/fishing-aquarium-motion');for(const f of fish)for(let t=0;t<24;t+=.17){const p=M.sample({id:'qa-'+f.id,speciesId:f.id,growth:100},{time:t,feed:{strength:.7,progress:.4}});for(const n of [p.x,p.y,p.z,p.angle,p.scale])assert(Number.isFinite(n),f.id);assert(p.x-p.extent.x>=-M.tank.x&&p.x+p.extent.x<=M.tank.x,f.id+' side glass');assert(p.z-p.extent.z>=-M.tank.z&&p.z+p.extent.z<=M.tank.z,f.id+' front glass');if(A.isBenthic(f.id)){assert(Math.abs(p.y-A.groundClearance(f.id)*p.scale-M.tank.bottom-.025)<1e-9,f.id+' foot plane');assert.equal(p.roll,0);assert.equal(p.pitch,0);assert(p.y+A.bounds(f.id)[1]*p.scale<M.tank.top,f.id+' water surface');}}});
