'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib'),Images=require('../lib/pet-image'),Pet=require('../skins/tracer/pet-model'),Model=require('../skins/tracer/model'),Store=require('../lib/store'),Portable=require('../lib/portable-backup');function crc(bytes) { let value = 0xffffffff; for (const byte of bytes) { value ^= byte; for(let i=0;i<8;i++) value=value&1?0xedb88320^(value>>>1):value>>>1; } return (value^0xffffffff)>>>0; }
function chunk(type, value) { const result=Buffer.alloc(value.length+12); result.writeUInt32BE(value.length);result.write(type,4);value.copy(result,8);result.writeUInt32BE(crc(result.subarray(4,-4)),result.length-4);return result; }
function png(edge=1, metadata='', color=120) {
  const header=Buffer.alloc(13);header.writeUInt32BE(edge);header.writeUInt32BE(edge,4);header[8]=8;header[9]=6;
  const pixels=Buffer.alloc(edge*(1+edge*4));
  for(let y=0;y<edge;y++) for(let x=0;x<edge;x++) pixels.set([color,160,140,255],y*(edge*4+1)+1+x*4);
  return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),...(metadata?[chunk('tEXt',Buffer.from('Comment\0'+metadata))]:[]),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);
}

async function room(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tracer-portable-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return dir;}async function setup(t){const root=await room(t),source=path.join(root,'source'),target=path.join(root,'target'),backup=path.join(root,'export');await fs.mkdir(source);await fs.mkdir(target);const bytes=png(1),url=await Images.storeGenerated(source,bytes),id='custom_'+'c'.repeat(32),state=Pet.fresh(1);state.customs=[{id,name:'Portable',kind:'creature',image:url,personality:''}];state.unlocked.push(id,'garden_neon_orchid_shiny');state.selected=id;state.pets[id]={food:62,energy:81,joy:73,bond:68,sleeping:false};const workspace=Model.emptyWorkspace();Model.addTask(workspace,{title:'Cross-root synthetic task'});await Store.writeStore(source,'workspace',JSON.stringify(workspace));await Store.writeStore(target,'workspace',JSON.stringify(Model.emptyWorkspace()));await Portable.exportDirectory(source,{'tracer.pet.v1':JSON.stringify(state)},backup);return{source,target,backup,state,bytes,url,id};}
test('explicit cross-root file restore preserves selection, unlock, bond, artwork and tasks without identities',async t=>{const f=await setup(t);await assert.rejects(Portable.restoreDirectory(f.backup,f.target,{}),{code:'backup-confirmation-required'});const result=await Portable.restoreDirectory(f.backup,f.target,{}, {confirm:true}),workspace=await Store.readStore(f.target,'workspace'),state=JSON.parse(workspace.meta.backupRestore.preferences['tracer.pet.v1']);assert.equal(state.selected,f.id);assert.equal(state.pets[f.id].bond,68);assert(state.unlocked.includes('garden_neon_orchid_shiny'));assert.equal(workspace.tasks[0].title,'Cross-root synthetic task');assert.deepEqual(await Images.readAsset(f.target,f.url),f.bytes);assert.equal((await Portable.inspectDirectory(result.snapshot)).assets.length,0);});
test('damaged files and failed commit never leave a partially restored workspace',async t=>{const f=await setup(t),asset=path.join(f.backup,'images',f.url.split('/').at(-1));await fs.writeFile(asset,'damaged');await assert.rejects(Portable.restoreDirectory(f.backup,f.target,{}, {confirm:true}),{code:'backup-invalid-assets'});assert.equal((await Store.readStore(f.target,'workspace')).tasks.length,0);await fs.writeFile(asset,f.bytes);const original=Store.writeStore;Store.writeStore=async()=>{throw Error('synthetic failure')};try{await assert.rejects(Portable.restoreDirectory(f.backup,f.target,{}, {confirm:true}),/synthetic failure/);}finally{Store.writeStore=original;}assert.equal(await Images.readAsset(f.target,f.url),null);assert.equal((await Store.readStore(f.target,'workspace')).tasks.length,0);});
test('multiple companions retain distinct selected state and both resources',async t=>{const f=await setup(t),second='custom_'+'d'.repeat(32),url=await Images.storeGenerated(f.source,png(1,'',145));f.state.customs.push({id:second,name:'Second',kind:'creature',personality:'',image:url});f.state.unlocked.push(second);f.state.selected=second;f.state.pets[second]={food:45,energy:80,joy:77,bond:28,sleeping:false};const directory=path.join(path.dirname(f.backup),'multi-export');const exported=await Portable.exportDirectory(f.source,{'tracer.pet.v1':JSON.stringify(f.state)},directory);assert.equal(exported.images,2);await Portable.restoreDirectory(directory,f.target,{}, {confirm:true});const state=JSON.parse((await Store.readStore(f.target,'workspace')).meta.backupRestore.preferences['tracer.pet.v1']);assert.equal(state.customs.length,2);assert.equal(state.selected,second);assert.equal(state.pets[second].bond,28);assert.deepEqual(await Images.readAsset(f.target,url),png(1,'',145));});
