'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const G=require('../public/task-garden'),M=require('../skins/tracer/model'),S=require('../public/workspace-sync');
const clone=value=>structuredClone(value);
function plant(ws,index,ticket=9999){const at=1000+index*10,task={id:'flower_'+index,title:'Step '+index,projectId:null,status:'doing',createdAt:at,updatedAt:at,doneAt:null,order:index};ws.tasks.push(task);G.taskChanged(ws,task,at,limit=>limit===10000?ticket:0);return task;}
function finish(ws,task,at=task.createdAt+1){task.status='done';task.updatedAt=at;task.doneAt=at;return G.taskChanged(ws,task,at);}
function series(count){const ws=M.emptyWorkspace();for(let i=1;i<=count;i++)finish(ws,plant(ws,i));return ws;}

test('the fishing edition retires flower elf and shiny guarantees for all new completions',()=>{const ws=M.emptyWorkspace();for(let i=1;i<=300;i++){const seed=finish(ws,plant(ws,i,i%100));assert.equal(seed.variant,'normal','completion '+i);assert.ok(seed.ticket>=100);assert.equal(seed.pityVersion,undefined);}const restored=S.validate(clone(ws));assert.ok(restored.taskGarden.seeds.every(s=>s.variant==='normal'));});

test('historical rare and shiny receipts stay unchanged across reading, merge and stale persistence',()=>{const ws=series(150);for(const [index,ticket] of [[29,1],[149,0]]){const seed=ws.taskGarden.seeds[index];seed.ticket=ticket;seed.variant=G.variant(ticket);seed.pityVersion=1;}const old=clone(ws.taskGarden),stale=clone(ws);assert.doesNotThrow(()=>G.validate(old));G.pity(ws);assert.deepEqual(ws.taskGarden,old);const merged=G.merge(old,old,old);assert.deepEqual(merged,old);delete stale.taskGarden;G.preserve(ws,stale);assert.deepEqual(stale.taskGarden,old);assert.equal(finish(ws,plant(ws,151,0)).variant,'normal');assert.deepEqual(ws.taskGarden.seeds.slice(0,150),old.seeds);});

test('first completion timestamps and flower identities survive repeated task transitions',()=>{const ws=series(30),task=ws.tasks.at(-1),first=clone(ws.taskGarden.seeds.at(-1));for(let i=0;i<3;i++){task.status='doing';task.updatedAt=11000+i*2;G.taskChanged(ws,task);finish(ws,task,11001+i*2);}assert.equal(ws.taskGarden.seeds.at(-1).completedAt,first.completedAt);assert.equal(ws.taskGarden.seeds.at(-1).ticket,first.ticket);assert.equal(ws.taskGarden.seeds.at(-1).variant,'normal');});

test('same-millisecond batches keep completion order without awarding a flower character',()=>{const ws=M.emptyWorkspace(),tasks=Array.from({length:30},(_,i)=>plant(ws,i+1)).reverse();tasks.forEach(task=>assert.equal(finish(ws,task,10000).variant,'normal'));for(let i=1;i<tasks.length;i++){const a=ws.taskGarden.seeds.find(s=>s.taskId===tasks[i-1].id),b=ws.taskGarden.seeds.find(s=>s.taskId===tasks[i].id);assert.ok(b.completedAt>a.completedAt);}});

test('concurrent completions merge as ordinary flowers and accepted identities cannot reroll',()=>{const base=series(28),a=plant(base,29),b=plant(base,30),local=clone(base),remote=clone(base);finish(local,local.tasks.find(t=>t.id===a.id));finish(remote,remote.tasks.find(t=>t.id===b.id));const merged=G.merge(base.taskGarden,local.taskGarden,remote.taskGarden);assert.deepEqual(G.merge(base.taskGarden,remote.taskGarden,local.taskGarden),merged);assert.ok(merged.seeds.every(s=>s.variant==='normal'));const accepted=clone(base);accepted.taskGarden=merged;const forged=clone(local);forged.taskGarden.seeds[0].ticket=0;forged.taskGarden.seeds[0].variant='shiny';G.preserve(accepted,forged);assert.equal(forged.taskGarden.seeds[0].variant,'normal');});

test('legacy imported memories and invalid old guarantee metadata remain validated',()=>{const imported=M.emptyWorkspace();G.importLegacy(imported,[{projectId:'old',plantKind:'wildflower',maturedAt:100,harvestedAt:200,ticket:0}]);assert.equal(G.read(imported).seeds[0].variant,'shiny');const ws=series(1);for(const value of [0,2,'1',null]){const raw=clone(ws.taskGarden);raw.seeds[0].pityVersion=value;assert.throws(()=>G.validate(raw),/Invalid task garden/);}const growing=M.emptyWorkspace();plant(growing,1);growing.taskGarden.seeds[0].pityVersion=1;assert.throws(()=>G.validate(growing.taskGarden),/Invalid task garden/);});
