'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require(process.env.TRACER_QA_PLAYWRIGHT||'playwright'),M=require('../skins/tracer/model'),G=require('../public/task-garden');
const root=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(root,'.cache/frames-')),data=path.join(output,'data');fs.mkdirSync(data);Object.assign(process.env,{DOCS_PORTAL_HOST:'127.0.0.1',DOCS_PORTAL_SKIN:'tracer',DOCS_PORTAL_DATA_DIR:data,DOCS_PORTAL_STATE_FILE:path.join(output,'state.json')});const {server}=require('../server'),frames=require('../public/frame-catalog.json'),materials=require('../public/wallpaper-catalog.json').filter(i=>i.type==='material');
const ws=M.emptyWorkspace();for(const [i,status]of ['todo','doing','review'].entries())M.addTask(ws,{title:['给热爱的事，留一点时间','收集一点新的灵感','把小小的愿望变成日常'][i],notes:'一步一步，慢慢靠近。',status,scheduled:M.todayISO(),due:M.todayISO(),priority:'high'});ws.taskGarden=G.read(ws);ws.taskGarden.market.testCredit={id:'test_frames',amount:100000,updatedAt:Date.now()};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1080}}),origin='http://127.0.0.1:'+server.address().port,errors=[];page.on('pageerror',e=>errors.push(e.message));
 const department=id=>page.locator('.store-navigation [data-store-action='+id+']'),action=()=>page.locator('[data-store-action=wall-buy]'),balance=()=>page.evaluate(()=>TaskGarden.economy(Tracer.store.base).balance);
 try{
  await page.goto(origin+'/?sec=shop');await page.waitForFunction(()=>Tracer.store.base);await page.selectOption('#language-select','zh');await page.click('#nav-shop');await department('avatarFrames').click();await page.waitForFunction(()=>document.querySelectorAll('.store-wall-card').length===6);await page.click('[data-wallpaper-id=af01]');assert.match(await action().textContent(),/登录/);await page.keyboard.press('Escape');
  const id=await page.evaluate(async()=>{const r=await TracerAccount.api('register',{email:'frames@example.com',password:'Frames test password 123',profile:{nickname:'Frame collector'}});TracerAccount.seedLanguage(r.user.id,'zh');return r.user.id;});const dir=path.join(data,'.accounts',id,'data');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'workspace.json'),JSON.stringify(ws));await page.reload();await page.waitForFunction(()=>TracerAccount.context.user&&Tracer.store.base);await page.click('#nav-shop');
  for(const [dept,id,slot]of [['avatarFrames','af01','avatarFrame'],['taskFrames','tf02','taskFrame'],['materials','m02','material']]){
   await department(dept).click();await page.locator('[data-wallpaper-id='+id+']').click();await action().click();await page.waitForFunction(id=>Tracer.store.base.taskGarden.market.wallpapers?.purchases.some(p=>p.itemId===id),id);await page.waitForFunction(()=>!document.querySelector('[data-store-action=wall-buy]').disabled);await action().click();await page.waitForFunction(({slot,id})=>Tracer.store.base.taskGarden.market.wallpapers.appearance[slot+'ItemId']===id,{slot,id});await page.keyboard.press('Escape');
  }
  assert.equal(await balance(),99380);await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.taskFrame==='nocturne'&&document.documentElement.dataset.avatarFrame==='laurel');assert.equal(await page.locator('html').getAttribute('data-wallpaper-material'),'porcelain');
  await page.click('[data-sec=board]');const card=page.locator('.card').first();assert.equal(await card.evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(32, 37, 44)');assert.equal(await card.locator('.card-title').evaluate(n=>getComputedStyle(n).color),'rgb(241, 232, 215)');await page.waitForTimeout(300);await page.screenshot({path:path.join(root,'docs/task-frame-priority.png')});
  // Every frame must keep its own text and surface under all ten material themes.
  const combos=await page.evaluate(({frames,materials})=>{const rows=[];for(const frame of frames.filter(i=>i.type==='taskFrame'))for(const material of materials){document.documentElement.dataset.wallpaperMaterial=material.material;TracerFrames.apply({catalog:frames,appearance:{taskFrameItemId:frame.id,avatarFrameItemId:'af01'}});const c=document.querySelector('.card'),s=getComputedStyle(c),t=getComputedStyle(c.querySelector('.card-title'));rows.push({frame:frame.id,material:material.id,bg:s.backgroundColor,title:t.color,border:s.borderRadius,fg:s.color});}return rows;},{frames,materials});for(const frame of frames.filter(i=>i.type==='taskFrame'))assert.equal(new Set(combos.filter(r=>r.frame===frame.id).map(r=>JSON.stringify([r.bg,r.title,r.border,r.fg]))).size,1,frame.id+' material precedence');
  await page.click('[data-sec=planner]');assert.equal(await page.locator('.pl-card-title').first().evaluate(n=>getComputedStyle(n).color),'rgb(238, 233, 250)');
  await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.taskFrame==='nocturne');await page.click('#account-open');await page.locator('.account-avatar-preview').waitFor();for(const selector of ['.account-trigger','.account-portrait','.account-avatar-preview'])assert.match(await page.locator(selector).evaluate(n=>getComputedStyle(n,'::after').backgroundImage),/frame-art\/af01-v2\.png/);await page.screenshot({path:path.join(output,'avatar-account.png')});await page.keyboard.press('Escape');
  await page.click('#nav-shop');await page.evaluate(async frames=>{await Promise.all(frames.map(item=>new Promise((resolve,reject)=>{const image=new Image();image.onload=resolve;image.onerror=()=>reject(new Error(item.asset));image.src=item.asset;})));},frames);for(const dept of ['avatarFrames','taskFrames']){await department(dept).click();await page.locator('.store-wall-grid').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.locator('.store-wallpapers').screenshot({path:path.join(root,dept==='avatarFrames'?'docs/avatar-frame-shop.png':'docs/task-frame-shop.png')});}
  for(const language of ['zh','en'])for(const width of [320,390,768,1440]){await page.selectOption('#language-select',language);await page.setViewportSize({width,height:1000});for(const dept of ['avatarFrames','taskFrames']){await department(dept).click();await page.waitForTimeout(70);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),language+' '+width);const geometry=await page.locator('.frame-preview').evaluateAll(nodes=>nodes.map(n=>{const rect=n.getBoundingClientRect();return[...n.querySelectorAll('.frame-caption,.frame-sample-footer,.frame-sample-title')].every(child=>{const r=child.getBoundingClientRect();return r.top>=rect.top&&r.bottom<=rect.bottom+1&&child.scrollWidth<=child.clientWidth+1;});}));assert.ok(geometry.every(Boolean),'preview geometry '+dept+' '+language+' '+width);}}
  // Photo portraits retain their crop and generated ornament on all account surfaces.
  await page.setViewportSize({width:1440,height:1080});await page.selectOption('#language-select','zh');
  await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='#9cb5a3';ctx.fillRect(0,0,64,64);ctx.fillStyle='#263e31';ctx.fillRect(16,16,32,32);await TracerAccount.api('profile',{...TracerAccount.context.user.profile,avatar:{kind:'image',value:c.toDataURL('image/png')}});});
  await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.avatarFrame==='laurel');await page.click('#account-open');
  for(const selector of ['.account-trigger','.account-portrait','.account-avatar-preview']){const n=page.locator(selector);await n.locator('img').waitFor();assert.equal(await n.locator('img').evaluate(img=>getComputedStyle(img).objectFit),'cover');assert.match(await n.evaluate(el=>getComputedStyle(el,'::after').backgroundImage),/af01-v2/);}
  await page.click('#account-tab-collection');await page.locator('#wallpaper-balance').waitFor();
  for(const [type,id]of [['avatarFrame','af01'],['taskFrame','tf02']]){await page.click('[data-wallpaper-filter='+type+']');assert.equal(await page.locator('.wallpaper-card').count(),6);await page.click('.wallpaper-card[data-wallpaper-id='+id+']');assert.ok(await page.locator('#wallpaper-action').isDisabled());}
  await page.keyboard.press('Escape');await page.click('#nav-shop');await department('avatarFrames').click();assert.equal(await page.locator('.frame-avatar img').count(),6);
  await department('taskFrames').click();await page.click('[data-store-action=default-taskFrame]');await page.waitForFunction(()=>!document.documentElement.dataset.taskFrame);assert.equal(await page.locator('html').getAttribute('data-wallpaper-material'),'porcelain');await page.click('[data-sec=board]');assert.notEqual(await card.evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(32, 37, 44)');
  await page.click('#nav-shop');await department('avatarFrames').click();await page.click('[data-store-action=default-avatarFrame]');await page.waitForFunction(()=>!document.documentElement.dataset.avatarFrame);assert.equal(await balance(),99380);await page.reload();await page.waitForFunction(()=>Tracer.store.base);assert.equal(await page.locator('html').getAttribute('data-task-frame'),null);assert.equal(await page.locator('html').getAttribute('data-avatar-frame'),null);
  assert.deepEqual(errors,[]);console.log('PASS: frame purchase/apply/reset/reload, avatar surfaces, planner cards, 60 material combinations, 320/390/768/1440 Chinese/English. '+output);
 }catch(e){await page.screenshot({path:path.join(output,'failure.png')});console.log('Failure screenshot '+output,errors);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
