(function(){
  'use strict';
  const A=window.TracerAccount,T=window.Tracer,trigger=document.getElementById('account-open');
  if(!A||!trigger)return;
  const tr=(zh,en)=>window.TracerLocale?.language()==='en'?en:zh;
  const icons={moon:'☾',leaf:'❧',star:'✧',flower:'✿',mountain:'△',cat:'ฅ',sun:'☀',cloud:'☁',aries:'♈',taurus:'♉',gemini:'♊',cancer:'♋',leo:'♌',virgo:'♍',libra:'♎',scorpio:'♏',sagittarius:'♐',capricorn:'♑',aquarius:'♒',pisces:'♓'};
  const avatarNames={moon:['月亮','Moon'],leaf:['叶子','Leaf'],star:['星星','Star'],flower:['花朵','Flower'],mountain:['山峰','Mountain'],cat:['猫咪','Cat'],sun:['太阳','Sun'],cloud:['云朵','Cloud']};
  Object.assign(avatarNames,{aries:['白羊座','Aries'],taurus:['金牛座','Taurus'],gemini:['双子座','Gemini'],cancer:['巨蟹座','Cancer'],leo:['狮子座','Leo'],virgo:['处女座','Virgo'],libra:['天秤座','Libra'],scorpio:['天蝎座','Scorpio'],sagittarius:['射手座','Sagittarius'],capricorn:['摩羯座','Capricorn'],aquarius:['水瓶座','Aquarius'],pisces:['双鱼座','Pisces']});
  const colors=['#c7d7a8','#9ccad9','#c2ade2','#e4b0bc','#e5c58d','#abb7c7'];
  const colorNames=[['苔绿','Moss'],['冰蓝','Ice'],['淡紫','Lilac'],['玫瑰','Rose'],['暖金','Gold'],['银灰','Silver']];
  const errors={
    'invalid-email':['请填写有效的邮箱地址。','Enter a valid email address.'], 'invalid-password':['密码需为 10–128 个字符。','Use a password with 10–128 characters.'],
    'invalid-profile':['请检查昵称、简介和空间名称的长度。','Check your nickname, bio and space name.'], 'invalid-avatar':['头像格式不支持，请重新选择图片。','Choose another avatar image.'],
    'email-in-use':['这个邮箱已在本机注册，请直接登录。','This email is registered on this computer. Sign in instead.'], 'invalid-credentials':['邮箱或密码不正确。','The email or password is incorrect.'],
    'invalid-recovery':['邮箱或恢复码不正确。','The email or recovery code is incorrect.'], 'session-expired':['登录已过期，请重新登录。','Your session expired. Sign in again.'],
    'account-changed':['账户状态已改变，请重新打开工作空间。','The account changed. Reopen your workspace.'], 'try-again-later':['尝试次数较多，请 15 分钟后重试。','Too many attempts. Try again in 15 minutes.'],
    'account-storage-unavailable':['暂时无法保存账户，请检查磁盘空间或权限后重试。','Account storage is unavailable. Check disk space and permissions.'],
    'readonly':['当前处于只读模式，无法更改账户。','This instance is read only.'], 'guest-already-imported':['游客工作区已导入其他账户。','The guest workspace was already imported into another account.'],
    'guest-empty':['游客工作区没有可导入的数据。','There is no guest workspace to import.'], 'account-not-empty':['当前账户已有数据，不能覆盖导入。','This account already has data and cannot be overwritten.'],
    'save-pending':['工作区尚未保存，请处理保存提示后重试。','Save your workspace before continuing.'], 'password-mismatch':['两次输入的密码不一致。','The passwords do not match.'],
    'avatar-too-large':['请选择不超过 5 MB 的图片。','Choose an image smaller than 5 MB.'], 'avatar-read-failed':['无法读取这张图片，请选择 PNG、JPEG 或 WebP。','Choose a valid PNG, JPEG or WebP image.'],
    'account-limit':['本机账户数量已达到上限。','This computer has reached its account limit.'], 'generation-pending':['请先暂停伙伴生成并等待草稿保存，再切换账户。','Pause companion generation and save its draft before switching accounts.'],
    'avatar-crop-pending':['请先确认或取消头像裁剪。','Apply or cancel the avatar crop first.']
  };
  let user=A.context.user,tab='profile',authTab='login',busy=false,selectedAvatar=user?.profile.avatar||{kind:'preset',value:'moon',color:colors[0],iconColor:'#000000'},recovery=null,afterRecovery=null,cropCleanup=null,cropPending=false;
  const dialog=document.createElement('dialog');dialog.className='account-dialog';dialog.id='account-dialog';dialog.setAttribute('aria-labelledby','account-title');document.body.append(dialog);
  function el(tag,className,parent,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;if(parent)parent.append(node);return node;}
  function button(parent,text,action,primary=false){const node=el('button','account-button'+(primary?' account-primary':''),parent,text);node.type='button';node.onclick=action;return node;}
  function field(parent,id,label,type='text',value='',extra={}){const wrap=el('label','account-field',parent);el('span','',wrap,label);const input=el(type==='textarea'?'textarea':'input','',wrap);input.id=id;input.name=id;if(type!=='textarea')input.type=type;input.value=value;Object.assign(input,extra);return input;}
  function notice(text,kind='success'){const node=document.getElementById('account-notice');if(node){node.textContent=text;node.className='account-notice '+kind;node.hidden=false;}}
  function failure(error){const pair=errors[error.message];notice(pair?tr(...pair):tr('操作未完成，请稍后重试。','The request did not finish. Try again.'),'error');}
  async function run(action){if(busy)return;busy=true;dialog.setAttribute('aria-busy','true');const controls=[...dialog.querySelectorAll('button,input,textarea,select')];const prior=new Map(controls.map(x=>[x,x.disabled]));controls.forEach(x=>x.disabled=true);try{await action();}catch(error){A.resume();failure(error);}finally{busy=false;dialog.removeAttribute('aria-busy');controls.filter(x=>x.isConnected).forEach(x=>x.disabled=prior.get(x));}}
  async function flush(){
    if(T.pet?.canSwitchAccount&&!T.pet.canSwitchAccount())throw new Error('generation-pending');
    if(T.pet?.prepareAccountSwitch)await T.pet.prepareAccountSwitch();
    await T.ready;const state=T.store;if(state.lost||state.conflict)throw new Error('save-pending');
    if(state.dirty)T.saveNow();const deadline=Date.now()+10000;while(state.inflight&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,40));
    if(state.dirty||state.inflight||state.lost||state.conflict)throw new Error('save-pending');
  }
  async function beginSwitch(){await flush();A.suspend();}
  function completeSwitch(){A.signal();location.reload();}
  function paintAvatar(node,value){node.replaceChildren();if(value?.kind==='image'){const image=el('img','',node);image.src=value.value;image.alt='';node.style.background='transparent';}else{node.textContent=(icons[value?.value]||'☾')+'\uFE0E';node.style.background=value?.color||colors[0];node.style.color=value?.iconColor||'#000000';} }
  function updateTrigger(){paintAvatar(trigger,user?.profile.avatar);trigger.title=user?user.profile.nickname:tr('游客 · 登录账户','Guest · Sign in');trigger.setAttribute('aria-label',trigger.title);}
  function header(){dialog.replaceChildren();const head=el('div','account-heading',dialog);const titles=el('div','',head);el('p','account-eyebrow',titles,'TRACER / '+tr('个人空间','PERSONAL SPACE'));el('h2','',titles,user?tr('我的账户','My account'):tr('让努力，有自己的归属。','A space of your own.')).id='account-title';const close=button(head,'×',()=>dialog.close());close.className='account-close';close.setAttribute('aria-label',tr('关闭账户面板','Close account panel'));const n=el('p','account-notice',dialog);n.id='account-notice';n.setAttribute('role','status');n.hidden=true;}
  function render(){if(cropCleanup)cropCleanup();header();if(recovery){renderRecovery();return;}if(!user){renderAuth();return;}
    const shell=el('div','account-shell',dialog),nav=el('aside','account-nav',shell),identity=el('div','account-identity',nav),portrait=el('div','account-portrait',identity);paintAvatar(portrait,user.profile.avatar);el('strong','',identity,user.profile.nickname);el('span','account-email',identity,user.email);el('span','account-mode',identity,tr('本机账户','Local account'));
    [['profile','个人资料','Profile'],['security','账户安全','Security'],['data','我的数据','My data'],['collection','装扮收藏','Appearance']].forEach(([id,zh,en])=>{const b=button(nav,tr(zh,en),()=>{tab=id;render();});b.className='account-nav-item'+(tab===id?' active':'');b.setAttribute('aria-pressed',String(tab===id));b.id='account-tab-'+id;});
    const logout=button(nav,tr('退出账户','Sign out'),()=>run(async()=>{await beginSwitch();await A.api('logout',{});completeSwitch();}));logout.className='account-signout';logout.id='account-logout';
    const content=el('section','account-content',shell);content.id='account-content';if(tab==='profile')renderProfile(content);if(tab==='security')renderSecurity(content);if(tab==='data')renderData(content);if(tab==='collection')renderCollection(content);
  }
  function renderAuth(){const shell=el('div','account-auth-shell',dialog),intro=el('aside','account-auth-intro',shell);el('span','account-intro-moon',intro,'☾');el('h3','',intro,tr('属于你的 Tracer','Your own Tracer'));el('p','',intro,tr('任务、花园与个人设置，都在自己的空间里慢慢积累。','Keep tasks, your garden and personal preferences together in your own space.'));
    ['独立工作区|Separate workspace','可自定义头像与昵称|Your own avatar and name','恢复码找回密码|Recover access with a recovery code'].forEach(text=>{const [zh,en]=text.split('|');el('p','account-auth-feature',intro,'✧ '+tr(zh,en));});
    el('p','account-local-note',intro,tr('账户与数据保存在这台电脑。邮箱用于登录标识，不发送验证邮件。','Accounts and data stay on this computer. Your email is a login identifier; no verification email is sent.'));
    const content=el('section','account-auth-content',shell),tabs=el('div','account-auth-tabs',content);
    [['login','登录','Sign in'],['register','创建账户','Create account'],['recover','找回密码','Recover']].forEach(([id,zh,en])=>{const b=button(tabs,tr(zh,en),()=>{authTab=id;render();});b.className='account-auth-tab'+(authTab===id?' active':'');b.id='account-auth-'+id;b.setAttribute('aria-pressed',String(authTab===id));});
    const form=el('form','account-form',content);form.autocomplete='on';
    const address=field(form,'account-email',tr('邮箱地址','Email address'),'email','',{required:true,maxLength:254,autocomplete:'username'});
    let nickname,pass,confirm,code;
    if(authTab==='register')nickname=field(form,'account-nickname',tr('昵称','Nickname'),'text','',{required:true,maxLength:32,autocomplete:'nickname'});
    if(authTab==='recover')code=field(form,'account-recovery-input',tr('注册时保存的恢复码','Your saved recovery code'),'text','',{required:true,maxLength:80,autocomplete:'off',spellcheck:false});
    pass=field(form,'account-password',authTab==='recover'?tr('设置新密码','New password'):tr('密码','Password'),'password','',{required:true,minLength:10,maxLength:128,autocomplete:authTab==='login'?'current-password':'new-password'});
    if(authTab!=='login')confirm=field(form,'account-password-confirm',tr('再次输入密码','Confirm password'),'password','',{required:true,minLength:10,maxLength:128,autocomplete:'new-password'});
    el('p','account-help',form,tr('密码至少 10 个字符，支持粘贴和密码管理器。','At least 10 characters. Pasting and password managers are supported.'));
    const submit=el('button','account-button account-primary',form,authTab==='login'?tr('登录我的空间','Sign in'):authTab==='register'?tr('创建本机账户','Create local account'):tr('重设密码','Reset password'));submit.type='submit';submit.id='account-auth-submit';
    form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;run(async()=>{if(confirm&&confirm.value!==pass.value)throw new Error('password-mismatch');await beginSwitch();let result;
      if(authTab==='register'){result=await A.api('register',{email:address.value,password:pass.value,profile:{nickname:nickname.value}});A.seedLanguage(result.user.id,window.TracerLocale?.language()||'zh');recovery=result.recoveryCode;afterRecovery='enter';render();}
      else if(authTab==='login'){result=await A.api('login',{email:address.value,password:pass.value});A.seedLanguage(result.user.id,window.TracerLocale?.language()||'zh');completeSwitch();}
      else{result=await A.api('recover',{email:address.value,newPassword:pass.value,recoveryCode:code.value});recovery=result.recoveryCode;afterRecovery='login';render();}
    });};
    button(content,tr('继续使用游客空间','Continue as guest'),()=>{if(A.scope==='locked')run(async()=>{await A.api('logout',{});completeSwitch();});else dialog.close();}).className='account-text-button';
  }
  function renderRecovery(){dialog.querySelector('.account-close').hidden=true;const content=el('section','account-recovery',dialog);el('span','account-recovery-icon',content,'✧');el('h3','',content,tr('保存你的恢复码','Save your recovery code'));el('p','',content,tr('忘记密码时，它可以帮你找回这个本机账户。恢复码只在这里显示，请保存在安全的地方。','Use this code to recover your local account if you forget the password. It is shown only here; keep it somewhere safe.'));const code=el('code','account-recovery-code',content,recovery);code.id='account-recovery-code';button(content,tr('下载恢复码','Download recovery code'),()=>download('tracer-recovery-code.txt',tr('Tracer 本机账户恢复码\n请保密保存。\n','Tracer local account recovery code\nKeep this private.\n')+recovery+'\n','text/plain'));
    const saved=el('label','account-check-label',content),check=el('input','',saved);check.type='checkbox';check.id='account-recovery-saved';el('span','',saved,tr('我已妥善保存恢复码','I have saved my recovery code'));
    const next=button(content,afterRecovery==='enter'?tr('进入我的空间','Enter my space'):tr('完成','Done'),()=>{recovery=null;if(afterRecovery==='enter')completeSwitch();else{A.resume();afterRecovery=null;authTab='login';render();notice(tr('恢复码已更新，旧恢复码已失效。','Your recovery code was replaced. The old code no longer works.'));}},true);next.id='account-recovery-continue';next.disabled=true;check.onchange=()=>next.disabled=!check.checked;
  }
  function renderProfile(content){el('h3','',content,tr('让空间更像你','Make it yours'));el('p','account-help',content,tr('资料仅在本机账户中展示。','Your profile is shown in this local account.'));const form=el('form','account-form',content),avatarRow=el('div','account-avatar-editor',form),preview=el('div','account-avatar-preview',avatarRow);selectedAvatar=structuredClone(user.profile.avatar);paintAvatar(preview,selectedAvatar);
    const choices=el('div','account-avatar-options',avatarRow);const presets=el('div','account-avatar-groups',choices);
    [Object.keys(icons).slice(0,8),Object.keys(icons).slice(8)].forEach((group,index)=>{el('span','account-avatar-label',presets,index?tr('十二星座','Zodiac signs'):tr('基础图案','Symbols'));const row=el('div','account-avatar-presets',presets);group.forEach(id=>{const b=button(row,icons[id]+'\uFE0E',()=>{selectedAvatar={kind:'preset',value:id,color:selectedAvatar.color||colors[0],iconColor:selectedAvatar.iconColor||'#000000'};paintAvatar(preview,selectedAvatar);updateAvatarSelection();});b.dataset.avatar=id;b.setAttribute('aria-label',tr(...avatarNames[id]));b.title=tr(...avatarNames[id]);});});
    el('span','account-avatar-label',choices,tr('背景颜色','Background color'));const palette=el('div','account-avatar-colors',choices);colors.forEach((color,index)=>{const b=button(palette,'',()=>{selectedAvatar={kind:'preset',value:selectedAvatar.kind==='preset'?selectedAvatar.value:'moon',color,iconColor:selectedAvatar.iconColor||'#000000'};paintAvatar(preview,selectedAvatar);updateAvatarSelection();});b.style.background=color;b.dataset.color=color;b.setAttribute('aria-label',tr(...colorNames[index]));});
    const colorRow=el('div','account-symbol-color',choices),colorLabel=el('label','',colorRow);colorLabel.htmlFor='account-icon-color';colorLabel.textContent=tr('图案颜色','Symbol color');const iconColor=el('input','',colorRow);iconColor.id='account-icon-color';iconColor.type='color';iconColor.setAttribute('aria-label',tr('选择图案颜色','Choose symbol color'));const black=button(colorRow,tr('恢复黑色','Reset to black'),()=>changeSymbolColor('#000000'));
    function changeSymbolColor(color){if(selectedAvatar.kind!=='preset')return;selectedAvatar.iconColor=color;paintAvatar(preview,selectedAvatar);updateAvatarSelection();}iconColor.oninput=()=>changeSymbolColor(iconColor.value);
    function updateAvatarSelection(){presets.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(selectedAvatar.kind==='preset'&&selectedAvatar.value===b.dataset.avatar)));palette.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(selectedAvatar.color===b.dataset.color)));iconColor.value=selectedAvatar.iconColor||'#000000';iconColor.disabled=black.disabled=selectedAvatar.kind!=='preset';}updateAvatarSelection();
    const upload=field(form,'account-avatar-file',tr('上传头像','Upload avatar'),'file');upload.accept='image/png,image/jpeg,image/webp';const cropHost=el('div','account-crop-host',form);cropHost.hidden=true;upload.onchange=()=>run(async()=>{if(upload.files[0])await cropAvatar(upload.files[0],cropHost,value=>{selectedAvatar={kind:'image',value};paintAvatar(preview,selectedAvatar);updateAvatarSelection();},()=>{upload.value='';});});
    const nickname=field(form,'account-profile-nickname',tr('昵称','Nickname'),'text',user.profile.nickname,{required:true,maxLength:32});const space=field(form,'account-profile-space',tr('空间名称','Space name'),'text',user.profile.workspaceName,{maxLength:48,placeholder:tr('例如：Andy 的工作室','For example: Andy’s studio')});const bio=field(form,'account-profile-bio',tr('个人简介','Bio'),'textarea',user.profile.bio,{maxLength:160,rows:3});
    const submit=el('button','account-button account-primary',form,tr('保存资料','Save profile'));submit.type='submit';submit.id='account-profile-save';form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;run(async()=>{if(cropPending)throw new Error('avatar-crop-pending');const result=await A.api('profile',{nickname:nickname.value,workspaceName:space.value,bio:bio.value,avatar:selectedAvatar});user=result.user;A.context.user=user;updateTrigger();render();notice(tr('个人资料已保存。','Profile saved.'));});};
  }
  function renderSecurity(content){el('h3','',content,tr('密码与恢复','Password & recovery'));const form=el('form','account-form account-security-form',content);const current=field(form,'account-current-password',tr('当前密码','Current password'),'password','',{required:true,maxLength:128,autocomplete:'current-password'});const next=field(form,'account-new-password',tr('新密码','New password'),'password','',{required:true,minLength:10,maxLength:128,autocomplete:'new-password'});const confirm=field(form,'account-new-password-confirm',tr('再次输入新密码','Confirm new password'),'password','',{required:true,minLength:10,maxLength:128,autocomplete:'new-password'});const submit=el('button','account-button',form,tr('更新密码并退出其他会话','Update password & sign out other sessions'));submit.type='submit';form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;run(async()=>{if(next.value!==confirm.value)throw new Error('password-mismatch');await A.api('password',{currentPassword:current.value,newPassword:next.value});form.reset();A.signal();notice(tr('密码已更新，其他登录会话已退出。','Password updated. Other sessions were signed out.'));loadSessions(sessions);});};
    const recover=el('form','account-form account-recovery-form',content);el('h4','',recover,tr('更换恢复码','Replace recovery code'));el('p','account-help',recover,tr('旧恢复码将立即失效。更换后请下载保存新恢复码。','The old code will stop working. Download the replacement code.'));const pw=field(recover,'account-code-password',tr('输入当前密码','Enter current password'),'password','',{required:true,maxLength:128,autocomplete:'current-password'});const replace=el('button','account-button',recover,tr('生成新的恢复码','Generate a new recovery code'));replace.type='submit';recover.onsubmit=e=>{e.preventDefault();if(recover.reportValidity())run(async()=>{const result=await A.api('recovery-code',{password:pw.value});recovery=result.recoveryCode;afterRecovery='profile';render();});};
    el('h4','',content,tr('本机登录会话','Sessions on this computer'));const sessions=el('div','account-sessions',content);loadSessions(sessions);
  }
  async function loadSessions(target){target.textContent=tr('正在读取…','Loading…');try{const result=await A.api('sessions');if(!target.isConnected)return;target.replaceChildren();result.sessions.forEach(session=>{const row=el('div','account-session',target),info=el('div','',row);el('strong','',info,session.label+(session.current?tr(' · 当前',' · Current'):''));el('span','account-help',info,new Date(session.createdAt).toLocaleString());if(!session.current)button(row,tr('退出','Sign out'),()=>run(async()=>{await A.api('revoke-session',{id:session.id});await loadSessions(target);notice(tr('该会话已退出。','Session signed out.'));}));});}catch(error){if(target.isConnected)target.textContent=tr('暂时无法读取登录会话。','Sessions are unavailable right now.');}}
  function renderData(content){el('h3','',content,tr('我的数据','My data'));const status=el('div','account-data-status',content);el('span','',status,'◉');el('div','',status,tr('保存在本机 · 云服务未连接','Saved locally · Cloud service not connected'));el('p','account-help',content,tr('任务、笔记和花园属于当前账户。更换电脑前请导出备份。','Tasks, notes and your garden belong to this account. Export a backup before changing computers.'));
    button(content,tr('导出账户资料与工作区','Export profile & workspace'),()=>run(async()=>{await flush();const data=await A.api('export');data.preferences=A.exportPreferences();download('tracer-account-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data,null,2),'application/json');notice(tr('导出文件已准备好，包含当前账户资料与工作区，不含密码、恢复码或 AI 密钥。','Export prepared with your profile and workspace, excluding passwords, recovery codes and AI keys.'));})).id='account-export';
    const section=el('section','account-import',content);el('h4','',section,tr('导入游客工作区','Import guest workspace'));const text=el('p','account-help',section,tr('正在检查游客数据…','Checking guest data…'));
    A.api('guest-preview').then(result=>{if(!section.isConnected)return;text.textContent=result.pendingImport?tr('上次导入尚未完成，可以安全重试。','The previous import is incomplete. You can safely retry.'):result.alreadyImported?tr('这份游客工作区已经导入当前账户。','This guest workspace was already imported.'):result.claimed?tr('这份游客工作区已导入另一个账户。','This guest workspace was imported into another account.'):result.targetHasData?tr('当前账户已有数据。为避免覆盖，不能再导入游客工作区。','This account already has data. Guest import is disabled to prevent overwriting it.'):tr('游客空间：','Guest space: ')+result.counts.tasks+tr(' 个任务 · ',' tasks · ')+result.counts.notes+tr(' 篇笔记 · ',' notes · ')+result.counts.projects+tr(' 个项目',' projects');
      if(!result.available)return;el('p','account-help',section,tr('将复制游客任务、笔记、项目、完成历史和花园金币。原游客数据保留；同一份数据只能导入一个账户。伙伴草稿和 AI 密钥不导入。','Copies guest tasks, notes, projects, history and garden coins. Guest data stays intact and can be imported into only one account. Companion drafts and AI keys are excluded.'));
      const label=el('label','account-check-label',section),check=el('input','',label);check.type='checkbox';check.id='account-import-confirm';el('span','',label,tr('我确认把这份游客数据导入当前账户','Import this guest data into my current account'));const importButton=button(section,tr('确认导入','Import workspace'),()=>run(async()=>{await beginSwitch();await A.api('import-guest',{});completeSwitch();}),true);importButton.id='account-import-guest';importButton.disabled=true;check.onchange=()=>importButton.disabled=!check.checked;
    }).catch(()=>{if(text.isConnected)text.textContent=tr('暂时无法读取游客数据，请稍后重试。','Guest data is unavailable. Try again later.');});
  }
  function renderCollection(content){window.TracerWallpapers.mount(content,{flush,run,notice});}
  function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function cropAvatar(file,host,apply,cancel){
    if(file.size>5*1024*1024)throw new Error('avatar-too-large');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('avatar-read-failed');
    let bitmap;try{bitmap=await createImageBitmap(file);}catch{throw new Error('avatar-read-failed');}if(!bitmap.width||!bitmap.height||bitmap.width*bitmap.height>25000000){bitmap.close();throw new Error('avatar-read-failed');}
    if(cropCleanup)cropCleanup();cropPending=true;host.replaceChildren();host.hidden=false;let zoom=1,x=0,y=0,drag=null;
    const title=el('strong','',host,tr('调整头像位置','Adjust avatar position'));title.id='account-crop-label';el('p','account-help',host,tr('拖动图片调整位置，或聚焦图片后使用方向键。缩放可放大细节；圆框用于预览头像显示区域。','Drag to reposition, or focus the image and use arrow keys. Zoom in for detail; the circle previews your avatar.'));
    const stage=el('div','account-crop-stage',host),canvas=el('canvas','',stage);canvas.id='account-crop-canvas';canvas.width=canvas.height=512;canvas.tabIndex=0;canvas.setAttribute('aria-label',tr('拖动或使用方向键调整头像位置','Drag or use arrow keys to reposition avatar'));el('div','account-crop-guide',stage).setAttribute('aria-hidden','true');
    const zoomLabel=el('label','account-crop-zoom',host);el('span','',zoomLabel,tr('缩放','Zoom'));const slider=el('input','',zoomLabel);slider.id='account-crop-zoom';slider.type='range';slider.min='1';slider.max='3';slider.step='.01';slider.value='1';const output=el('output','',zoomLabel,'100%');
    function draw(target){const size=target.width,cover=Math.max(1/bitmap.width,1/bitmap.height)*zoom,w=bitmap.width*cover,h=bitmap.height*cover;x=Math.max(-(w-1)/2,Math.min((w-1)/2,x));y=Math.max(-(h-1)/2,Math.min((h-1)/2,y));const c=target.getContext('2d');c.clearRect(0,0,size,size);c.drawImage(bitmap,(1-w)/2*size+x*size,(1-h)/2*size+y*size,w*size,h*size);}
    function update(){draw(canvas);output.textContent=Math.round(zoom*100)+'%';canvas.dataset.cropX=x.toFixed(4);canvas.dataset.cropY=y.toFixed(4);}
    slider.oninput=()=>{zoom=Number(slider.value);update();};canvas.onpointerdown=event=>{drag={x:event.clientX,y:event.clientY,id:event.pointerId};canvas.setPointerCapture(event.pointerId);canvas.focus();};canvas.onpointermove=event=>{if(!drag||drag.id!==event.pointerId)return;const rect=canvas.getBoundingClientRect();x+=(event.clientX-drag.x)/rect.width;y+=(event.clientY-drag.y)/rect.height;drag={x:event.clientX,y:event.clientY,id:event.pointerId};update();};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};canvas.onkeydown=event=>{const step=event.shiftKey ? .08 : .02;if(event.key==='ArrowLeft')x-=step;else if(event.key==='ArrowRight')x+=step;else if(event.key==='ArrowUp')y-=step;else if(event.key==='ArrowDown')y+=step;else return;event.preventDefault();update();};
    const controls=el('div','account-crop-actions',host);button(controls,tr('居中重置','Reset position'),()=>{zoom=1;x=0;y=0;slider.value='1';update();});button(controls,tr('取消','Cancel'),()=>{cropCleanup();cancel();});const confirm=button(controls,tr('确认裁剪','Apply crop'),()=>{const result=document.createElement('canvas');result.width=result.height=192;draw(result);const value=result.toDataURL('image/png');cropCleanup();apply(value);},true);confirm.id='account-crop-apply';
    cropCleanup=()=>{bitmap.close();host.hidden=true;host.replaceChildren();cropPending=false;cropCleanup=null;};update();canvas.focus();
  }
  dialog.addEventListener('cancel',event=>{if(busy||recovery)event.preventDefault();});dialog.addEventListener('close',()=>{if(cropCleanup)cropCleanup();if(!recovery)dialog.replaceChildren();trigger.focus();});
  trigger.onclick=()=>{if(A.locked){A.lock();return;}render();dialog.showModal();};
  updateTrigger();
})();
