(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.TracerFishingTackle=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
  'use strict';
  const escape=value=>String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const hook='<svg viewBox="0 0 200 190" fill="none" aria-hidden="true"><defs><linearGradient id="tackle-hook-metal" x1="65" y1="60" x2="140" y2="170" gradientUnits="userSpaceOnUse"><stop stop-color="#bdc9c5"/><stop offset=".5" stop-color="#697c79"/><stop offset="1" stop-color="#d5ddd5"/></linearGradient></defs><path d="M101 0v72" stroke="#7d8b7e" stroke-width="1.4"/><circle cx="101" cy="79" r="6" stroke="#83968d" stroke-width="3"/><path d="M101 85v42c0 29 37 39 50 12 4-8 4-20 1-30l-7 10" stroke="url(#tackle-hook-metal)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="m152 109-1 13" stroke="#748a80" stroke-width="2"/></svg>';
  const tools='<svg viewBox="0 0 120 100" fill="none" aria-hidden="true"><ellipse cx="66" cy="62" rx="33" ry="24" fill="#9da98c"/><ellipse cx="66" cy="58" rx="28" ry="20" fill="#c4c6a7" stroke="#6d7e63" stroke-width="3"/><ellipse cx="66" cy="58" rx="16" ry="11" stroke="#8e9a7a" stroke-width="8"/><ellipse cx="66" cy="58" rx="5" ry="4" fill="#66795e"/><path d="m33 26 41 11M33 36l42-12" stroke="#aebbb1" stroke-width="5" stroke-linecap="round"/><circle cx="24" cy="23" r="9" stroke="#777c61" stroke-width="5"/><circle cx="24" cy="40" r="9" stroke="#777c61" stroke-width="5"/><path d="M65 71c-32 6-40 19-28 18" stroke="#d5dfc7" stroke-width="1.5"/></svg>';
  let tackleSerial=0;
  function create(host,options={}){
    if(!host?.ownerDocument)throw new Error('A tackle box host is required.');
    const doc=host.ownerDocument,win=doc.defaultView||root,element=doc.createElement('section'),hookArt=hook.replaceAll('tackle-hook-metal','tackle-hook-metal-'+(++tackleSerial));element.className='fishing-tackle'+(options.compact?' is-compact':'');element.dataset.mode=options.mode==='shop'?'shop':'equip';host.appendChild(element);
    let snapshot=null,selectedId=options.selectedId||'',signature='',destroyed=false;
    const tr=(zh,en)=>snapshot?.language==='en'?en:zh;
    const name=item=>Array.isArray(item?.name)?item.name[snapshot?.language==='en'?1:0]:item?.name||'';
    const catalog=()=>snapshot?.catalog||win.TracerFishingModel?.catalog||root.TracerFishingModel?.catalog||{baits:[],fish:[]};
    const art=()=>win.TracerFishingArt||root.TracerFishingArt||{};
    const baitArt=bait=>art().baitMarkup?.(bait)||'';
    const number=value=>Math.max(0,Number(value)||0);
    const focusNode=key=>Array.from(element.querySelectorAll('[data-tackle-focus]')).find(node=>node.dataset.tackleFocus===key);
    const restoreFocus=key=>{const node=focusNode(key);(node&&!node.disabled?node:focusNode('slot-'+selectedId))?.focus({preventScroll:true});};
    function render(){
      if(destroyed||!snapshot)return;
      const entries=catalog().baits||[],state=snapshot.state||{},inventory=state.baits||{},shop=element.dataset.mode==='shop',busy=!!snapshot.busy;
      if(!entries.length){element.replaceChildren();return;}
      if(!entries.some(b=>b.id===selectedId))selectedId=state.equippedBaitId||entries[0].id;
      const selected=entries.find(b=>b.id===selectedId)||entries[0],equipped=entries.find(b=>b.id===state.equippedBaitId),count=number(inventory[selected.id]),balance=number(snapshot.economy?.balance),loaded=selected.id===state.equippedBaitId&&count>0;
      const key=JSON.stringify([snapshot.language,entries,inventory,state.equippedBaitId,selected.id,shop,busy,balance,snapshot.error]);if(key===signature)return;signature=key;
      const focus=doc.activeElement?.closest('[data-tackle-focus]'),focusKey=element.contains(focus)?focus?.dataset.tackleFocus:'';
      const fish=(selected.fishIds||[]).map(id=>(catalog().fish||[]).find(f=>f.id===id)).filter(Boolean),action=shop?'buy-bait':count?'equip-bait':'open-shop',disabled=busy||(shop?balance<number(selected.price):loaded);
      const label=shop?tr('买一袋 · ','Buy a pack · ')+'◈ '+selected.price:count?loaded?tr('已装上鱼钩','On the hook'):tr('装上鱼钩','Bait the hook'):tr('去鱼饵铺补充 →','Restock at the bait counter →');
      element.setAttribute('aria-label',tr(shop?'鱼饵铺钓具箱':'我的钓具箱',shop?'Bait counter tackle box':'My tackle box'));
      element.innerHTML='<header class="fishing-tackle-header"><div class="fishing-tackle-plaque"><span>'+tr('湖畔钓具','LAKESIDE TACKLE')+'</span><strong>'+tr(shop?'鱼饵铺':'我的钓具箱',shop?'The bait counter':'My tackle box')+'</strong></div><div class="fishing-tackle-loaded"><span>'+tr('当前鱼钩','ON YOUR HOOK')+'</span><div>'+ (equipped?'<i>'+baitArt(equipped)+'</i><b>'+escape(name(equipped))+'</b><small>× '+number(inventory[equipped.id])+'</small>':'—')+'</div></div></header>'+
        '<div class="fishing-tackle-body"><div class="fishing-tackle-chest"><i class="fishing-tackle-hinge left" aria-hidden="true"></i><i class="fishing-tackle-hinge right" aria-hidden="true"></i><div class="fishing-tackle-lid"><span>'+tr('挑一份鱼饵，装上新的期待。','Pick a bait. Make room for a surprise.')+'</span><i aria-hidden="true"></i></div><div class="fishing-tackle-tray" role="group" aria-label="'+tr('选择鱼饵','Choose bait')+'">'+entries.map((b,i)=>{
          const qty=number(inventory[b.id]),active=b.id===selected.id,onHook=b.id===state.equippedBaitId&&qty>0;return'<button type="button" class="fishing-tackle-slot'+(active?' is-selected':'')+(qty||shop?'':' is-empty')+'" data-bait-id="'+escape(b.id)+'" data-tackle-focus="slot-'+escape(b.id)+'" aria-pressed="'+active+'" aria-label="'+escape(name(b)+'，'+tr('库存 ','In bag ')+qty+(onHook?tr('，已装钩',', on your hook'):''))+'" tabindex="'+(active?0:-1)+'"><span class="fishing-tackle-slot-art">'+baitArt(b)+'</span><span class="fishing-tackle-slot-label">'+escape(name(b))+'</span><span class="fishing-tackle-stock">'+(qty?'× '+qty:shop?tr('未持有','New'):tr('缺货','Empty'))+'</span>'+(onHook?'<i class="fishing-tackle-pin" title="'+tr('已装钩','On the hook')+'" aria-hidden="true">⌁</i>':'')+'<span class="fishing-tackle-slot-no" aria-hidden="true">'+String(i+1).padStart(2,'0')+'</span></button>';
        }).join('')+'<div class="fishing-tackle-tools" aria-hidden="true">'+tools+'<span>'+tr('钩 · 线 · 小工具','HOOKS & THREAD')+'</span></div></div><div class="fishing-tackle-latch" aria-hidden="true"></div></div>'+
        '<div class="fishing-tackle-bay" data-selected-bait="'+escape(selected.id)+'"><div class="fishing-tackle-hook-stage"><span class="fishing-tackle-stage-label">'+tr('试饵台','BAITING STAND')+'</span><div class="fishing-tackle-hook">'+hookArt+'</div><div class="fishing-tackle-hero-art">'+baitArt(selected)+'</div><i class="fishing-tackle-stage-shadow" aria-hidden="true"></i><span class="fishing-tackle-stage-stock">'+tr('背包剩余 ','In bag ')+count+'</span></div><div class="fishing-tackle-detail"><span class="fishing-tackle-detail-overline">'+(shop?tr('一袋 '+selected.quantity+' 份','PACK OF '+selected.quantity):loaded?tr('准备出发','READY TO CAST'):count?tr('准备装钩','READY TO BAIT'):tr('还没有这份鱼饵','NOT IN YOUR BAG'))+'</span><h3>'+escape(name(selected))+'</h3><p>'+escape(name({name:selected.description}))+'</p><div class="fishing-tackle-fish-heading"><span>'+tr('它们可能会来','THEY MAY COME TO VISIT')+'</span><i aria-hidden="true">⌁</i></div><div class="fishing-tackle-fish-water">'+fish.map((f,i)=>'<span class="fishing-tackle-visiting-fish" style="--fish-order:'+i+'" title="'+escape(name(f))+'" aria-label="'+escape(name(f))+'">'+(art().fishMarkup?.(f)||'')+'<small>'+escape(name(f))+'</small></span>').join('')+'</div><div class="fishing-tackle-action-row"><button type="button" class="fishing-tackle-primary" data-tackle-action="'+action+'" data-bait-id="'+escape(selected.id)+'" data-tackle-focus="primary" '+(disabled?'disabled':'')+'>'+escape(label)+'</button>'+(!shop&&count?'<button type="button" class="fishing-tackle-restock" data-tackle-action="open-shop" data-bait-id="'+escape(selected.id)+'" data-tackle-focus="restock"'+(busy?' disabled':'')+'>'+tr('补充鱼饵','Restock')+'</button>':'')+'</div><p class="fishing-tackle-footnote">'+escape(shop?balance<number(selected.price)?tr('金币还差 '+(selected.price-balance)+' 枚。','You need '+(selected.price-balance)+' more coins.'):tr('◈ '+balance+' · 点击购买获得 '+selected.quantity+' 份','◈ '+balance+' · One purchase gives '+selected.quantity+' pieces'):tr('每次抛竿使用 1 份鱼饵。','Each cast uses one piece of bait.'))+'</p></div></div></div><div class="fishing-tackle-announcement" aria-live="polite">'+escape(name(selected))+'</div>';
      if(focusKey)restoreFocus(focusKey);
    }
    function select(id,focus){if(destroyed)return;selectedId=id;signature='';render();if(focus)focusNode('slot-'+id)?.focus({preventScroll:true});}
    function click(event){const slot=event.target.closest('.fishing-tackle-slot');if(slot&&element.contains(slot)){select(slot.dataset.baitId,true);return;}const button=event.target.closest('[data-tackle-action]');if(!button||button.disabled||!element.contains(button)||snapshot?.busy)return;options.onAction?.(button.dataset.tackleAction,button.dataset.baitId);}
    function keydown(event){const slot=event.target.closest('.fishing-tackle-slot');if(!slot||!element.contains(slot))return;const entries=catalog().baits||[],index=entries.findIndex(b=>b.id===slot.dataset.baitId),columns=Math.max(1,win.getComputedStyle(element.querySelector('.fishing-tackle-tray')).gridTemplateColumns.split(' ').length);let next=index;if(event.key==='ArrowRight')next=(index+1)%entries.length;else if(event.key==='ArrowLeft')next=(index-1+entries.length)%entries.length;else if(event.key==='ArrowDown')next=(index+columns)%entries.length;else if(event.key==='ArrowUp')next=(index-columns+entries.length)%entries.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=entries.length-1;else return;event.preventDefault();select(entries[next].id,true);}
    element.addEventListener('click',click);element.addEventListener('keydown',keydown);
    const api={update(next){if(destroyed||!next)return;snapshot={...snapshot,...next};render();},getSelectedId(){return selectedId;},selectBait(id){if(destroyed||!(catalog().baits||[]).some(b=>b.id===id))return false;select(id,false);return true;},destroy(){if(destroyed)return;destroyed=true;element.removeEventListener('click',click);element.removeEventListener('keydown',keydown);element.remove();}};
    if(options.snapshot)api.update(options.snapshot);
    return api;
  }
  return Object.freeze({create});
});
