(function(root){
  'use strict';
  const F=root.TracerFishingModel,A=root.TracerFishingArt;
  const escape=A.escape;
  function create(host,options={}){
    const doc=host.ownerDocument,section=options.section||'ponds';
    let snapshot=null,signature='',selectedPond='',filter='all',selectedPool='basic',collectionPool='all',pondPlayer=null,tackleBox=null,tackleSelection='',destroyed=false,feeding=null,editing=false,selectedDecoration='',aquariumPlayer=null,showcaseEditing=false,showcaseDraft=null;
    let skinPreviewId=null,skinPreviewPlayer=null,skinPreviewKey='';
    let pondPlayerId='',pondVisualKey='',journalRarity='all',journalHabitat='all',journalDiscovery='all';
    const page=doc.createElement('div');page.className='fishing-page fishing-page-'+section;host.append(page);
    const tr=(zh,en)=>snapshot?.language==='en'?en:zh;
    const name=item=>Array.isArray(item?.name)?item.name[snapshot?.language==='en'?1:0]:item?.name||'';
    const effectNote=rod=>rod.effectDescription?'<p class="fishing-rod-effect-note">'+escape(name({name:rod.effectDescription}))+'</p>':'';
    const rodPool=rod=>F.catalog.rodPools.find(pool=>pool.hiddenRodId===rod.id||pool.rodIds.includes(rod.id));
    const rarity=id=>({common:tr('寻常','Common'),rare:tr('珍稀','Rare'),epic:tr('史诗','Epic'),legendary:tr('传说','Legendary')})[id]||id;
    const button=(action,label,value='',disabled=false,extra='')=>'<button type="button" class="fishing-button '+extra+'" data-fishing-action="'+action+'" data-value="'+escape(value)+'" '+(disabled?'disabled':'')+'>'+escape(label)+'</button>';
    const harvestButton=fry=>fry.growth===100?button('harvest-fish',tr('收获售卖 · '+F.harvestValue(fry,snapshot.state)+' 金币','Harvest · '+F.harvestValue(fry,snapshot.state)+' coins'),fry.id,snapshot.busy,'primary fishing-harvest'):'';
    const growthStageName=stage=>({fry:tr('鱼苗','Fingerling'),juvenile:tr('成长中','Growing'),adult:tr('已成年','Adult')})[stage]||'';
    const growthText=(fish,fry,compact=false)=>{
      const appearance=F.growthAppearance(fish,fry.growth),percent=Math.round(appearance.progress*100);
      let html='<span class="fishing-growth-status"><span class="fishing-growth-stage" data-growth-stage="'+appearance.stage+'">'+growthStageName(appearance.stage)+'</span><span>'+tr('成长 ','Growth ')+percent+'%</span></span>';
      if(!compact)html+='<span class="fishing-growth" role="progressbar" aria-label="'+escape(name(fish)+tr('成长',' growth'))+'" aria-valuenow="'+percent+'" aria-valuemin="0" aria-valuemax="100"><i style="width:'+percent+'%"></i></span>';
      if(appearance.mature){
        html+='<span class="fishing-growth-unlock"><strong>'+escape(name({name:appearance.formName}))+'</strong>'+(appearance.actionName?' · '+escape(name({name:appearance.actionName})): '')+'</span>';
        if(!compact)html+='<span class="fishing-growth-description">'+escape(name({name:appearance.description}))+'</span>';
      }else if(!compact)html+='<span class="fishing-growth-hint">'+tr('成长至 100%：成年形态 · 新动作 · 售价 +50%','At 100%: larger size · adult form · new move · harvest price +50%')+'</span>';
      if(appearance.mature&&!compact)html+='<span class="fishing-growth-hint">'+tr('已成熟，可收获售卖 · 基础售价 +50%','Ready to harvest · base price +50%')+'</span>';
      return html;
    };
    const fishCard=(fish,copy,actions='',resident=null)=>{
      const appearance=resident?F.growthAppearance(fish,resident.growth):null;
      return '<article class="fishing-fish-card" data-rarity="'+(fish.rarity||'common')+'"'+(resident?' data-fry-id="'+escape(resident.id)+'" data-growth-stage="'+appearance.stage+'" style="--fish-growth-scale:'+(+appearance.scale.toFixed(3))+'"':'')+'><div class="fishing-fish-art">'+(fish.kind==='junk'||fish.kind==='mystery'?root.TracerFishingRewards.markup(fish):resident?A.fishMarkup({...fish,growth:resident.growth},{scaleGrowth:false}):A.fishMarkup(fish))+'</div><div><span class="fishing-rarity">'+(fish.kind==='junk'?tr('水中杂物','Found object'):fish.kind==='mystery'?tr('神秘收获','Mystery catch'):rarity(fish.rarity))+'</span><h3>'+escape(name(fish))+'</h3><p>'+copy+'</p>'+actions+'</div></article>';
    };

    function expeditionPanel(){
      const e=snapshot.expedition||F.expedition({fishing:snapshot.state}),p=snapshot.progression||F.progression({fishing:snapshot.state}),s=e.selection;
      return '<section class="fishing-expedition" data-expedition><div class="fishing-expedition-head"><div><span class="fishing-eyebrow">FISHING GROUNDS</span><h2>'+tr('渔场选择','Fishing grounds')+'</h2><p>'+tr('用金币逐级解锁六境，越深入，鱼获越珍贵。解锁后永久开放。','Unlock six waters in order with coins. Deeper waters yield more valuable catches; access is permanent.')+'</p></div><span class="fishing-mastery">Lv. '+p.mastery.level+'<small>'+p.mastery.xp+' XP'+(p.mastery.nextLevelXp?' / '+p.mastery.nextLevelXp:' MAX')+'</small></span></div><div class="fishing-spots">'+(e.grounds||F.groundProgress(snapshot.state)).map((x,i)=>{
        const active=x.id===s.spotId,affordable=snapshot.economy.balance>=x.unlockPrice,locked=!x.unlocked;
        const label=active?tr('正在垂钓','FISHING HERE'):x.unlocked?tr('进入鱼塘','ENTER GROUND'):x.available?tr('解锁 · '+x.unlockPrice.toLocaleString()+' 金币','UNLOCK · '+x.unlockPrice.toLocaleString()+' COINS'):tr(x.unlockPrice.toLocaleString()+' 金币 · 先解锁上一鱼塘',x.unlockPrice.toLocaleString()+' COINS · UNLOCK PREVIOUS');
        return '<button type="button" data-fishing-action="'+(locked?'unlock-ground':'set-spot')+'" data-value="'+x.id+'" aria-pressed="'+active+'" '+(snapshot.busy||snapshot.loadoutLocked||locked&&(!x.available||!affordable)?'disabled':'')+' data-water="'+x.id+'" data-locked="'+locked+'"><span class="fishing-ground-art" aria-hidden="true"></span><span class="fishing-ground-top"><span>0'+(i+1)+' / '+tr('水域','WATERS')+'</span><span>'+tr('鱼价 ×','VALUE ×')+x.valueMultiplier+'</span></span><span class="fishing-ground-copy"><strong>'+escape(name(x))+'</strong><small>'+escape(name({name:x.description}))+'</small></span><span class="fishing-ground-action">'+label+'</span>'+(locked&&x.available&&!affordable?'<small class="fishing-ground-shortfall">'+tr('还差 '+(x.unlockPrice-snapshot.economy.balance).toLocaleString()+' 金币',(x.unlockPrice-snapshot.economy.balance).toLocaleString()+' more coins needed')+'</small>':'')+'</button>';
      }).join('')+'</div><div class="fishing-expedition-options">'+(root.TracerFishingWeather?.markup(snapshot.weather,snapshot.language,escape)||'<span>'+tr('天气暂不可用','Weather unavailable')+'</span>')+'<div class="fishing-forecast"><strong>'+tr('上鱼率 ','Fish chance ')+Math.round(e.fishChance*100)+'%</strong><small>'+tr('微雨、清晨与黄昏更活跃；夜间偏好深潭和月池。','Rain, dawn and dusk improve activity; night favors deep and moon waters.')+'</small></div></div><p class="fishing-depth-guide">'+tr('蓄力 <38% 近岸 · 38–75% 中水 · ≥76% 深水；对应水层的鱼更容易上钩。','Power <38%: shallows · 38–75%: midwater · ≥76%: deep. Matching depth favors its fish.')+'</p><details class="fishing-forecast-fish"><summary>'+escape(name(e.spot))+' · '+e.fish.length+tr(' 种鱼 · 查看鱼情',' species · Fish forecast')+'</summary><div>'+e.fish.map(f=>'<span data-favored="'+e.favoredFishIds.includes(f.id)+'">'+A.fishMarkup(f)+'<b>'+escape(name(f))+'</b><small>'+ tr('售价 ','Value ')+(f.groundPrice??F.groundValue(f,e.spot.id))+tr(' 金币 · ',' coins · ')+(e.favoredFishIds.includes(f.id)?tr('鱼饵偏好 ×3','Bait ×3'):rarity(f.rarity))+'</small></span>').join('')+'</div></details><details class="fishing-achievements"><summary>'+tr('钓鱼成就','Fishing achievements')+' · '+p.discovered+'/'+p.total+tr(' 种已发现',' discovered')+'</summary><div>'+p.achievements.map(a=>'<span data-complete="'+a.complete+'"><b>'+(a.complete?'✓ ':'')+escape(name(a))+'</b><small>'+a.current+' / '+a.target+'</small>'+(a.description?'<small>'+escape(name({name:a.description}))+'</small>':'')+'</span>').join('')+'</div></details></section>';
    }

    function heading(title,subtitle){return '<header class="fishing-heading"><div><span class="fishing-eyebrow">TRACER / FISHING</span><h1>'+title+'</h1><p>'+subtitle+'</p></div><div class="fishing-heading-actions"><span class="fishing-wallet">◈ '+snapshot.economy.balance.toLocaleString()+'</span>'+'</div></header>';}
    function notice(){return '<div class="fishing-notice" role="status" '+(!snapshot.error&&!snapshot.notice?'hidden':'')+'>'+escape(snapshot.error||snapshot.notice||'')+(snapshot.error?button('retry-save',tr('重试保存','Retry save')):'')+'</div>';}
    function rods(){
      const s=snapshot.state,active=F.catalog.rods.find(r=>r.id===s.equippedRodId);
      let out=heading(tr('鱼竿收藏','Rod collection'),tr('查看已收集鱼竿、装备属性和专属效果。','View collected rods, handling and special effects.'))+notice();
      out+='<section class="fishing-rod-feature"><div class="fishing-feature-art">'+A.rodMarkup(active)+'</div><div><span class="fishing-eyebrow">'+tr('当前装备 / READY TO CAST','EQUIPPED / READY TO CAST')+'</span><h2>'+escape(name(active))+'</h2>'+effectNote(active)+'<p>'+tr('所有鱼竿都能钓到稀有鱼。更好的控竿区间，让收线更从容。','Every rod can catch rare fish. A larger control zone makes reeling more forgiving.')+'</p><div class="fishing-feature-stats"><span>'+tr('收集进度','Collection')+' <b>'+s.rods.length+' / '+F.catalog.rods.length+'</b></span><span>'+tr('控竿区间','Control zone')+' <b>'+Math.round(active.barSize*100)+'%</b></span></div>'+button('open-shop',tr('探索鱼竿盲盒 →','Explore rod boxes →'))+'</div></section>';
      out+='<nav class="fishing-filters" aria-label="'+tr('鱼竿系列','Rod collections')+'">'+button('select-rod-pool',tr('全部系列','All collections'),'all',false,collectionPool==='all'?'selected':'')+F.catalog.rodPools.map(pool=>button('select-rod-pool',name(pool),pool.id,false,collectionPool===pool.id?'selected':'')).join('')+'</nav>';
      out+='<nav class="fishing-filters" aria-label="'+tr('鱼竿筛选','Rod filters')+'">'+[['all',tr('全部鱼竿','All rods')],['owned',tr('已收藏','Collected')],['real',tr('现实匠作','Crafted')],['fantasy',tr('奇幻星光','Fantasy')],['xianxia',tr('仙侠灵韵','Celestial')]].map(([id,label])=>button('filter',label,id,false,filter===id?'selected':'')).join('')+'</nav><div class="fishing-rod-grid">';
      for(const rod of F.sortedRods(F.catalog.rods).filter(r=>(collectionPool==='all'||rodPool(r)?.id===collectionPool)&&(filter==='all'||filter==='owned'&&s.rods.includes(r.id)||r.family===filter))){
        const owned=s.rods.includes(rod.id),equipped=rod.id===s.equippedRodId,pool=rodPool(rod);
        if(rod.hidden&&!owned){out+='<article class="fishing-rod-card fishing-secret-card" data-hidden-reward><span class="fishing-rarity">'+escape(name(pool))+' · '+tr('隐藏款','Secret')+'</span><div class="fishing-rod-art fishing-secret-art" aria-hidden="true">?</div><h3>'+tr('尚未揭晓','Yet to be discovered')+'</h3><p>'+tr('0.5% · 开出后揭晓外观','0.5% · Appearance revealed on discovery')+'</p>'+button('open-pool',tr('前往所属奖池','Explore this collection'),pool.id)+'</article>';continue;}
        out+='<article class="fishing-rod-card" data-rarity="'+rod.rarity+'" data-owned="'+owned+'"><span class="fishing-rarity">'+rarity(rod.rarity)+(pool?' · '+escape(name(pool)):'')+'</span><div class="fishing-rod-art">'+A.rodMarkup(rod)+'</div><h3>'+escape(name(rod))+'</h3>'+effectNote(rod)+'<p>'+tr('控竿区间 ','Control zone ')+Math.round(rod.barSize*100)+'% · '+tr('手感 ','Control ')+rod.control.toFixed(2)+'</p>'+button(owned?'equip-rod':'open-pool',equipped?tr('已装备','Equipped'):owned?tr('装备鱼竿','Equip rod'):tr('盲盒中发现','Discover in boxes'),owned?rod.id:pool.id,equipped||snapshot.busy,owned?'':'quiet')+'</article>';
      }
      return out+'</div>';
    }
    const baitBox=shop=>'<div class="fishing-tackle-mount" data-tackle-box-mode="'+(shop?'shop':'equip')+'"></div>';
    function tackle(){
      const pool=F.catalog.rodPools.find(p=>p.id===selectedPool)||F.catalog.rodPools[0],pity=F.pity(snapshot.state,pool.id),price=F.boxPrice(pool.id);
      return heading(tr('钓具商店','Tackle shop'),tr('每个奖池分别累计保底；同品质优先获得本池未收藏的鱼竿，集齐该品质后才会重复。','Guarantees are tracked separately for each collection. Uncollected rods come first within the rolled rarity.'))+notice()+(F.catalog.rodPools.length>1?'<nav class="fishing-filters" aria-label="'+tr('选择鱼竿奖池','Choose a rod collection')+'">'+F.catalog.rodPools.map(p=>button('select-pool',name(p),p.id,false,p.id===pool.id?'selected':'')).join('')+'</nav>':'')+
        '<section class="fishing-box-feature" data-rod-pool="'+pool.id+'"><div><span class="fishing-eyebrow">'+escape(name(pool))+' · VOL. '+String(pool.volume||1).padStart(2,'0')+'</span><h2>'+escape(name(pool))+'</h2><p>'+escape(name({name:pool.description}))+'</p><p>'+tr((pool.rodIds.length+1)+' 款 · 每次开启获得 1 款 · 隐藏款包含在内。',(pool.rodIds.length+1)+' rods · One rod per box · Includes one secret.')+'</p>'+'<div class="fishing-box-actions">'+button('buy-box',tr('单抽 · '+price+' 金币','Open 1 · '+price+' coins'),pool.id,snapshot.busy||snapshot.economy.balance<price)+button('buy-ten-boxes',tr('十连抽 · '+(price*10)+' 金币','Open 10 · '+(price*10)+' coins'),pool.id,snapshot.busy||snapshot.economy.balance<price*10,'primary')+'</div>'+'<small>'+tr('重复鱼竿返还 20 / 40 / 75 / 150 金币','Duplicates return 20 / 40 / 75 / 150 coins')+'</small></div><div class="fishing-box-display" aria-hidden="true">'+['common','epic','legendary'].map(tier=>F.catalog.rods.find(r=>pool.rodIds.includes(r.id)&&r.rarity===tier)).filter(Boolean).map(r=>A.rodMarkup(r)).join('')+'<span>ROD<br>COLLECTION</span></div></section>'+
        '<div class="fishing-odds">'+Object.entries(pool.odds).sort(([a],[b])=>Number(a==='hidden')-Number(b==='hidden')).map(([id,p])=>'<div data-rarity="'+id+'"><span>'+(id==='hidden'?tr('隐藏款','Secret'):rarity(id))+'</span><strong>'+Number((p*100).toFixed(1))+'%</strong></div>').join('')+'</div><p class="fishing-pity">'+(pool.id==='valorant'?tr('每盒必出传说。','Every draw is legendary. '):tr('最多再开 '+pity.epicRemaining+' 盒必出史诗或以上，'+pity.legendaryRemaining+' 盒必出传说。','Epic or better within '+pity.epicRemaining+' boxes; legendary within '+pity.legendaryRemaining+'. '))+'</p><p class="fishing-pity fishing-hidden-pity" data-active="'+pity.hiddenActive+'">'+(pity.hiddenActive?tr('隐藏保底已开启 · '+pity.hidden+'/100 · 最多再抽 '+pity.hiddenRemaining+' 次必出隐藏款。出隐藏后重新计数。','Secret guarantee active · '+pity.hidden+'/100 · Secret within '+pity.hiddenRemaining+' draws. Resets on a secret.'):tr('常规款收集 '+pity.collected+'/'+pity.collectionTotal+' · 集齐本礼包所有常规鱼竿后，从下一抽开始计数，100 抽内必出隐藏款。','Regular collection '+pity.collected+'/'+pity.collectionTotal+' · Complete this collection to start the 100-draw secret guarantee on the next draw.'))+'<small>'+tr('自然出货概率 0.5%；各礼包独立计数，单抽与十连共享进度。','Natural secret chance 0.5%; separate counters per collection, shared by single and ten draws.')+'</small>'+'</p><div class="fishing-section-heading"><h2>'+tr('鱼饵商店','Bait shop')+'</h2></div>'+baitBox(true)+pondSkinShop();
    }
    function pondSkinShop(){
      const state=snapshot.state,equipped=state.pondAppearance?.skinId||null,owned=new Set(state.transactions.filter(t=>t.kind==='pond_skin').map(t=>t.itemId));
      let out='<section class="fishing-skin-shop" data-pond-skin-shop><div class="fishing-section-heading"><div><span class="fishing-eyebrow">POND & TACKLE CHEST</span><h2>'+tr('鱼塘主题皮肤','Pond themes')+'</h2><p>'+tr('一套包含鱼塘与配套钓鱼箱。永久解锁，自由换装；鱼种、价格与钓场规则由原钓场决定。','Each permanent theme includes a pond and matching tackle chest. Species, prices and fishing rules still follow your selected ground.')+'</p></div>'+button('equip-pond-skin',equipped?tr('恢复原始外观','Restore original'):tr('原始外观使用中','Original equipped'),'',snapshot.busy||!equipped,'quiet')+'</div>';
      const preview=F.catalog.pondSkins.find(s=>s.id===skinPreviewId);
      if(preview)out+='<div class="fishing-skin-preview" data-skin-preview><div class="fishing-skin-preview-pond" data-skin-pond></div><div class="fishing-skin-preview-copy"><span class="fishing-eyebrow">'+tr('外观预览','APPEARANCE PREVIEW')+'</span><h3>'+escape(name(preview))+'</h3><img src="'+preview.box+'" alt="'+escape(name(preview))+tr('配套钓鱼箱',' matching tackle chest')+'" width="160" height="140"><p>'+tr('拖动旋转 · 滚轮缩放','Drag to rotate · Scroll to zoom')+'</p><small>'+tr('预览不会更换当前装备','Preview keeps your current equipment')+'</small>'+skinAction(preview,owned,equipped)+button('close-skin-preview',tr('收起预览','Close preview'),' ',false,'quiet')+'</div></div>';
      out+='<div class="fishing-skin-grid">';
      for(const skin of F.catalog.pondSkins)out+='<article class="fishing-skin-card" data-skin="'+skin.id+'" data-equipped="'+(equipped===skin.id)+'" style="--pond-skin-base:'+skin.base+';--pond-skin-accent:'+skin.accent+'"><button type="button" class="fishing-skin-art" data-fishing-action="preview-pond-skin" data-value="'+skin.id+'" aria-label="'+tr('预览','Preview ')+escape(name(skin))+'"><img class="fishing-skin-bank" src="'+skin.preview+'" alt="" loading="lazy" width="280" height="280"><img class="fishing-skin-chest" src="'+skin.box+'" alt="" loading="lazy" width="120" height="120"><span>'+tr('查看立体预览','View in 3D')+'</span></button><div class="fishing-skin-card-copy"><h3>'+escape(name(skin))+'</h3><p>'+tr('鱼塘 + 钓鱼箱','Pond + tackle chest')+'</p>'+skinAction(skin,owned,equipped)+'</div></article>';
      return out+'</div></section>';
    }
    function skinAction(skin,owned,equipped){const has=owned.has(skin.id),active=equipped===skin.id;return button(has?'equip-pond-skin':'buy-pond-skin',active?tr('已装备','Equipped'):has?tr('装备整套','Equip set'):tr('购买 · ','Buy · ')+skin.price+tr(' 金币',' coins'),skin.id,snapshot.busy||active||!has&&snapshot.economy.balance<skin.price,has?'':'primary');}
    function decorationEditor(){
      const pond=snapshot.state.ponds.find(p=>p.id===selectedPond),items=pond?.decorations||[],selected=items.find(d=>d.id===selectedDecoration),catalog=F.catalog.decorations||[];
      const sprite=kind=>A.decorationMarkup(kind);
      let html='<div class="fishing-decor-heading"><div><h3>'+tr('鱼塘装饰','Pond decorations')+'</h3><p>'+tr('拖动场景中的装饰摆放，留出水面看鱼儿。装饰免费。','Drag decorations in the scene. Leave room to watch your fish. All decorations are free.')+'</p></div><small>'+items.length+' / 16</small></div><div class="fishing-decor-catalog">';
      for(const d of catalog)html+='<button type="button" data-fishing-action="add-decoration" data-value="'+d.id+'" '+(snapshot.busy||items.length>=16?'disabled':'')+' title="'+escape(tr('添加 ','Add ')+name(d))+'">'+sprite(d.id)+'<span>'+escape(name(d))+'</span><i>＋</i></button>';
      html+='</div><div class="fishing-decor-selection"><label>'+tr('选中装饰','Selected decoration')+'<select data-decoration-select><option value="">'+tr('点击场景中的装饰','Choose a decoration in the scene')+'</option>'+items.map((d,i)=>'<option value="'+d.id+'" '+(d.id===selectedDecoration?'selected':'')+'>'+escape(name(catalog.find(c=>c.id===d.kind)))+' '+(i+1)+'</option>').join('')+'</select></label><div class="fishing-decor-tools">';
      for(const [id,label]of [['left','←'],['up','↑'],['down','↓'],['right','→'],['rotate',tr('转向','Turn')],['smaller','−'],['larger','＋'],['remove',tr('收起','Remove')]])html+=button('decor-'+id,label,'',!selected||snapshot.busy,'quiet');
      return html+'</div></div>'+button('reset-decorations',tr('恢复推荐布局','Restore recommended layout'),'',snapshot.busy,'quiet');
    }
    function renderEditor(){const editor=page.querySelector('[data-decoration-editor]');if(!editor)return;editor.hidden=!editing;editor.innerHTML=editing?decorationEditor():'';const toggle=page.querySelector('[data-fishing-action="edit-decorations"]');if(toggle){toggle.textContent=editing?tr('完成布置','Finish decorating'):tr('布置鱼塘','Decorate pond');toggle.setAttribute('aria-pressed',String(editing));}pondPlayer?.update?.({editing,selectedDecorationId:selectedDecoration});}
    function pondFingerlings(){return snapshot.state.fry.filter(f=>f.releasedAt===null&&f.pondId===null&&['rare','epic'].includes(F.catalog.fish.find(x=>x.id===f.fishId)?.rarity));}
    function pondNursery(pond){
      const available=pondFingerlings(),s=snapshot.state,full=s.fry.filter(f=>f.pondId===pond.id&&f.releasedAt===null).length>=F.MAX_FISH;
      let out='<section class="fishing-pond-nursery" data-pond-nursery><header><h3>'+tr('待放养鱼苗','Pond nursery')+'</h3><span>'+available.length+'</span></header><p>'+tr('珍稀和史诗鱼苗可放入鱼塘，每塘最多五条。','Rare and epic fingerlings can live in a pond, up to five per pond.')+'</p>';
      if(full)out+='<p class="fishing-pond-nursery-hint">'+tr('鱼塘已满，可收获成熟的鱼，或先取回一条到育养箱。','This pond is full. Harvest an adult or return a resident to the nursery.')+'</p>';
      out+='<div class="fishing-pond-fry-list">';
      for(const fry of available.slice().reverse()){const fish=F.catalog.fish.find(f=>f.id===fry.fishId),appearance=F.growthAppearance(fish,fry.growth);out+='<article class="fishing-pond-fry" data-fry-id="'+fry.id+'" data-rarity="'+fish.rarity+'" data-growth-stage="'+appearance.stage+'" style="--fish-growth-scale:'+(+appearance.scale.toFixed(3))+'"><div class="fishing-pond-fry-art">'+A.fishMarkup({...fish,growth:fry.growth},{scaleGrowth:false})+'</div><div><span class="fishing-rarity">'+rarity(fish.rarity)+'</span><h4>'+escape(name(fish))+'</h4>'+growthText(fish,fry,true)+'</div>'+button('place-pond-fish',full?tr('鱼塘已满','Pond full'):tr('放入这座鱼塘','Place in this pond'),fry.id,snapshot.busy||full,'primary')+harvestButton(fry)+'</article>';}
      if(!available.length)out+='<p class="fishing-pond-nursery-empty">'+tr('钓到珍稀或史诗鱼后，额外获得的鱼苗会在这里。已钓到的鱼苗也会保留。','Rare and epic catches give you fingerlings that wait here until placed.')+'</p>';
      return out+'</div><p class="fishing-pond-nursery-footer">'+tr('传奇鱼请入住水族箱。','Legendary fish live in the aquarium.')+'</p>'+button('open-aquarium',tr('前往传奇水族箱 →','Legendary aquarium →'),' ',snapshot.busy,'quiet')+'</section>';
    }
    function ponds(){
      const s=snapshot.state,active=s.ponds.find(p=>!p.archivedAt)||s.ponds[0];
      if(!s.ponds.some(p=>p.id===selectedPond))selectedPond=active.id;
      const pond=s.ponds.find(p=>p.id===selectedPond),style=F.catalog.pondStyles.find(p=>p.id===pond.styleId),residents=s.fry.filter(f=>f.pondId===pond.id&&!f.releasedAt);
      let out=heading(tr('我的鱼塘','My ponds'),tr('放养珍稀和史诗鱼苗，投喂并查看成长。传奇鱼在水族箱中管理。','Raise and feed rare and epic fingerlings, and track their growth. Manage legendary fish in the aquarium.'))+notice();
      out+='<div class="fishing-pond-layout"><aside class="fishing-pond-list"><span class="fishing-eyebrow">'+tr('我的鱼塘','MY PONDS')+'</span>'+s.ponds.map((p,i)=>{const st=F.catalog.pondStyles.find(x=>x.id===p.styleId),n=s.fry.filter(f=>f.pondId===p.id&&!f.releasedAt).length;return '<button type="button" data-fishing-action="select-pond" data-value="'+p.id+'" class="fishing-pond-tab '+(p.id===pond.id?'selected':'')+'"><i style="--pond-color:'+st.color+'"></i><span><strong>'+escape(name(st))+' <small>'+String(i+1).padStart(2,'0')+'</small></strong><small>'+tr('养殖鱼塘','Fish pond')+' · '+n+'/5</small></span></button>';}).join('')+'<p>'+tr('成熟后可收获售卖，价格比同种钓获鱼高 50%。传说鱼在水族箱养殖。','Harvest adults for 50% above the same species’ base catch price. Raise legendary fish in the aquarium.')+'</p>'+pondNursery(pond)+'</aside><section class="fishing-pond-detail"><div class="fishing-pond-title"><div><span class="fishing-eyebrow">'+'FISH POND'+'</span><h2>'+escape(name(style))+'</h2></div><strong>'+residents.length+' <small>/ 5</small></strong></div><div class="fishing-pond-canvas" id="fishing-pond-canvas"></div><div class="fishing-pond-toolbar">'+(root.TracerFishing?button('pin-pond',tr('这座摆到桌面 ↗','Show this pond on desktop ↗')):'')+button('feed-pond',tr('投喂 · 5 金币','Feed · 5 coins'),pond.id,snapshot.busy||!residents.some(f=>f.fedAt===null||Date.now()-f.fedAt>=60000)||snapshot.economy.balance<5,'primary')+'<small>'+tr('拖动旋转 · 滚轮缩放','Drag to rotate · Scroll to zoom')+'</small></div>';
      out+='<div class="fishing-pond-styles"><span>'+tr('免费换景','FREE SCENERY')+'</span>'+F.catalog.pondStyles.map(p=>button('pond-style',name(p),p.id,snapshot.busy||p.id===pond.styleId,p.id===pond.styleId?'selected':'')).join('')+'</div>';
      out+='<div class="fishing-decor-bar">'+button('edit-decorations',editing?tr('完成布置','Finish decorating'):tr('布置鱼塘','Decorate pond'),'',snapshot.busy)+'<span>'+tr('树影、花丛与岸边小物，摆成你喜欢的样子。','Arrange trees, flowers and little waterside treasures.')+'</span></div><section class="fishing-decor-editor" data-decoration-editor '+(editing?'':'hidden')+'>'+(editing?decorationEditor():'')+'</section><div class="fishing-residents">';
      for(const fry of residents){const f=F.catalog.fish.find(x=>x.id===fry.fishId);out+=fishCard(f,growthText(f,fry),harvestButton(fry)+button('take-pond-fish',tr('取回育养箱','Return to nursery'),fry.id,snapshot.busy)+button('release-request',tr('放生','Release fish'),fry.id,snapshot.busy,'quiet'),fry);}
      if(!residents.length)out+='<div class="fishing-empty">⌁<h3>'+tr('暂未放养鱼','No fish in this pond')+'</h3><p>'+tr('从「待放养鱼苗」选择一条珍稀或史诗鱼，放进这座鱼塘。','Choose a rare or epic fingerling from the pond nursery to move in.')+'</p>'+button('manage-pond-nursery',tr('查看待放养鱼苗','View pond nursery'))+'</div>';
      out+='</div></section></div>';
      return out+pondSkinShop();
    }
    function showcaseValue(){
      const value=snapshot.showcase;if(!showcaseEditing||!showcaseDraft||!value)return value;
      return {...value,selection:{...value.selection,...showcaseDraft},fish:value.fish};
    }
    function aquariumDecorationEditor(){
      const selected=showcaseDraft.decorationIds||root.TracerFishingAquariumArt.defaultDecorations;
      return '<div class="fishing-aquarium-decor-editor" data-aquarium-decor-editor><h3>'+tr('水族箱装饰','Aquarium decorations')+'</h3><p>'+tr('装饰免费使用，最多放三件，按选择顺序从左向右摆放。再次点击即可取走。','All decorations are free. Choose up to three, placed from left to right in selection order. Click again to remove.')+'</p><div class="fishing-aquarium-choices">'+F.catalog.aquariumDecorations.map(d=>'<button type="button" class="fishing-aquarium-choice" data-fishing-action="showcase-decoration" data-value="'+d.id+'" aria-pressed="'+selected.includes(d.id)+'" '+(snapshot.busy||selected.length>=3&&!selected.includes(d.id)?'disabled':'')+'>'+root.TracerFishingAquariumArt.decorationMarkup(d.id)+'<span>'+escape(name(d))+'</span></button>').join('')+'</div><p class="fishing-aquarium-message">'+selected.length+' / 3 · '+tr('装饰会和鱼一起保存到桌面水族箱','Decorations sync with your fish to the desktop aquarium')+'</p></div>';
    }
    function showcaseEditor(){
      if(!showcaseEditing||!showcaseDraft)return '';
      return aquariumDecorationEditor()+'<div class="fishing-aquarium-actions">'+button('save-showcase',tr('保存布置','Save decorations'),'',snapshot.busy,'primary')+button('cancel-showcase',tr('取消','Cancel'),'',snapshot.busy,'quiet')+'</div>';
    }
    function renderShowcaseEditor(){const mount=page.querySelector('[data-showcase-editor]');if(mount){mount.hidden=!showcaseEditing;mount.innerHTML=showcaseEditor();}aquariumPlayer?.update(showcaseValue(),snapshot.language);}
    function aquarium(){
      const s=snapshot.state,bag=s.catches.filter(c=>c.soldAt===null&&!F.catchItem(c)?.openable),bagValue=bag.reduce((sum,c)=>sum+F.catchValue(s,c),0);
      const discovered=new Set(s.catches.filter(c=>F.catalog.fish.some(f=>f.id===c.fishId)).map(x=>x.fishId)),legends=F.catalog.fish.filter(f=>f.rarity==='legendary');
      let out=heading(tr('传奇水族箱','Legendary aquarium'),tr('管理传奇鱼、查看图鉴与钓鱼收获，可同步到桌面水族箱。','Manage legendary fish, your journal and catches. Sync your aquarium to the desktop.'))+notice();
      out+='<section class="fishing-aquarium-feature"><div data-aquarium-display></div><div><span class="fishing-eyebrow">LEGENDARY AQUARIUM</span><h2>'+tr('水族箱展示','Aquarium display')+'</h2><p>'+tr('最多展示三条传奇鱼，可从育养箱放入并随时取回。','Display up to three legendary fish. Move them in from the nursery and take them back at any time.')+'</p><div class="fishing-aquarium-picked">'+(snapshot.showcase?.fish||[]).map(f=>'<span>'+escape(name(f))+'</span>').join('')+'</div><div class="fishing-feature-stats"><span>'+tr('传奇发现','Legends discovered')+' <b>'+legends.filter(f=>discovered.has(f.id)).length+' / '+legends.length+'</b></span><span>'+tr('正在展示','On display')+' <b>'+(snapshot.showcase?.fish.length||0)+' / 3</b></span></div><div class="fishing-aquarium-actions">'+button('manage-aquarium',tr('放入传奇鱼','Add legendary fish'),'',snapshot.busy,'primary')+button('edit-aquarium-decor',tr('布置水族箱','Decorate aquarium'),'',snapshot.busy)+button('pin-aquarium',root.TracerFishingAquarium?tr('摆到桌面 ↗','Place on desktop ↗'):tr('预览桌面水族箱','Preview desktop aquarium'))+(root.TracerFishingAquarium?button('hide-aquarium',tr('从桌面隐藏','Hide from desktop')):'')+'</div><p class="fishing-aquarium-desktop-note">'+(root.TracerFishingAquarium?tr('透明桌面摆件，可拖动、收起，展示选择会同步更新。','A transparent desktop ornament. Move or hide it; your fish selection stays in sync.'):tr('桌面客户端可独立摆放水族箱；这里可以预览相同的展示。','Use the desktop app for a standalone aquarium; preview the same display here.'))+'</p></div></section><section class="fishing-aquarium-editor" data-showcase-editor '+(showcaseEditing?'':'hidden')+'>'+showcaseEditor()+'</section>';
      out+=aquariumResidents();
      out+=mysteryCollection();
      out+='<div class="fishing-section-heading"><h2>'+tr('我的钓具','My tackle')+'</h2></div>'+baitBox(false);
      out+='<div class="fishing-section-heading" data-catch-basket><h2>'+tr('我的鱼篓','Catch basket')+' <span>'+bag.length+'</span></h2>'+button('sell-all-fish',bag.length?tr('全部出售 · '+bag.length+' 件 · ','Sell all · '+bag.length+' catches · ')+'◈ '+bagValue:tr('暂无可出售的收获','No catches to sell'),'',snapshot.busy||!bag.length,'primary')+'<p>'+tr('普通收获直接出售，含传奇鱼时会提醒确认。神秘礼包保留；育养箱、水族箱住客和图鉴记录保留。','Sell regular catches instantly; sales including legendary fish ask for confirmation. Mystery bundles, nursery fish, aquarium residents and journal records stay.')+'</p></div><div class="fishing-catch-grid">';
      for(const caught of bag.slice(-60).reverse()){const f=F.catchItem(caught),variantNames={boots:tr('旧靴子','Old boot'),broken_watch:tr('破手表','Broken watch'),trash_bag:tr('垃圾袋','Rubbish bag')};out+=fishCard(f,f.kind==='junk'?escape(variantNames[f.variant]||'')+' · '+tr('固定价值 1 金币','Always worth 1 coin'):caught.length+' cm · '+(caught.blastPercent!==undefined?tr('爆能器收获 · 售价 '+caught.blastPercent+'%','Spike catch · value '+caught.blastPercent+'%'):caught.quality==='perfect'?tr('完美捕获','Perfect catch'):tr('水边收获','A waterside catch')),button('sell-fish',tr('出售 · ','Sell · ')+'◈ '+F.catchValue(s,caught)+(caught.blastPercent!==undefined?' · '+caught.blastPercent+'%':''),caught.id,snapshot.busy));}
      if(!bag.length)out+='<p class="fishing-soft-empty">'+tr('空空的鱼篓，等一个好故事。','An empty basket, waiting for a good story.')+'</p>';
      out+='</div><div class="fishing-section-heading"><h2>'+tr('水生图鉴','The aquatic journal')+'</h2><p>'+tr('查看栖息地、偏好鱼饵、捕获记录与投喂动作。','View habitats, preferred bait, catch records and feeding actions.')+'</p></div><div class="fishing-journal-grid">';
      out+='<nav class="fishing-filters fishing-journal-filters" aria-label="'+tr('图鉴栖息地','Journal habitat')+'">'+[['all',tr('全部','All')],['river',tr('溪河','River')],['sea',tr('海洋','Sea')],['ice',tr('冰湖','Ice')],['deep',tr('深潭','Deep')],['spirit',tr('灵池','Spirit')],['moon',tr('月池','Moon')]].map(([id,label])=>button('journal-filter',label,id,false,journalHabitat===id?'selected':'')).join('')+'</nav>';
      for(const f of F.catalog.fish.filter(f=>journalHabitat==='all'||f.habitat===journalHabitat)){const count=s.catches.filter(c=>c.fishId===f.id).length,profile=F.catalog.difficultyProfiles?.[f.rarity];out+='<article class="fishing-journal-card" data-discovered="'+!!count+'"><div>'+A.fishMarkup(f)+'</div><span class="fishing-rarity">'+rarity(f.rarity)+'</span><h3>'+escape(name(f))+'</h3>'+(f.description?'<p>'+escape(name({name:f.description}))+'</p>':'')+'<p>'+tr('捕获 ','Caught ')+count+tr(' 次',' times')+'</p>'+(profile?'<small class="fishing-difficulty-note"><strong>'+escape(name(f.technique||profile))+'</strong> · '+escape(name({name:profile.description}))+'</small>':'')+'<small>'+tr('可钓渔场：','Found in: ')+F.catalog.spots.filter(spot=>spot.habitats.includes(f.habitat)||spot.fishIds?.includes(f.id)).map(name).join(' · ')+'</small>'+(count?'<small>'+tr('最大记录 ','Personal best ')+Math.max(...s.catches.filter(c=>c.fishId===f.id).map(c=>c.length)).toFixed(1)+' cm</small>':'')+'<small>'+tr('偏好鱼饵：','Preferred bait: ')+(F.catalog.baits.filter(b=>b.fishIds.includes(f.id)).map(name).join(' · ')||tr('无特定偏好，通用蚯蚓可用','No special preference; earthworms work'))+'</small><small>'+escape(name({name:f.feedingHabit||f.feedingReaction?.description}))+'</small></article>';}
      return out+'</div>';
    }
    function motorCard(gift,s){
      const motor=snapshot.autoMotor||{installed:!!s.motorInstallation?.installed,running:false},locked=!!snapshot.busy;
      return '<article class="fishing-gift-card fishing-motor-card" data-gift="'+gift.id+'" data-equipped="'+motor.installed+'">'+root.TracerFishingRewards.giftMarkup(gift)+'<div class="fishing-gift-card-copy"><span class="fishing-gift-kind">'+tr('极稀有装备 · 0.001%','Ultra-rare equipment · 0.001%')+'</span><h3>'+escape(name(gift))+'</h3><p>'+escape(name({name:gift.description}))+'</p><p class="fishing-motor-achievement"><b>'+tr('气运之子','Child of Fortune')+'</b><span>'+tr('抽到概率0.001%的自动钓鱼马达','Obtain the automatic fishing motor with a 0.001% drop chance')+'</span></p>'+(motor.installed?button(motor.running?'pause-motor':'start-motor',motor.running?tr('自动钓鱼中 · 暂停','Fishing automatically · Pause'):tr('继续自动钓鱼','Resume automatic fishing'),'',locked&&!motor.running,'primary')+button('remove-motor',tr('卸下马达','Remove motor'),'',locked,'quiet'):button('install-motor',tr('安装并自动钓鱼','Install and start fishing'),'',locked,'primary'))+'</div></article>';
    }
    function mysteryCollection(){
      const s=snapshot.state,bundles=s.catches.filter(c=>c.fishId==='mystery_bundle'&&c.openedAt===null),gifts=s.giftUnlocks||[],appearance=s.giftAppearance||{};
      let out='<section class="fishing-mystery-shelf" data-mystery-bundles>'+root.TracerFishingRewards.markup({kind:'mystery'})+'<div><span class="fishing-eyebrow">'+tr('钓鱼奖励','FISHING REWARDS')+'</span><h2>'+tr('神秘大礼包','Mystery bundles')+' · '+bundles.length+'</h2></div>'+button('open-bundle',bundles.length?tr('开启一份礼包','Open a bundle'):tr('暂无礼包','No bundles'),bundles[0]?.id||'',snapshot.busy||!bundles.length,'primary')+'</section>';
      out+='<section data-gift-collection><div class="fishing-section-heading"><h2>'+tr('礼物收藏','Gift collection')+' <span>'+gifts.length+'</span></h2><p>'+tr('只展示已经获得的礼物。收起后恢复原来的头像框或背景。','Only discovered gifts appear here. Put them away to restore your previous frame or background.')+'</p></div>';
      if(!gifts.length)return out+'<p class="fishing-soft-empty">'+tr('暂无礼物。钓到神秘大礼包后可在这里开启。','No gifts yet. Open mystery bundles caught while fishing here.')+'</p></section>';
      out+='<div class="fishing-gift-grid">';
      for(const gift of gifts){if(gift.id==='auto_fishing_motor'){out+=motorCard(gift,s);continue;}const equipped=appearance[gift.slot+'Id']===gift.id;out+='<article class="fishing-gift-card" data-gift="'+gift.id+'" data-equipped="'+equipped+'">'+root.TracerFishingRewards.giftMarkup(gift)+'<div class="fishing-gift-card-copy"><span class="fishing-gift-kind">'+(gift.slot==='avatarFrame'?tr('限定头像框','Exclusive avatar frame'):tr('限定背景板','Exclusive background'))+'</span><h3>'+escape(name(gift))+'</h3><p>'+escape(name({name:gift.description}))+'</p>'+button(equipped?'remove-gift':'equip-gift',equipped?tr('使用中 · 收起','In use · Put away'):tr('使用礼物','Use gift'),equipped?gift.slot:gift.id,snapshot.busy,equipped?'quiet':'primary')+'</div></article>';}
      return out+'</div></section>';
    }
    function aquariumResidents(){
      const s=snapshot.state,ids=s.aquarium?.fryIds||[],residents=ids.map(id=>s.fry.find(f=>f.id===id)),available=s.fry.filter(f=>f.releasedAt===null&&!ids.includes(f.id)&&F.catalog.fish.find(x=>x.id===f.fishId)?.rarity==='legendary');
      let out='<section data-aquarium-residents><div class="fishing-section-heading"><h2>'+tr('水族箱住客','Aquarium residents')+' <span>'+residents.length+' / 3</span></h2>'+button('feed-aquarium',tr('投喂 · 5 金币','Feed · 5 coins'),'',snapshot.busy||!residents.some(f=>f.fedAt===null||Date.now()-f.fedAt>=60000)||snapshot.economy.balance<5,'primary')+'</div><p>'+tr('只接收传奇鱼，最多三条。取回会回到育养箱，成长和投喂记录都会保留。','A home for up to three legendary fish. Returning a fish to the nursery preserves its growth and feeding history.')+'</p><div class="fishing-residents">';
      for(const fry of residents){const f=F.catalog.fish.find(x=>x.id===fry.fishId);out+=fishCard(f,growthText(f,fry),harvestButton(fry)+button('take-aquarium-fish',tr('取回育养箱','Return to nursery'),fry.id,snapshot.busy,'quiet'),fry);}
      if(!residents.length)out+='<p class="fishing-soft-empty">'+tr('水族箱还没有住客，从下方选择一条传奇鱼入住吧。','Your aquarium is waiting. Choose a legendary fingerling below.')+'</p>';
      out+='</div><div class="fishing-section-heading"><h2>'+tr('传奇鱼育养箱','Legendary nursery')+'</h2><p>'+tr('成熟后可按基础售价的 150% 收获售卖，出售传说鱼前需要确认。','Harvest mature fish for 150% of the base price. Selling legendary fish requires confirmation.')+'</p></div><div class="fishing-nursery">';
      for(const fry of available){const f=F.catalog.fish.find(x=>x.id===fry.fishId);out+=fishCard(f,growthText(f,fry),harvestButton(fry)+button('place-aquarium-fish',fry.pondId?tr('从鱼塘移入水族箱','Move from pond to aquarium'):tr('放入水族箱','Place in aquarium'),fry.id,snapshot.busy||residents.length>=3),fry);}
      if(!available.length)out+='<p class="fishing-soft-empty">'+tr('钓获传奇鱼后，获得的鱼苗会在这里等你。','Legendary catches give you fingerlings that wait here.')+'</p>';
      const pondFry=pondFingerlings();
      return out+'</div><div class="fishing-pond-nursery-link"><p>'+tr('另有 '+pondFry.length+' 条珍稀 / 史诗鱼苗待放养，可前往「我的鱼塘」查看。',pondFry.length+' rare / epic fingerlings are waiting in My Ponds.')+'</p>'+button('open-ponds',tr('查看鱼塘鱼苗 →','View pond nursery →'))+'</div></section>';
    }
    function update(next){
      if(destroyed||!next?.state)return;snapshot={...next,busy:!!(next.busy||next.loadoutLocked)};
      const key=JSON.stringify([snapshot.language,snapshot.weather&&{...snapshot.weather,now:Math.floor(snapshot.weather.now/60000)},snapshot.expedition?.selection,snapshot.state,snapshot.economy.balance,snapshot.busy,snapshot.error,snapshot.notice,section,selectedPond,filter,selectedPool,collectionPool,snapshot.state.fry.map(f=>f.fedAt===null||Date.now()-f.fedAt>=60000)]);
      if(signature===key)return;signature=key;
      const focus=doc.activeElement?.closest('[data-fishing-action]'),focusId=focus&&[focus.dataset.fishingAction,focus.dataset.value];
      const tackleFocus=doc.activeElement?.closest('[data-tackle-focus]'),tackleFocusKey=tackleFocus&&page.contains(tackleFocus)?tackleFocus.dataset.tackleFocus:'';
      if(tackleBox){tackleSelection=tackleBox.getSelectedId();tackleBox.destroy();tackleBox=null;}
      // Saving and live cast controls can change without changing a 3D display.
      // Keep its canvas and GPU context alive while refreshing the surrounding
      // buttons; recreating it can block the cast clock on software rendering.
      const retainedAquarium=aquariumPlayer&&page.querySelector('[data-aquarium-display]');
      const retainedPond=pondPlayer&&page.querySelector('#fishing-pond-canvas');
      const retainedSkin=skinPreviewPlayer&&page.querySelector('[data-skin-pond]');
      if(!retainedPond){pondPlayer?.destroy();pondPlayer=null;pondPlayerId='';pondVisualKey='';}
      if(!retainedAquarium){aquariumPlayer?.destroy();aquariumPlayer=null;}
      page.innerHTML=section==='rods'?rods():section==='cabin'?aquarium():section==='tackle'?tackle():ponds();if(section==='ponds'||section==='cabin')page.querySelector('.fishing-heading')?.insertAdjacentHTML('afterend',expeditionPanel());
      let skinHost=page.querySelector('[data-skin-pond]');
      if(skinHost){
        if(retainedSkin){skinHost.replaceWith(retainedSkin);skinHost=retainedSkin;}
        const style=snapshot.expedition?.spot?.style||snapshot.desktopPond?.pond?.styleId||'meadow',settings={pond:{styleId:style,skinId:skinPreviewId},fish:[],interactive:true,zoom:1.08},key=JSON.stringify(settings.pond);
        if(!skinPreviewPlayer)skinPreviewPlayer=A.createPond(skinHost,settings);else if(key!==skinPreviewKey)skinPreviewPlayer.update(settings);
        skinPreviewKey=key;
      }else if(skinPreviewPlayer){skinPreviewPlayer.destroy();skinPreviewPlayer=null;skinPreviewKey='';}
      let showcaseHost=page.querySelector('[data-aquarium-display]');
      if(retainedAquarium&&showcaseHost){showcaseHost.replaceWith(retainedAquarium);showcaseHost=retainedAquarium;}
      else if(retainedAquarium){aquariumPlayer.destroy();aquariumPlayer=null;}
      if(showcaseHost&&root.TracerFishingAquariumArt){if(!aquariumPlayer)aquariumPlayer=root.TracerFishingAquariumArt.create(showcaseHost);aquariumPlayer.update(showcaseValue(),snapshot.language);}
      const tackleMount=page.querySelector('[data-tackle-box-mode]');
      if(tackleMount){tackleBox=root.TracerFishingTackle.create(tackleMount,{mode:tackleMount.dataset.tackleBoxMode,selectedId:tackleSelection,onAction:(action,id)=>options.onAction?.(action,id,{pondId:selectedPond})});tackleBox.update(snapshot);if(tackleFocusKey){const node=Array.from(tackleMount.querySelectorAll('[data-tackle-focus]')).find(node=>node.dataset.tackleFocus===tackleFocusKey);(node&&!node.disabled?node:tackleMount.querySelector('.fishing-tackle-slot[tabindex="0"]'))?.focus({preventScroll:true});}}
      if(section==='ponds'){
        const pond=snapshot.state.ponds.find(p=>p.id===selectedPond),style=F.catalog.pondStyles.find(p=>p.id===pond.styleId),fish=snapshot.state.fry.filter(f=>f.pondId===pond.id&&!f.releasedAt).map(f=>({...F.catalog.fish.find(x=>x.id===f.fishId),...f,speciesId:f.fishId}));
        const viewport=page.querySelector('#fishing-pond-canvas'),settings={pond:{...style,...pond,style:style.style,skinId:snapshot.state.pondAppearance?.skinId||null},fish,catalog:F.catalog,interactive:true,editing,selectedDecorationId:selectedDecoration,onDecorationSelect:id=>{selectedDecoration=id;renderEditor();},onDecorationMove:patch=>options.onAction?.('set-decoration',patch.id,{pondId:selectedPond,patch}),onSelect:fish=>{const id=typeof fish==='string'?fish:fish.id;const row=page.querySelector('[data-value="'+CSS.escape(id)+'"]');row?.closest('.fishing-fish-card')?.scrollIntoView({block:'nearest',behavior:'smooth'});},feeding};
        const visualKey=JSON.stringify([settings.pond,fish,editing,selectedDecoration,feeding]);
        if(retainedPond&&pondPlayerId===pond.id){viewport.replaceWith(retainedPond);if(visualKey!==pondVisualKey)pondPlayer.update(settings);}
        else{pondPlayer?.destroy();viewport.className='fishing-pond-viewport';pondPlayer=A.createPond(viewport,settings);pondPlayerId=pond.id;}
        pondVisualKey=visualKey;
      }
      if(focusId)page.querySelector('[data-fishing-action="'+focusId[0]+'"][data-value="'+CSS.escape(focusId[1])+'"]')?.focus({preventScroll:true});
    }
    function click(event){
      const node=event.target.closest('[data-fishing-action]');if(!node||node.disabled||!page.contains(node))return;const action=node.dataset.fishingAction,value=node.dataset.value;
      if(action==='preview-pond-skin'||action==='close-skin-preview'){skinPreviewId=action==='preview-pond-skin'&&F.catalog.pondSkins.some(s=>s.id===value)?value:null;signature='';update(snapshot);page.querySelector('[data-skin-preview]')?.scrollIntoView({block:'nearest',behavior:'smooth'});return;}
      if(action==='set-spot'){options.onAction?.('set-expedition','',{patch:{spotId:value}});return;}
      if(action==='journal-filter'){journalHabitat=value;signature='';update(snapshot);return;}
      if(action==='edit-aquarium-decor'){showcaseEditing=true;showcaseDraft={};if(snapshot.showcase?.selection?.decorationIds)showcaseDraft.decorationIds=snapshot.showcase.selection.decorationIds.slice();renderShowcaseEditor();page.querySelector('[data-aquarium-decor-editor]')?.scrollIntoView({block:'nearest',behavior:'smooth'});return;}
      if(action==='cancel-showcase'){showcaseEditing=false;showcaseDraft=null;renderShowcaseEditor();return;}
      if(action==='manage-aquarium'){page.querySelector('[data-aquarium-residents]')?.scrollIntoView({block:'start',behavior:'smooth'});return;}
      if(action==='manage-pond-nursery'){const nursery=page.querySelector('[data-pond-nursery]');nursery?.scrollIntoView({block:'nearest',behavior:'smooth'});nursery?.querySelector('button:not(:disabled)')?.focus({preventScroll:true});return;}
      if(action==='showcase-decoration'){if(!showcaseDraft)return;const ids=showcaseDraft.decorationIds||(showcaseDraft.decorationIds=root.TracerFishingAquariumArt.defaultDecorations.slice()),index=ids.indexOf(value);if(index>=0)ids.splice(index,1);else if(ids.length<3)ids.push(value);renderShowcaseEditor();page.querySelector('[data-fishing-action="showcase-decoration"][data-value="'+CSS.escape(value)+'"]')?.focus({preventScroll:true});return;}
      if(action==='save-showcase'){const patch=showcaseDraft;showcaseEditing=false;showcaseDraft=null;renderShowcaseEditor();options.onAction?.('set-showcase','',{patch});return;}
      if(action==='select-pond'){selectedPond=value;selectedDecoration='';signature='';update(snapshot);return;}
      if(action==='select-pool'){if(F.catalog.rodPools.some(p=>p.id===value)){selectedPool=value;signature='';update(snapshot);}return;}
      if(action==='select-rod-pool'){if(value==='all'||F.catalog.rodPools.some(p=>p.id===value)){collectionPool=value;signature='';update(snapshot);}return;}
      if(action==='filter'){filter=value;signature='';update(snapshot);return;}
      if(action==='edit-decorations'){editing=!editing;renderEditor();return;}
      if(action.startsWith('decor-')){const d=snapshot.state.ponds.find(p=>p.id===selectedPond)?.decorations.find(d=>d.id===selectedDecoration);if(!d)return;const kind=action.slice(6),patch=kind==='left'?{x:Math.max(-2.65,d.x-.2)}:kind==='right'?{x:Math.min(2.65,d.x+.2)}:kind==='up'?{z:Math.max(-2.65,d.z-.2)}:kind==='down'?{z:Math.min(2.65,d.z+.2)}:kind==='rotate'?{rotation:(d.rotation+1)%4}:kind==='smaller'?{scale:Math.max(.6,+(d.scale-.1).toFixed(2))}:kind==='larger'?{scale:Math.min(1.5,+(d.scale+.1).toFixed(2))}:{remove:true};options.onAction?.('set-decoration',d.id,{pondId:selectedPond,patch:{id:d.id,...patch}});return;}
      options.onAction?.(action,value,{pondId:selectedPond});
    }
    function selectDecoration(id){selectedDecoration=id||'';renderEditor();}
    function change(event){if(event.target.matches('[data-decoration-select]'))selectDecoration(event.target.value);}
    page.addEventListener('click',click);page.addEventListener('change',change);
    return {update,selectDecoration,selectPool(id){if(!F.catalog.rodPools.some(p=>p.id===id))return false;selectedPool=id;signature='';if(snapshot)update(snapshot);return true;},selectBait(id){tackleSelection=id;tackleBox?.selectBait(id);},getDecorationPosition:id=>pondPlayer?.getDecorationPosition?.(id),feed(value){if(destroyed)return;feeding=value;aquariumPlayer?.feed(value);pondPlayer?.feed?.(value);pondPlayer?.update?.({feeding:value});},selectPond(id){selectedPond=id;signature='';if(snapshot)update(snapshot);},destroy(){destroyed=true;skinPreviewPlayer?.destroy();pondPlayer?.destroy();aquariumPlayer?.destroy();tackleBox?.destroy();page.removeEventListener('click',click);page.removeEventListener('change',change);page.remove();}};
  }
  root.TracerFishingView={create};
})(typeof window!=='undefined'?window:globalThis);
