(function(root,factory){const common=typeof module==='object'&&module.exports,api=factory(common?require('./fishing-art'):root.TracerFishingArt,common?require('./fishing-motion'):root.TracerFishingMotion,common?require('./fishing-rod-renderer'):root.TracerFishingRodRenderer);if(common)module.exports=api;else root.TracerFishingGame=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Art,Motion,RodRenderer){
  'use strict';
  const clamp=value=>Math.max(0,Math.min(1,Number(value)||0));
  const COPY={zh:{idle:['静水等一竿','按住蓄力，松开抛竿'],charging:['寻找好落点','松开抛竿 · 蓄力越高抛得越远'],cast:['鱼线划过水面','浮漂落水后，耐心等待'],waiting:['等待鱼儿咬钩','留意浮漂，出现「咬钩」立即提竿'],bite:['咬钩了！','点击提竿，抓住这一瞬间'],reeling:['稳住鱼，慢慢收线','按住上升 · 松开下沉 · 让鱼留在绿色区间'],caught:['漂亮的一竿','鱼儿已经放入背包'],escaped:['鱼儿游走了','重新抛竿再试一次'],castButton:'按住抛竿',hookButton:'立即提竿',reelButton:'按住收线',waitButton:'等候咬钩',castProgress:'抛竿力度',catchProgress:'收获进度',tension:'鱼线张力',rod:'鱼竿',bait:'鱼饵',noBait:'未装鱼饵',spot:'钓点',fingerling:'获得鱼苗',perfect:'完美捕获',fish:'发现新鱼',capacity:'每个鱼塘最多养 5 条鱼',keys:'空格也可操作',rare:'稀有鱼苗可放入「我的鱼塘」培养',unknown:'湖畔',again:'再抛一竿'},en:{idle:['A quiet moment by the water','Hold to charge, release to cast'],charging:['Find your casting distance','Release to cast · More power reaches farther'],cast:['A line across the water','Wait for your float to settle'],waiting:['Waiting for a bite','Watch the float and hook when it dips'],bite:['A bite!','Hook now before it slips away'],reeling:['Keep the fish in the green zone','Hold to rise · Release to sink'],caught:['A lovely catch','Your catch is in your inventory'],escaped:['The fish slipped away','Cast again for another chance'],castButton:'Hold to cast',hookButton:'Hook now',reelButton:'Hold to reel',waitButton:'Waiting for a bite',castProgress:'Cast power',catchProgress:'Catch progress',tension:'Line tension',rod:'Rod',bait:'Bait',noBait:'No bait equipped',spot:'Fishing spot',fingerling:'Fingerling earned',perfect:'Perfect catch',fish:'New discovery',capacity:'Up to 5 fish per pond',keys:'Or use Space',rare:'Raise rare fingerlings in My Ponds',unknown:'Lakeside',again:'Cast again'}};
  function title(item,en){if(!item)return'';return Array.isArray(item.name)?item.name[en?1:0]||item.name[0]:item.name||item.label||item.id||'';}
  Object.assign(COPY.zh,{waiting:['等待沉漂再提竿','小啄只是试探；出现「咬钩」再提竿，提前提会跑鱼。'],waitButton:'提竿 · 等漂沉下',nibble:'鱼在试探，先等一等',cruise:'游弋',surge:'冲刺',rest:'回气',stamina:'鱼的体力',relax:'松线卸力',near:'近岸',far:'深水'});
  Object.assign(COPY.en,{waiting:['Wait for the float to dip','Small nibbles are a test. An early hook lets the fish escape.'],waitButton:'Hook · wait for the dip',nibble:'A nibble. Wait for the bite.',cruise:'Cruising',surge:'Surging',rest:'Resting',stamina:'Fish stamina',relax:'Release to ease tension',near:'Shallows',far:'Deep water'});
  Object.assign(COPY.zh,{idle:['静水等一竿','按住 F 或鼠标蓄力，松开抛竿'],bite:['咬钩了！','按 F 或点击提竿，抓住这一瞬间'],reeling:['稳住鱼，慢慢收线','按住 F 上提 · 松开下落 · 点按微调'],keys:'F / 空格 / 鼠标均可操作'});
  Object.assign(COPY.en,{idle:['A quiet moment by the water','Hold F or the mouse to charge; release to cast'],bite:['A bite!','Press F or click to hook before it slips away'],reeling:['Keep the fish in the green zone','Hold F to rise · Release to fall · Tap to adjust'],keys:'Use F, Space or the mouse'});
  function create(host,configuration){
    if(!host||!host.ownerDocument)throw new Error('A fishing game host element is required.');
    const config=configuration||{},doc=host.ownerDocument,win=doc.defaultView||globalThis,esc=Art.escape;
    let snapshot={},phase='idle',press=null,destroyed=false,lastAnnouncement='',lastRod='',lastCatch='',lastFish='',pondKey='',en=false,flightFigure=null,flightKind='';const keysDown=new Set();
    const shell=doc.createElement('section');shell.className='fishing-game'+(config.compact?' is-compact':'');shell.tabIndex=0;shell.setAttribute('aria-label','桌面钓鱼 / Desktop fishing');
    shell.innerHTML='<div class="fishing-game-stage"><div class="fishing-game-horizon"></div><div class="fishing-game-sparkle one"></div><div class="fishing-game-sparkle two"></div><div class="fishing-game-scene-top"><span class="fishing-game-location"></span><span class="fishing-game-phase"></span></div><div class="fishing-game-pond"></div><div class="fishing-game-rod"></div><svg class="fishing-game-line" viewBox="0 0 600 340" preserveAspectRatio="none" aria-hidden="true"><path d="M 225 79 Q 267 155 330 214"/></svg><div class="fishing-game-bobber"><i></i><b></b></div><div class="fishing-game-bite" aria-hidden="true"><img class="fishing-bite-art" src="/fishing-art/bite-hooked-gold-v1.png" alt="" draggable="false"></div><div class="fishing-game-catch"></div><div class="fishing-game-reel" hidden><div class="fishing-reel-track"><div class="fishing-reel-target"></div><div class="fishing-reel-fish">◆</div></div><div class="fishing-reel-progress"><i></i></div></div><div class="fishing-game-watermark">TRACER · FISHING</div></div><div class="fishing-game-instructions"><strong></strong><span></span></div><div class="fishing-game-meter" hidden><span></span><div><i></i></div><b></b></div><div class="fishing-game-loadout"><span class="fishing-game-rod-label"></span><span class="fishing-game-bait-label"></span></div><div class="fishing-game-controls"><button class="fishing-game-action" type="button"></button><span class="fishing-game-keyhint"></span></div><div class="fishing-game-live sr-only" aria-live="polite" aria-atomic="true"></div>';
    host.appendChild(shell);
    const keyboardScope=config.keyboardScope||host.closest?.('dialog')||shell;
    const find=selector=>shell.querySelector(selector),stage=find('.fishing-game-stage'),location=find('.fishing-game-location'),phaseBadge=find('.fishing-game-phase'),rodHost=find('.fishing-game-rod'),instructions=find('.fishing-game-instructions'),meter=find('.fishing-game-meter'),reel=find('.fishing-game-reel'),button=find('.fishing-game-action'),catchHost=find('.fishing-game-catch'),live=find('.fishing-game-live'),pond=Art.createPond(find('.fishing-game-pond'),{pond:{style:'stone'},fish:[],interactive:false});
    find('.fishing-reel-fish').innerHTML='<svg viewBox="0 0 24 16" aria-hidden="true"><path d="M2 8C5 2 12 1 18 6L23 3V13L18 10C12 15 5 14 2 8Z"/><circle cx="6" cy="7" r="1"/></svg>';
    const flightFish=doc.createElement('div');flightFish.className='fishing-game-flight-fish';flightFish.hidden=true;flightFish.setAttribute('aria-hidden','true');stage.appendChild(flightFish);
    const catchShadow=doc.createElement('div');catchShadow.className='fishing-catch-shadow';catchShadow.setAttribute('aria-hidden','true');stage.insertBefore(catchShadow,flightFish);
    const castTarget=doc.createElement('div');castTarget.className='fishing-cast-target';castTarget.hidden=true;castTarget.setAttribute('aria-hidden','true');stage.appendChild(castTarget);
    const nibbleCue=doc.createElement('span');nibbleCue.className='fishing-nibble-cue';nibbleCue.hidden=true;stage.appendChild(nibbleCue);
    const feedback=doc.createElement('div');feedback.className='fishing-game-feedback';feedback.hidden=true;feedback.innerHTML='<span class="fishing-fish-behavior"></span><span class="fishing-stamina-label"></span><i class="fishing-stamina"><b></b></i>';stage.appendChild(feedback);
    const line=find('.fishing-game-line'),motion=Motion?.create({stage,rod:rodHost,createRodFlex:host=>RodRenderer?.create(host)||Art.createRodFlex?.(host),bobber:find('.fishing-game-bobber'),line,path:line.querySelector('path'),bite:find('.fishing-game-bite'),flightFish,catchShadow,result:catchHost,pond,castTarget,nibbleCue,stamina:feedback.querySelector('b'),target:find('.fishing-reel-target'),fish:find('.fishing-reel-fish'),progress:find('.fishing-reel-progress i'),waterPoint:{x:.57,y:.63},baseAngle:-8,onFrame:frame=>{if(flightKind==='product'){flightFigure?.setVisible?.(frame.pose.fishAlpha>=.005);flightFigure?.setPose?.({phase:frame.phase,age:frame.age,angle:frame.pose.fishAngle,scale:frame.pose.fishScale,opacity:frame.pose.fishAlpha});}}});
    function action(kind,payload){if(!destroyed&&typeof config.onAction==='function')config.onAction(kind,payload||{});}
    function start(source){if(press||button.disabled)return;if(['idle','caught','escaped'].includes(phase)){press={source,kind:'cast'};action('cast-start');}else if(['waiting','bite'].includes(phase)){if(source.startsWith('keyboard:'))press={source,kind:'hook'};action('hook');}else if(phase==='reeling'){press={source,kind:'reel'};action('reel-start');}}
    function release(source,cancel){if(!press||source&&press.source!==source)return;const kind=press.kind;press=null;if(kind!=='hook')action(cancel&&kind==='cast'?'cancel':kind==='cast'?'cast-release':'reel-release');}
    function pointerDown(event){if(event.button!==0||button.disabled)return;event.preventDefault();button.focus({preventScroll:true});button.setPointerCapture?.(event.pointerId);start('pointer');}
    function pointerUp(event){release('pointer');button.releasePointerCapture?.(event.pointerId);}
    function pointerCancel(){release('pointer',true);}
    function stageHook(event){if(event.button!==0||!['waiting','bite'].includes(phase)||button.disabled)return;event.preventDefault();action('hook');}
    function keyCode(event){return event.code==='KeyF'||event.code==='Space'?event.code:!event.code&&String(event.key).toLowerCase()==='f'?'KeyF':'';}
    function editing(target){return !!(target?.isContentEditable||target?.closest?.('input,textarea,select,[contenteditable]:not([contenteditable="false"]),[role="textbox"]'));}
    function acceptsKeyboard(target){
      if(destroyed||doc.hidden||shell.isConnected===false)return false;
      const dialogs=Array.from(doc.querySelectorAll?.('dialog[open]')||[]),top=dialogs.filter(node=>node.matches?.(':modal')).at(-1)||dialogs.at(-1);
      if(top&&!top.contains(shell))return false;
      // Disabling a focused cast button or replacing a rig selector can leave
      // focus on BODY. The active fishing dialog still owns its F shortcut.
      if(keyboardScope.tagName==='DIALOG')return keyboardScope.open&&(keyboardScope.contains(target)||target===doc.body||target===doc.documentElement);
      return keyboardScope.contains(target);
    }
    function keyDown(event){const code=keyCode(event);if(!code||!acceptsKeyboard(event.target)||event.defaultPrevented||event.isComposing||event.ctrlKey||event.altKey||event.metaKey||editing(event.target)||code==='Space'&&!shell.contains(event.target))return;event.preventDefault();if(event.repeat||keysDown.has(code))return;if(phase==='caught'&&snapshot.recastRemaining>0){keysDown.add(code);return;}if(button.disabled)return;if(!shell.contains(doc.activeElement))shell.focus({preventScroll:true});keysDown.add(code);start('keyboard:'+code);}
    function keyUp(event){const code=keyCode(event);if(!code||!keysDown.delete(code))return;event.preventDefault();release('keyboard:'+code);}
    function blur(){keysDown.clear();release(null,true);}
    function focusOut(event){if(!keyboardScope.contains(event.relatedTarget)||editing(event.relatedTarget))blur();}
    function visibility(){if(doc.hidden)blur();}
    function click(event){if(event.detail===0&&['waiting','bite'].includes(phase)&&!button.disabled)action('hook');}
    button.addEventListener('pointerdown',pointerDown);button.addEventListener('pointerup',pointerUp);button.addEventListener('pointercancel',pointerCancel);button.addEventListener('lostpointercapture',pointerCancel);button.addEventListener('click',click);stage.addEventListener('pointerdown',stageHook);win.addEventListener('keydown',keyDown);keyboardScope.addEventListener('focusout',focusOut);win.addEventListener('keyup',keyUp);win.addEventListener('blur',blur);doc.addEventListener('visibilitychange',visibility);
    function update(next){
      if(destroyed)return;snapshot=next||{};const session=snapshot.session||{},newPhase=session.phase||'idle';en=String(snapshot.lang||snapshot.language||config.lang||'zh').startsWith('en');const copy=COPY[en?'en':'zh'];phase=newPhase in copy?newPhase:'idle';
      if(press?.kind==='hook'&&phase==='reeling'){press.kind='reel';action('reel-start');}
      if(press&&((press.kind==='cast'&&phase!=='charging'&&phase!=='idle')||(press.kind==='reel'&&phase!=='reeling')||(press.kind==='hook'&&!['waiting','bite'].includes(phase))))press=null;
      shell.dataset.phase=phase;stage.dataset.phase=phase;const words=copy[phase];instructions.querySelector('strong').textContent=words[0];instructions.querySelector('span').textContent=snapshot.error||words[1];phaseBadge.textContent=phase==='bite'?(en?'BITE!':'咬钩'):phase==='reeling'?(en?'REELING':'收线'):phase==='caught'?(en?'CAUGHT':'收获'):(en?'FREE FISHING':'自由垂钓');location.textContent='◌ '+(title(snapshot.spot,en)||copy.unknown);
      const rod=snapshot.rod||{id:'bamboo',style:'bamboo',color:'#a2a36c',accent:'#d8cc9d'},rodKey=JSON.stringify([rod.id,rod.color,rod.accent,rod.style]);if(rodKey!==lastRod){rodHost.innerHTML=Art.rodMarkup(rod);lastRod=rodKey;}
      const shownPond=snapshot.desktopPond||{pond:{style:snapshot.spot&&snapshot.spot.pondStyle||snapshot.pondStyle||'stone'},fish:[]},nextPondKey=JSON.stringify(shownPond);if(nextPondKey!==pondKey){pond.update(shownPond);pondKey=nextPondKey;}
      find('.fishing-game-rod-label').innerHTML='<i>'+esc(copy.rod)+'</i> '+esc(title(rod,en));find('.fishing-game-bait-label').innerHTML='<i>'+esc(copy.bait)+'</i> '+esc(title(snapshot.bait,en)||copy.noBait);
      const holding=phase==='charging'||phase==='reeling',recastPause=phase==='caught'&&snapshot.recastRemaining>0,disabled=phase==='cast'||recastPause||snapshot.disabled===true||snapshot.busy===true;if(disabled&&doc.activeElement===button)shell.focus({preventScroll:true});button.disabled=disabled;button.textContent=recastPause?(en?'Catch display · ':'收获展示 · ')+Math.ceil(snapshot.recastRemaining/1000)+(en?'s':' 秒'):phase==='bite'?copy.hookButton:phase==='reeling'?copy.reelButton:phase==='waiting'?copy.waitButton:button.disabled?copy.waitButton:['caught','escaped'].includes(phase)?copy.again:copy.castButton;button.setAttribute('aria-label',button.textContent+' · '+words[1]);find('.fishing-game-keyhint').textContent=recastPause?(en?'Enjoy your catch. Press again when the pause ends.':'先欣赏本次收获，展示结束后重新按下抛竿'):copy.keys;
      meter.hidden=!holding;reel.hidden=phase!=='reeling';const power=clamp(session.castPower),progress=clamp(session.progress),tension=clamp(session.tension);meter.querySelector('span').textContent=phase==='charging'?copy.castProgress:copy.catchProgress;meter.querySelector('i').style.width=(phase==='charging'?power:progress)*100+'%';meter.querySelector('b').textContent=Math.round((phase==='charging'?power:progress)*100)+'%';meter.dataset.warning=tension>.8?'true':'false';
      if(!motion){const size=Math.max(.06,Math.min(.8,Number(session.barSize)||.25)),position=Math.max(size/2,Math.min(1-size/2,clamp(session.barPosition)));find('.fishing-reel-target').style.height=size*100+'%';find('.fishing-reel-target').style.bottom=(position-size/2)*100+'%';find('.fishing-reel-fish').style.bottom=clamp(session.fishPosition)*100+'%';find('.fishing-reel-progress i').style.height=progress*100+'%';}reel.setAttribute('aria-label',copy.catchProgress+' '+Math.round(progress*100)+'%, '+copy.tension+' '+Math.round(tension*100)+'%');
      const bobber=find('.fishing-game-bobber');bobber.style.setProperty('--cast-distance',String(Math.round(power*38)));rodHost.style.setProperty('--cast-power',String(power));stage.style.setProperty('--line-tension',String(tension));
      const behavior=['cruise','surge','rest'].includes(session.fishBehavior)?session.fishBehavior:'cruise';feedback.hidden=phase!=='reeling';feedback.querySelector('.fishing-fish-behavior').textContent=tension>.8?copy.relax:copy[behavior];feedback.querySelector('.fishing-stamina-label').textContent=copy.stamina;feedback.setAttribute('aria-label',copy[behavior]+' · '+copy.stamina+' '+Math.round(clamp(session.stamina===undefined?1:session.stamina)*100)+'%');
      nibbleCue.textContent=copy.nibble;if(phase==='waiting'&&clamp(session.nibble)>.08)instructions.querySelector('span').textContent=copy.nibble;
      if(phase==='reeling')instructions.querySelector('span').textContent=tension>.8?copy.relax:behavior==='surge'?(en?'A surge! Track the fish; release if the line strains.':'鱼在冲刺！跟住鱼，张力过高时松线。'):behavior==='rest'?(en?'The fish is resting. Stay in green to wear it down.':'鱼在回气，保持在绿色区间消耗它的体力。'):words[1];
      const result=snapshot.result||session.catch||snapshot.lastCatch||{},catalog=snapshot.catalog&&snapshot.catalog.fish||snapshot.catalog&&snapshot.catalog.fishes||[],fishId=session.fishId||result.fishId||result.catch&&result.catch.fishId,identified=win.TracerFishingModel?.catchItem?.(session.fishId?session:result.catch||result),fish=identified?.kind?identified:snapshot.fish||(typeof fishId==='string'?Array.isArray(catalog)?catalog.find(f=>f.id===fishId):catalog[fishId]:null)||result.fish||identified;
      const product=fish?.kind==='junk'||fish?.kind==='mystery',figureKey=JSON.stringify([fish?.id||'',fish?.kind||'',fish?.variant||'']),rewards=win.TracerFishingRewards;
      const productWords=fish?.kind==='mystery'?[en?'A mysterious gift from the water':'从水里钓起一份惊喜',en?'Open it in your aquarium to reveal a gift':'前往水族馆打开，揭晓神秘礼物']:[en?'You fished out a piece of salvage':'钓起一件水中杂物',en?'Saved in your basket · Worth 1 coin':'已收入鱼篓 · 价值 1 金币'];
      if(product&&phase==='caught'){instructions.querySelector('strong').textContent=productWords[0];instructions.querySelector('span').textContent=snapshot.error||productWords[1];}
      // Use the collection's model atlas for the brief catch flight. A second
      // WebGL context must not consume live input or the catch display pause.
      if(phase==='caught'&&figureKey!==lastFish){
        const nextKind=product?'product':'fish';if(nextKind!==flightKind){flightFigure?.destroy();flightFigure=null;flightFish.replaceChildren();flightKind=nextKind;}
        if(product){if(!flightFigure&&rewards?.createFigure)flightFigure=rewards.createFigure(flightFish,{fish});else if(flightFigure)flightFigure.setFish?.(fish);else flightFish.innerHTML=rewards?.markup?.(fish)||'';}
        else{flightFigure?.destroy();flightFigure=null;flightFish.innerHTML=fish?Art.fishMarkup(fish):'';}
        flightFish.dataset.catchKind=fish?.kind||'fish';flightFish.dataset.catchVariant=fish?.variant||'';lastFish=figureKey;
      }
      const caughtRod=(snapshot.catalog?.rods||[]).find(r=>r.id===session.rodId)||snapshot.rod,bonus=!product&&caughtRod?.saleMultiplier===2;
      const hasFry=!product&&!!(result.fry||result.fingerlingId||result.fingerling||result.rare),perfect=result.perfect||result.catch&&result.catch.quality==='perfect',catchKey=JSON.stringify([phase,figureKey,hasFry,perfect,en,bonus]);if(catchKey!==lastCatch){
        const junkNames={boots:['旧靴子','Old boots'],broken_watch:['破手表','Broken watch'],trash_bag:['垃圾袋','Trash bag']},label=fish?.kind==='junk'?(junkNames[fish.variant]?.[en?1:0]||title(fish,en)):title(fish,en),caption=fish?.kind==='junk'?(en?'SALVAGE · 1 COIN':'水中杂物 · 1 金币'):fish?.kind==='mystery'?(en?'A MYSTERIOUS FIND':'钓到神秘大礼包'):bonus?(en?'GOLDEN CATCH · VALUE ×2':'黄金赐福 · 售价 ×2'):(en?'IN YOUR BASKET':'已收入鱼篓'),detail=fish?.kind==='junk'?(en?'Saved in your basket':'已收入鱼篓'):fish?.kind==='mystery'?(en?'Open it in your aquarium to reveal a gift':'前往水族馆打开，揭晓神秘礼物'):hasFry?copy.fingerling:perfect?copy.perfect:copy.fish;
        const shownDetail=hasFry?(fish?.rarity==='legendary'?(en?'Bonus fingerling · Aquarium nursery':'额外鱼苗 · 已进入水族箱育养箱'):(en?'Bonus fingerling · My Ponds nursery':'额外鱼苗 · 前往「我的鱼塘」放养')):detail;
        catchHost.innerHTML=phase==='caught'&&fish?`<small>${esc(caption)}</small><strong>${esc(label)}</strong><span>${esc(shownDetail)}</span>`:'';lastCatch=catchKey;
      }
      const spoken=product&&phase==='caught'?productWords:words,announcement=phase+':'+spoken[0];if(announcement!==lastAnnouncement){live.textContent=spoken.join('。');lastAnnouncement=announcement;}
      motion?.update(fish?{...snapshot,fish}:snapshot);
    }
    update(config.snapshot||{});
    return{update,destroy(){if(destroyed)return;blur();destroyed=true;motion?.destroy();flightFigure?.destroy();pond.destroy();button.removeEventListener('pointerdown',pointerDown);button.removeEventListener('pointerup',pointerUp);button.removeEventListener('pointercancel',pointerCancel);button.removeEventListener('lostpointercapture',pointerCancel);button.removeEventListener('click',click);stage.removeEventListener('pointerdown',stageHook);win.removeEventListener('keydown',keyDown);keyboardScope.removeEventListener('focusout',focusOut);win.removeEventListener('keyup',keyUp);win.removeEventListener('blur',blur);doc.removeEventListener('visibilitychange',visibility);shell.remove();},focus(){shell.focus({preventScroll:true});}};
  }
  return Object.freeze({create});
});
