(function(root){
  'use strict';
  const F=root.TracerFishingModel,A=root.TracerFishingArt;
  const escape=A.escape;
  function create(host,options={}){
    const doc=host.ownerDocument,section=options.section||'ponds';
    let snapshot=null,signature='',selectedPond='',filter='all',selectedPool='basic',pondPlayer=null,tackleBox=null,tackleSelection='',destroyed=false,feeding=null,editing=false,selectedDecoration='',aquariumPlayer=null,showcaseEditing=false,showcaseDraft=null;
    const page=doc.createElement('div');page.className='fishing-page fishing-page-'+section;host.append(page);
    const tr=(zh,en)=>snapshot?.language==='en'?en:zh;
    const name=item=>Array.isArray(item?.name)?item.name[snapshot?.language==='en'?1:0]:item?.name||'';
    const effectNote=rod=>rod.effectDescription?'<p class="fishing-rod-effect-note">'+escape(name({name:rod.effectDescription}))+'</p>':'';
    const rarity=id=>({common:tr('寻常','Common'),rare:tr('珍稀','Rare'),epic:tr('史诗','Epic'),legendary:tr('传说','Legendary')})[id]||id;
    const button=(action,label,value='',disabled=false,extra='')=>'<button type="button" class="fishing-button '+extra+'" data-fishing-action="'+action+'" data-value="'+escape(value)+'" '+(disabled?'disabled':'')+'>'+escape(label)+'</button>';
    const fishCard=(fish,copy,actions='')=>'<article class="fishing-fish-card" data-rarity="'+(fish.rarity||'common')+'"><div class="fishing-fish-art">'+(fish.kind==='junk'||fish.kind==='mystery'?root.TracerFishingRewards.markup(fish):A.fishMarkup(fish))+'</div><div><span class="fishing-rarity">'+(fish.kind==='junk'?tr('水中杂物','Found object'):fish.kind==='mystery'?tr('神秘收获','Mystery catch'):rarity(fish.rarity))+'</span><h3>'+escape(name(fish))+'</h3><p>'+copy+'</p>'+actions+'</div></article>';
    function heading(title,subtitle){return '<header class="fishing-heading"><div><span class="fishing-eyebrow">TRACER / WATERSIDE</span><h1>'+title+'</h1><p>'+subtitle+'</p></div><div class="fishing-heading-actions"><span class="fishing-wallet">◈ '+snapshot.economy.balance.toLocaleString()+'</span>'+button('open-game',tr('去钓鱼 ↗','Go fishing ↗'),' ',false,'primary')+'</div></header>';}
    function notice(){return '<div class="fishing-notice" role="status" '+(!snapshot.error&&!snapshot.notice?'hidden':'')+'>'+escape(snapshot.error||snapshot.notice||'')+(snapshot.error?button('retry-save',tr('重试保存','Retry save')):'')+'</div>';}
    function rods(){
      const s=snapshot.state,active=F.catalog.rods.find(r=>r.id===s.equippedRodId);
      let out=heading(tr('一竿，一种想象。','A rod. A new possibility.'),tr('从溪边竹影，到九霄星河。选择你的下一段水边时光。','From a quiet bamboo bank to a sky full of stars. Find your next waterside moment.'))+notice();
      out+='<section class="fishing-rod-feature"><div class="fishing-feature-art">'+A.rodMarkup(active)+'</div><div><span class="fishing-eyebrow">'+tr('当前装备 / READY TO CAST','EQUIPPED / READY TO CAST')+'</span><h2>'+escape(name(active))+'</h2>'+effectNote(active)+'<p>'+tr('所有鱼竿都能钓到稀有鱼。更好的控竿区间，让收线更从容。','Every rod can catch rare fish. A larger control zone makes reeling more forgiving.')+'</p><div class="fishing-feature-stats"><span>'+tr('收集进度','Collection')+' <b>'+s.rods.length+' / '+F.catalog.rods.length+'</b></span><span>'+tr('控竿区间','Control zone')+' <b>'+Math.round(active.barSize*100)+'%</b></span></div>'+button('open-shop',tr('探索鱼竿盲盒 →','Explore rod boxes →'))+'</div></section>';
      out+='<nav class="fishing-filters" aria-label="'+tr('鱼竿筛选','Rod filters')+'">'+[['all',tr('全部鱼竿','All rods')],['owned',tr('已收藏','Collected')],['real',tr('现实匠作','Crafted')],['fantasy',tr('奇幻星光','Fantasy')],['xianxia',tr('仙侠灵韵','Celestial')]].map(([id,label])=>button('filter',label,id,false,filter===id?'selected':'')).join('')+'</nav><div class="fishing-rod-grid">';
      for(const rod of F.catalog.rods.filter(r=>filter==='all'||filter==='owned'&&s.rods.includes(r.id)||r.family===filter)){
        const owned=s.rods.includes(rod.id),equipped=rod.id===s.equippedRodId;
        if(rod.hidden&&!owned){out+='<article class="fishing-rod-card fishing-secret-card" data-hidden-reward><span class="fishing-rarity">'+escape(name(F.catalog.rodPools.find(p=>p.hiddenRodId===rod.id)))+' · '+tr('隐藏款','Secret')+'</span><div class="fishing-rod-art fishing-secret-art" aria-hidden="true">?</div><h3>'+tr('尚未揭晓','Yet to be discovered')+'</h3><p>'+tr('0.5% · 开出后揭晓外观','0.5% · Appearance revealed on discovery')+'</p>'+button('open-shop',tr('前往基础奖池','Explore base collection'))+'</article>';continue;}
        out+='<article class="fishing-rod-card" data-rarity="'+rod.rarity+'" data-owned="'+owned+'"><span class="fishing-rarity">'+rarity(rod.rarity)+'</span><div class="fishing-rod-art">'+A.rodMarkup(rod)+'</div><h3>'+escape(name(rod))+'</h3>'+effectNote(rod)+'<p>'+tr('控竿区间 ','Control zone ')+Math.round(rod.barSize*100)+'% · '+tr('手感 ','Control ')+rod.control.toFixed(2)+'</p>'+button(owned?'equip-rod':'open-shop',equipped?tr('已装备','Equipped'):owned?tr('装备鱼竿','Equip rod'):tr('盲盒中发现','Discover in boxes'),rod.id,equipped||snapshot.busy,owned?'':'quiet')+'</article>';
      }
      return out+'</div>';
    }
    const baitBox=shop=>'<div class="fishing-tackle-mount" data-tackle-box-mode="'+(shop?'shop':'equip')+'"></div>';
    function tackle(){
      const pool=F.catalog.rodPools.find(p=>p.id===selectedPool)||F.catalog.rodPools[0],pity=F.pity(snapshot.state,pool.id);
      return heading(tr('水边的小惊喜','A little waterside wonder'),tr('同品质优先获得未收藏的鱼竿，集齐该品质后才会重复。','Each rarity gives uncollected rods first; duplicates arrive after that tier is complete.'))+notice()+(F.catalog.rodPools.length>1?'<nav class="fishing-filters">'+F.catalog.rodPools.map(p=>button('select-pool',name(p),p.id,false,p.id===pool.id?'selected':'')).join('')+'</nav>':'')+
        '<section class="fishing-box-feature"><div><span class="fishing-eyebrow">'+escape(name(pool))+' · VOL. 01</span><h2>'+tr('拆开一片<br>未知的水面。','Unwrap<br>uncharted waters.')+'</h2><p>'+tr((pool.rodIds.length+1)+' 款惊喜鱼竿，从现实到奇幻与仙侠。每次开启获得 1 款；初始竹竿不占抽取位置。',(pool.rodIds.length+1)+' collectible rods, from the handcrafted to the celestial. One rod per box; the starter bamboo rod is excluded.')+'</p>'+button('buy-box',tr('开启鱼竿盲盒 · 100 金币','Open a rod box · 100 coins'),pool.id,snapshot.busy||snapshot.economy.balance<F.BOX_PRICE,'primary')+'<small>'+tr('重复鱼竿返还 20 / 40 / 75 / 150 金币','Duplicates return 20 / 40 / 75 / 150 coins')+'</small></div><div class="fishing-box-display" aria-hidden="true">'+['common','epic','legendary'].map(tier=>F.catalog.rods.find(r=>pool.rodIds.includes(r.id)&&r.rarity===tier)).filter(Boolean).map(r=>A.rodMarkup(r)).join('')+'<span>THE UNKNOWN<br>IS WAITING</span></div></section>'+
        '<div class="fishing-odds">'+Object.entries(pool.odds).sort(([a],[b])=>Number(a==='hidden')-Number(b==='hidden')).map(([id,p])=>'<div data-rarity="'+id+'"><span>'+(id==='hidden'?tr('隐藏款','Secret'):rarity(id))+'</span><strong>'+Number((p*100).toFixed(1))+'%</strong></div>').join('')+'</div><p class="fishing-pity">'+tr('最多再开 '+pity.epicRemaining+' 盒必出史诗或以上，'+pity.legendaryRemaining+' 盒必出传说。对应品质出现后重置。隐藏款每抽固定 0.5%，不受保底影响；开出前不展示外观。','Epic or better within '+pity.epicRemaining+' boxes; legendary within '+pity.legendaryRemaining+'. Each guarantee resets when its tier appears. Secret: a fixed 0.5% per draw, unaffected by guarantees; appearance is concealed until discovered.')+'</p><div class="fishing-section-heading"><h2>'+tr('挑一袋鱼饵，去水边。','A little bait. A new adventure.')+'</h2></div>'+baitBox(true);
    }
    function decorationEditor(){
      const pond=snapshot.state.ponds.find(p=>p.id===selectedPond),items=pond?.decorations||[],selected=items.find(d=>d.id===selectedDecoration),catalog=F.catalog.decorations||[];
      const sprite=kind=>A.decorationMarkup(kind);
      let html='<div class="fishing-decor-heading"><div><h3>'+tr('布置水边小天地','Make this shore your own')+'</h3><p>'+tr('拖动场景中的装饰摆放，留出水面看鱼儿。装饰免费。','Drag decorations in the scene. Leave room to watch your fish. All decorations are free.')+'</p></div><small>'+items.length+' / 16</small></div><div class="fishing-decor-catalog">';
      for(const d of catalog)html+='<button type="button" data-fishing-action="add-decoration" data-value="'+d.id+'" '+(snapshot.busy||items.length>=16?'disabled':'')+' title="'+escape(tr('添加 ','Add ')+name(d))+'">'+sprite(d.id)+'<span>'+escape(name(d))+'</span><i>＋</i></button>';
      html+='</div><div class="fishing-decor-selection"><label>'+tr('选中装饰','Selected decoration')+'<select data-decoration-select><option value="">'+tr('点击场景中的装饰','Choose a decoration in the scene')+'</option>'+items.map((d,i)=>'<option value="'+d.id+'" '+(d.id===selectedDecoration?'selected':'')+'>'+escape(name(catalog.find(c=>c.id===d.kind)))+' '+(i+1)+'</option>').join('')+'</select></label><div class="fishing-decor-tools">';
      for(const [id,label]of [['left','←'],['up','↑'],['down','↓'],['right','→'],['rotate',tr('转向','Turn')],['smaller','−'],['larger','＋'],['remove',tr('收起','Remove')]])html+=button('decor-'+id,label,'',!selected||snapshot.busy,'quiet');
      return html+'</div></div>'+button('reset-decorations',tr('恢复推荐布局','Restore recommended layout'),'',snapshot.busy,'quiet');
    }
    function renderEditor(){const editor=page.querySelector('[data-decoration-editor]');if(!editor)return;editor.hidden=!editing;editor.innerHTML=editing?decorationEditor():'';const toggle=page.querySelector('[data-fishing-action="edit-decorations"]');if(toggle){toggle.textContent=editing?tr('完成布置','Finish decorating'):tr('布置鱼塘','Decorate pond');toggle.setAttribute('aria-pressed',String(editing));}pondPlayer?.update?.({editing,selectedDecorationId:selectedDecoration});}
    function pondFingerlings(){return snapshot.state.fry.filter(f=>f.releasedAt===null&&f.pondId===null&&['rare','epic'].includes(F.catalog.fish.find(x=>x.id===f.fishId)?.rarity));}
    function pondNursery(pond){
      const available=pondFingerlings(),s=snapshot.state,archived=pond.archivedAt!==null,full=s.fry.filter(f=>f.pondId===pond.id&&f.releasedAt===null).length>=F.MAX_FISH;
      let out='<section class="fishing-pond-nursery" data-pond-nursery><header><h3>'+tr('待放养鱼苗','Pond nursery')+'</h3><span>'+available.length+'</span></header><p>'+tr('珍稀和史诗鱼苗可放入鱼塘，每塘最多五条。','Rare and epic fingerlings can live in a pond, up to five per pond.')+'</p>';
      if(archived)out+='<p class="fishing-pond-nursery-hint">'+tr('这座鱼塘已珍藏，切换到新鱼塘继续放养。','This pond is archived. Switch to your open pond to add fish.')+'</p>'+button('select-pond',tr('切换到可放养鱼塘','Switch to open pond'),s.activePondId,snapshot.busy);
      else if(full)out+='<p class="fishing-pond-nursery-hint">'+tr('鱼塘已满，可先取回一条，或珍藏后开启新鱼塘。','This pond is full. Return a resident to the nursery, or archive it to start a new pond.')+'</p>';
      out+='<div class="fishing-pond-fry-list">';
      for(const fry of available.slice().reverse()){const fish=F.catalog.fish.find(f=>f.id===fry.fishId);out+='<article class="fishing-pond-fry" data-fry-id="'+fry.id+'" data-rarity="'+fish.rarity+'"><div class="fishing-pond-fry-art">'+A.fishMarkup(fish)+'</div><div><span class="fishing-rarity">'+rarity(fish.rarity)+'</span><h4>'+escape(name(fish))+'</h4><small>'+tr('成长 ','Growth ')+fry.growth+'%</small></div>'+button('place-pond-fish',archived?tr('已珍藏','Archived'):full?tr('鱼塘已满','Pond full'):tr('放入这座鱼塘','Place in this pond'),fry.id,snapshot.busy||archived||full,'primary')+'</article>';}
      if(!available.length)out+='<p class="fishing-pond-nursery-empty">'+tr('钓到珍稀或史诗鱼后，额外获得的鱼苗会在这里。已钓到的鱼苗也会保留。','Rare and epic catches give you fingerlings that wait here until placed.')+'</p>';
      return out+'</div><p class="fishing-pond-nursery-footer">'+tr('传奇鱼请入住水族箱。','Legendary fish live in the aquarium.')+'</p>'+button('open-aquarium',tr('前往传奇水族箱 →','Legendary aquarium →'),' ',snapshot.busy,'quiet')+'</section>';
    }
    function ponds(){
      const s=snapshot.state,active=s.ponds.find(p=>!p.archivedAt)||s.ponds[0];
      if(!s.ponds.some(p=>p.id===selectedPond))selectedPond=active.id;
      const pond=s.ponds.find(p=>p.id===selectedPond),style=F.catalog.pondStyles.find(p=>p.id===pond.styleId),residents=s.fry.filter(f=>f.pondId===pond.id&&!f.releasedAt),archived=!!pond.archivedAt;
      let out=heading(tr('把喜欢，养成一池。','A little pond of your own.'),tr('从鱼苗育养箱挑选珍稀和史诗鱼，养成自己的水边收藏。传奇鱼请入住水族箱。','Raise rare and epic fingerlings in your own pond. Legendary fish live in the aquarium.'))+notice();
      out+='<div class="fishing-pond-layout"><aside class="fishing-pond-list"><span class="fishing-eyebrow">'+tr('我的鱼塘','MY PONDS')+'</span>'+s.ponds.map((p,i)=>{const st=F.catalog.pondStyles.find(x=>x.id===p.styleId),n=s.fry.filter(f=>f.pondId===p.id&&!f.releasedAt).length;return '<button type="button" data-fishing-action="select-pond" data-value="'+p.id+'" class="fishing-pond-tab '+(p.id===pond.id?'selected':'')+'"><i style="--pond-color:'+st.color+'"></i><span><strong>'+escape(name(st))+' <small>'+String(i+1).padStart(2,'0')+'</small></strong><small>'+(p.archivedAt?tr('已珍藏 · 可投喂','Collected · Ready to feed'):tr('已有水景','Waterside scenery'))+' · '+n+'/5</small></span></button>';}).join('')+'<p>'+tr('这里保留你的水景和历史收藏。传奇鱼请前往水族箱入住。','Your scenery and past collections stay here. New legendary residents live in the aquarium.')+'</p>'+pondNursery(pond)+'</aside><section class="fishing-pond-detail"><div class="fishing-pond-title"><div><span class="fishing-eyebrow">'+(archived?'POND COLLECTION':'YOUR LIVING COLLECTION')+'</span><h2>'+escape(name(style))+'</h2></div><strong>'+residents.length+' <small>/ 5</small></strong></div><div class="fishing-pond-canvas" id="fishing-pond-canvas"></div><div class="fishing-pond-toolbar">'+(root.TracerFishing?button('pin-pond',tr('这座摆到桌面 ↗','Show this pond on desktop ↗')):'')+button('feed-pond',tr('投喂 · 5 金币','Feed · 5 coins'),pond.id,snapshot.busy||!residents.some(f=>f.fedAt===null||Date.now()-f.fedAt>=60000)||snapshot.economy.balance<5,'primary')+(!archived&&residents.length===5?button('archive-request',tr('确认五条 · 珍藏鱼塘','Confirm five · Keep this pond'),pond.id,residents.length!==5||snapshot.busy):!archived?'':'<span class="fishing-collection-seal">✧ '+tr('已珍藏','COLLECTED')+'</span>')+'<small>'+tr('拖动旋转 · 滚轮缩放','Drag to rotate · Scroll to zoom')+'</small></div>';
      if(!archived)out+='<div class="fishing-pond-styles"><span>'+tr('免费换景','FREE SCENERY')+'</span>'+F.catalog.pondStyles.map(p=>button('pond-style',name(p),p.id,snapshot.busy||p.id===pond.styleId,p.id===pond.styleId?'selected':'')).join('')+'</div>';
      out+='<div class="fishing-decor-bar">'+button('edit-decorations',editing?tr('完成布置','Finish decorating'):tr('布置鱼塘','Decorate pond'),'',snapshot.busy)+'<span>'+tr('树影、花丛与岸边小物，摆成你喜欢的样子。','Arrange trees, flowers and little waterside treasures.')+'</span></div><section class="fishing-decor-editor" data-decoration-editor '+(editing?'':'hidden')+'>'+(editing?decorationEditor():'')+'</section><div class="fishing-residents">';
      for(const fry of residents){const f=F.catalog.fish.find(x=>x.id===fry.fishId);out+=fishCard(f,'<span class="fishing-growth"><i style="width:'+fry.growth+'%"></i></span>'+tr('成长 ','Growth ')+fry.growth+'%'+(f.feedingReaction?'<br>'+escape(name({name:f.feedingReaction.description||f.feedingReaction.name||f.feedingReaction})):''),archived?'':button('take-pond-fish',tr('取回育养箱','Return to nursery'),fry.id,snapshot.busy)+button('release-request',tr('放生','Release fish'),fry.id,snapshot.busy,'quiet'));}
      if(!residents.length)out+='<div class="fishing-empty">⌁<h3>'+tr('水面已经准备好了','The water is waiting')+'</h3><p>'+tr('从「待放养鱼苗」选择一条珍稀或史诗鱼，放进这座鱼塘。','Choose a rare or epic fingerling from the pond nursery to move in.')+'</p>'+button('manage-pond-nursery',tr('查看待放养鱼苗','View pond nursery'))+'</div>';
      out+='</div></section></div>';
      return out;
    }
    function showcaseValue(){
      const value=snapshot.showcase;if(!showcaseEditing||!showcaseDraft||!value)return value;
      return {...value,selection:{...value.selection,...showcaseDraft},fish:value.fish};
    }
    function aquariumDecorationEditor(){
      const selected=showcaseDraft.decorationIds||root.TracerFishingAquariumArt.defaultDecorations;
      return '<div class="fishing-aquarium-decor-editor" data-aquarium-decor-editor><h3>'+tr('布置水下小天地','Decorate your underwater world')+'</h3><p>'+tr('装饰免费使用，最多放三件，按选择顺序从左向右摆放。再次点击即可取走。','All decorations are free. Choose up to three, placed from left to right in selection order. Click again to remove.')+'</p><div class="fishing-aquarium-choices">'+F.catalog.aquariumDecorations.map(d=>'<button type="button" class="fishing-aquarium-choice" data-fishing-action="showcase-decoration" data-value="'+d.id+'" aria-pressed="'+selected.includes(d.id)+'" '+(snapshot.busy||selected.length>=3&&!selected.includes(d.id)?'disabled':'')+'>'+root.TracerFishingAquariumArt.decorationMarkup(d.id)+'<span>'+escape(name(d))+'</span></button>').join('')+'</div><p class="fishing-aquarium-message">'+selected.length+' / 3 · '+tr('装饰会和鱼一起保存到桌面水族箱','Decorations sync with your fish to the desktop aquarium')+'</p></div>';
    }
    function showcaseEditor(){
      if(!showcaseEditing||!showcaseDraft)return '';
      return aquariumDecorationEditor()+'<div class="fishing-aquarium-actions">'+button('save-showcase',tr('保存布置','Save decorations'),'',snapshot.busy,'primary')+button('cancel-showcase',tr('取消','Cancel'),'',snapshot.busy,'quiet')+'</div>';
    }
    function renderShowcaseEditor(){const mount=page.querySelector('[data-showcase-editor]');if(mount){mount.hidden=!showcaseEditing;mount.innerHTML=showcaseEditor();}aquariumPlayer?.update(showcaseValue(),snapshot.language);}
    function aquarium(){
      const s=snapshot.state,bag=s.catches.filter(c=>c.soldAt===null&&!F.catchItem(c)?.openable),bagValue=bag.reduce((sum,c)=>sum+F.catchValue(s,c),0);
      const discovered=new Set(s.catches.filter(c=>F.catalog.fish.some(f=>f.id===c.fishId)).map(x=>x.fishId)),legends=F.catalog.fish.filter(f=>f.rarity==='legendary');
      let out=heading(tr('把传奇，留在眼前。','Keep your legends close.'),tr('专为传奇鱼准备的水族箱，也能摆在桌面陪你办公。','A home for your legendary fish, ready to sit on your desktop.'))+notice();
      out+='<section class="fishing-aquarium-feature"><div data-aquarium-display></div><div><span class="fishing-eyebrow">LEGENDARY AQUARIUM</span><h2>'+tr('你的传奇水族箱','Your legendary aquarium')+'</h2><p>'+tr('月冠、玉饰与星光，在一方清水里慢慢游动。从育养箱挑选三条传奇鱼，放入水族箱陪你办公。','Moon crowns, jade and starlight in a little world of water. Move three legendary fingerlings from your nursery into a home on your desktop.')+'</p><div class="fishing-aquarium-picked">'+(snapshot.showcase?.fish||[]).map(f=>'<span>'+escape(name(f))+'</span>').join('')+'</div><div class="fishing-feature-stats"><span>'+tr('传奇发现','Legends discovered')+' <b>'+legends.filter(f=>discovered.has(f.id)).length+' / '+legends.length+'</b></span><span>'+tr('正在展示','On display')+' <b>'+(snapshot.showcase?.fish.length||0)+' / 3</b></span></div><div class="fishing-aquarium-actions">'+button('manage-aquarium',tr('放入传奇鱼','Add legendary fish'),'',snapshot.busy,'primary')+button('edit-aquarium-decor',tr('布置水族箱','Decorate aquarium'),'',snapshot.busy)+button('pin-aquarium',root.TracerFishingAquarium?tr('摆到桌面 ↗','Place on desktop ↗'):tr('预览桌面水族箱','Preview desktop aquarium'))+(root.TracerFishingAquarium?button('hide-aquarium',tr('从桌面隐藏','Hide from desktop')):'')+'</div><p class="fishing-aquarium-desktop-note">'+(root.TracerFishingAquarium?tr('透明桌面摆件，可拖动、收起，展示选择会同步更新。','A transparent desktop ornament. Move or hide it; your fish selection stays in sync.'):tr('桌面客户端可独立摆放水族箱；这里可以预览相同的展示。','Use the desktop app for a standalone aquarium; preview the same display here.'))+'</p></div></section><section class="fishing-aquarium-editor" data-showcase-editor '+(showcaseEditing?'':'hidden')+'>'+showcaseEditor()+'</section>';
      out+=aquariumResidents();
      out+=mysteryCollection();
      out+='<div class="fishing-section-heading"><h2>'+tr('出发前，打开钓具箱。','Open your tackle box before you go.')+'</h2></div>'+baitBox(false);
      out+='<div class="fishing-section-heading" data-catch-basket><h2>'+tr('今日鱼篓','The catch basket')+' <span>'+bag.length+'</span></h2>'+button('sell-all-fish',bag.length?tr('全部出售 · '+bag.length+' 件 · ','Sell all · '+bag.length+' catches · ')+'◈ '+bagValue:tr('暂无可出售的收获','No catches to sell'),'',snapshot.busy||!bag.length,'primary')+'<p>'+tr('普通收获直接出售，含传奇鱼时会提醒确认。神秘礼包保留；育养箱、水族箱住客和图鉴记录保留。','Sell regular catches instantly; sales including legendary fish ask for confirmation. Mystery bundles, nursery fish, aquarium residents and journal records stay.')+'</p></div><div class="fishing-catch-grid">';
      for(const caught of bag.slice(-60).reverse()){const f=F.catchItem(caught),variantNames={boots:tr('旧靴子','Old boot'),broken_watch:tr('破手表','Broken watch'),trash_bag:tr('垃圾袋','Rubbish bag')};out+=fishCard(f,f.kind==='junk'?escape(variantNames[f.variant]||'')+' · '+tr('固定价值 1 金币','Always worth 1 coin'):caught.length+' cm · '+(caught.quality==='perfect'?tr('完美捕获','Perfect catch'):tr('水边收获','A waterside catch')),button('sell-fish',tr('出售 · ','Sell · ')+'◈ '+F.catchValue(s,caught)+(F.catchValue(s,caught)>f.price?' · ×2':''),caught.id,snapshot.busy));}
      if(!bag.length)out+='<p class="fishing-soft-empty">'+tr('空空的鱼篓，等一个好故事。','An empty basket, waiting for a good story.')+'</p>';
      out+='</div><div class="fishing-section-heading"><h2>'+tr('水生图鉴','The aquatic journal')+'</h2><p>'+tr('每种鱼的鱼饵线索和投喂性格，都写在这里。','Bait clues and feeding personalities for every species.')+'</p></div><div class="fishing-journal-grid">';
      for(const f of F.catalog.fish){const count=s.catches.filter(c=>c.fishId===f.id).length,profile=F.catalog.difficultyProfiles?.[f.rarity];out+='<article class="fishing-journal-card" data-discovered="'+!!count+'"><div>'+A.fishMarkup(f)+'</div><span class="fishing-rarity">'+rarity(f.rarity)+'</span><h3>'+escape(name(f))+'</h3>'+(f.description?'<p>'+escape(name({name:f.description}))+'</p>':'')+'<p>'+tr('捕获 ','Caught ')+count+tr(' 次',' times')+'</p>'+(profile?'<small class="fishing-difficulty-note"><strong>'+escape(name(f.technique||profile))+'</strong> · '+escape(name({name:profile.description}))+'</small>':'')+'<small>'+F.catalog.baits.filter(b=>b.fishIds.includes(f.id)).map(name).join(' · ')+'</small><small>'+escape(name({name:f.feedingHabit||f.feedingReaction?.description}))+'</small></article>';}
      return out+'</div>';
    }
    function mysteryCollection(){
      const s=snapshot.state,bundles=s.catches.filter(c=>c.fishId==='mystery_bundle'&&c.openedAt===null),gifts=s.giftUnlocks||[],appearance=s.giftAppearance||{};
      let out='<section class="fishing-mystery-shelf" data-mystery-bundles>'+root.TracerFishingRewards.markup({kind:'mystery'})+'<div><span class="fishing-eyebrow">'+tr('来自水下的礼物','GIFTS FROM THE WATER')+'</span><h2>'+tr('神秘大礼包','Mystery bundles')+' · '+bundles.length+'</h2><p>'+tr('偶尔随鱼钩而来的密封礼物，只能通过钓鱼获得。打开前不展示内容；同系列优先获得未收藏的礼物。','Sealed treasures occasionally caught while fishing. Contents stay concealed until opened; new gifts in the series come first.')+'</p></div>'+button('open-bundle',bundles.length?tr('开启一份礼包','Open a bundle'):tr('等待下一次惊喜','Your next surprise awaits'),bundles[0]?.id||'',snapshot.busy||!bundles.length,'primary')+'</section>';
      out+='<section data-gift-collection><div class="fishing-section-heading"><h2>'+tr('我的水下珍礼','Gifts from the deep')+' <span>'+gifts.length+'</span></h2><p>'+tr('只展示已经获得的礼物。收起后恢复原来的头像框或背景。','Only discovered gifts appear here. Put them away to restore your previous frame or background.')+'</p></div>';
      if(!gifts.length)return out+'<p class="fishing-soft-empty">'+tr('还没有拆开的秘密。去水边，等一份属于你的礼物。','Your first secret is still underwater. A little patience by the pond may bring a gift.')+'</p></section>';
      out+='<div class="fishing-gift-grid">';
      for(const gift of gifts){const equipped=appearance[gift.slot+'Id']===gift.id;out+='<article class="fishing-gift-card" data-gift="'+gift.id+'" data-equipped="'+equipped+'">'+root.TracerFishingRewards.giftMarkup(gift)+'<div class="fishing-gift-card-copy"><span class="fishing-gift-kind">'+(gift.slot==='avatarFrame'?tr('限定头像框','Exclusive avatar frame'):tr('限定背景板','Exclusive background'))+'</span><h3>'+escape(name(gift))+'</h3><p>'+escape(name({name:gift.description}))+'</p>'+button(equipped?'remove-gift':'equip-gift',equipped?tr('使用中 · 收起','In use · Put away'):tr('使用礼物','Use gift'),equipped?gift.slot:gift.id,snapshot.busy,equipped?'quiet':'primary')+'</div></article>';}
      return out+'</div></section>';
    }
    function aquariumResidents(){
      const s=snapshot.state,ids=s.aquarium?.fryIds||[],residents=ids.map(id=>s.fry.find(f=>f.id===id)),available=s.fry.filter(f=>f.releasedAt===null&&!ids.includes(f.id)&&F.catalog.fish.find(x=>x.id===f.fishId)?.rarity==='legendary'),archived=new Set(s.ponds.filter(p=>p.archivedAt!==null).map(p=>p.id));
      let out='<section data-aquarium-residents><div class="fishing-section-heading"><h2>'+tr('水族箱住客','Aquarium residents')+' <span>'+residents.length+' / 3</span></h2>'+button('feed-aquarium',tr('投喂 · 5 金币','Feed · 5 coins'),'',snapshot.busy||!residents.some(f=>f.fedAt===null||Date.now()-f.fedAt>=60000)||snapshot.economy.balance<5,'primary')+'</div><p>'+tr('只接收传奇鱼，最多三条。取回会回到育养箱，成长和投喂记录都会保留。','A home for up to three legendary fish. Returning a fish to the nursery preserves its growth and feeding history.')+'</p><div class="fishing-residents">';
      for(const fry of residents){const f=F.catalog.fish.find(x=>x.id===fry.fishId);out+=fishCard(f,'<span class="fishing-growth"><i style="width:'+fry.growth+'%"></i></span>'+tr('成长 ','Growth ')+fry.growth+'%',button('take-aquarium-fish',tr('取回育养箱','Return to nursery'),fry.id,snapshot.busy,'quiet'));}
      if(!residents.length)out+='<p class="fishing-soft-empty">'+tr('水族箱还没有住客，从下方选择一条传奇鱼入住吧。','Your aquarium is waiting. Choose a legendary fingerling below.')+'</p>';
      out+='</div><div class="fishing-section-heading"><h2>'+tr('传奇鱼育养箱','Legendary nursery')+'</h2><p>'+tr('从这里放入水族箱。已珍藏鱼塘中的鱼会保持原位。','Move fish into your aquarium here. Fish in archived ponds remain in their collections.')+'</p></div><div class="fishing-nursery">';
      for(const fry of available){const f=F.catalog.fish.find(x=>x.id===fry.fishId),locked=archived.has(fry.pondId);out+=fishCard(f,tr('成长 ','Growth ')+fry.growth+'%',button('place-aquarium-fish',locked?tr('已在珍藏鱼塘','In an archived pond'):fry.pondId?tr('从鱼塘移入水族箱','Move from pond to aquarium'):tr('放入水族箱','Place in aquarium'),fry.id,snapshot.busy||locked||residents.length>=3));}
      if(!available.length)out+='<p class="fishing-soft-empty">'+tr('钓获传奇鱼后，获得的鱼苗会在这里等你。','Legendary catches give you fingerlings that wait here.')+'</p>';
      const pondFry=pondFingerlings();
      return out+'</div><div class="fishing-pond-nursery-link"><p>'+tr('另有 '+pondFry.length+' 条珍稀 / 史诗鱼苗待放养，可前往「我的鱼塘」查看。',pondFry.length+' rare / epic fingerlings are waiting in My Ponds.')+'</p>'+button('open-ponds',tr('查看鱼塘鱼苗 →','View pond nursery →'))+'</div></section>';
    }
    function update(next){
      if(destroyed||!next?.state)return;snapshot={...next,busy:!!(next.busy||next.loadoutLocked)};
      const key=JSON.stringify([snapshot.language,snapshot.state,snapshot.economy.balance,snapshot.busy,snapshot.error,snapshot.notice,section,selectedPond,filter,selectedPool,snapshot.state.fry.map(f=>f.fedAt===null||Date.now()-f.fedAt>=60000)]);
      if(signature===key)return;signature=key;
      const focus=doc.activeElement?.closest('[data-fishing-action]'),focusId=focus&&[focus.dataset.fishingAction,focus.dataset.value];
      const tackleFocus=doc.activeElement?.closest('[data-tackle-focus]'),tackleFocusKey=tackleFocus&&page.contains(tackleFocus)?tackleFocus.dataset.tackleFocus:'';
      if(tackleBox){tackleSelection=tackleBox.getSelectedId();tackleBox.destroy();tackleBox=null;}
      pondPlayer?.destroy();pondPlayer=null;aquariumPlayer?.destroy();aquariumPlayer=null;
      page.innerHTML=section==='rods'?rods():section==='cabin'?aquarium():section==='tackle'?tackle():ponds();
      const showcaseHost=page.querySelector('[data-aquarium-display]');if(showcaseHost&&root.TracerFishingAquariumArt){aquariumPlayer=root.TracerFishingAquariumArt.create(showcaseHost);aquariumPlayer.update(showcaseValue(),snapshot.language);}
      const tackleMount=page.querySelector('[data-tackle-box-mode]');
      if(tackleMount){tackleBox=root.TracerFishingTackle.create(tackleMount,{mode:tackleMount.dataset.tackleBoxMode,selectedId:tackleSelection,onAction:(action,id)=>options.onAction?.(action,id,{pondId:selectedPond})});tackleBox.update(snapshot);if(tackleFocusKey){const node=Array.from(tackleMount.querySelectorAll('[data-tackle-focus]')).find(node=>node.dataset.tackleFocus===tackleFocusKey);(node&&!node.disabled?node:tackleMount.querySelector('.fishing-tackle-slot[tabindex="0"]'))?.focus({preventScroll:true});}}
      if(section==='ponds'){
        const pond=snapshot.state.ponds.find(p=>p.id===selectedPond),style=F.catalog.pondStyles.find(p=>p.id===pond.styleId),fish=snapshot.state.fry.filter(f=>f.pondId===pond.id&&!f.releasedAt).map(f=>({...F.catalog.fish.find(x=>x.id===f.fishId),...f,speciesId:f.fishId}));
        const viewport=page.querySelector('#fishing-pond-canvas');viewport.className='fishing-pond-viewport';
        pondPlayer=A.createPond(viewport,{pond:{...style,...pond,style:style.style},fish,catalog:F.catalog,interactive:true,editing,selectedDecorationId:selectedDecoration,onDecorationSelect:id=>{selectedDecoration=id;renderEditor();},onDecorationMove:patch=>options.onAction?.('set-decoration',patch.id,{pondId:selectedPond,patch}),onSelect:fish=>{const id=typeof fish==='string'?fish:fish.id;const row=page.querySelector('[data-value="'+CSS.escape(id)+'"]');row?.closest('.fishing-fish-card')?.scrollIntoView({block:'nearest',behavior:'smooth'});},feeding});
      }
      if(focusId)page.querySelector('[data-fishing-action="'+focusId[0]+'"][data-value="'+CSS.escape(focusId[1])+'"]')?.focus({preventScroll:true});
    }
    function click(event){
      const node=event.target.closest('[data-fishing-action]');if(!node||node.disabled||!page.contains(node))return;const action=node.dataset.fishingAction,value=node.dataset.value;
      if(action==='edit-aquarium-decor'){showcaseEditing=true;showcaseDraft={};if(snapshot.showcase?.selection?.decorationIds)showcaseDraft.decorationIds=snapshot.showcase.selection.decorationIds.slice();renderShowcaseEditor();page.querySelector('[data-aquarium-decor-editor]')?.scrollIntoView({block:'nearest',behavior:'smooth'});return;}
      if(action==='cancel-showcase'){showcaseEditing=false;showcaseDraft=null;renderShowcaseEditor();return;}
      if(action==='manage-aquarium'){page.querySelector('[data-aquarium-residents]')?.scrollIntoView({block:'start',behavior:'smooth'});return;}
      if(action==='manage-pond-nursery'){const nursery=page.querySelector('[data-pond-nursery]');nursery?.scrollIntoView({block:'nearest',behavior:'smooth'});nursery?.querySelector('button:not(:disabled)')?.focus({preventScroll:true});return;}
      if(action==='showcase-decoration'){if(!showcaseDraft)return;const ids=showcaseDraft.decorationIds||(showcaseDraft.decorationIds=root.TracerFishingAquariumArt.defaultDecorations.slice()),index=ids.indexOf(value);if(index>=0)ids.splice(index,1);else if(ids.length<3)ids.push(value);renderShowcaseEditor();page.querySelector('[data-fishing-action="showcase-decoration"][data-value="'+CSS.escape(value)+'"]')?.focus({preventScroll:true});return;}
      if(action==='save-showcase'){const patch=showcaseDraft;showcaseEditing=false;showcaseDraft=null;renderShowcaseEditor();options.onAction?.('set-showcase','',{patch});return;}
      if(action==='select-pond'){selectedPond=value;selectedDecoration='';signature='';update(snapshot);return;}
      if(action==='select-pool'){if(F.catalog.rodPools.some(p=>p.id===value)){selectedPool=value;signature='';update(snapshot);}return;}
      if(action==='filter'){filter=value;signature='';update(snapshot);return;}
      if(action==='edit-decorations'){editing=!editing;renderEditor();return;}
      if(action.startsWith('decor-')){const d=snapshot.state.ponds.find(p=>p.id===selectedPond)?.decorations.find(d=>d.id===selectedDecoration);if(!d)return;const kind=action.slice(6),patch=kind==='left'?{x:Math.max(-2.65,d.x-.2)}:kind==='right'?{x:Math.min(2.65,d.x+.2)}:kind==='up'?{z:Math.max(-2.65,d.z-.2)}:kind==='down'?{z:Math.min(2.65,d.z+.2)}:kind==='rotate'?{rotation:(d.rotation+1)%4}:kind==='smaller'?{scale:Math.max(.6,+(d.scale-.1).toFixed(2))}:kind==='larger'?{scale:Math.min(1.5,+(d.scale+.1).toFixed(2))}:{remove:true};options.onAction?.('set-decoration',d.id,{pondId:selectedPond,patch:{id:d.id,...patch}});return;}
      options.onAction?.(action,value,{pondId:selectedPond});
    }
    function selectDecoration(id){selectedDecoration=id||'';renderEditor();}
    function change(event){if(event.target.matches('[data-decoration-select]'))selectDecoration(event.target.value);}
    page.addEventListener('click',click);page.addEventListener('change',change);
    return {update,selectDecoration,selectBait(id){tackleSelection=id;tackleBox?.selectBait(id);},getDecorationPosition:id=>pondPlayer?.getDecorationPosition?.(id),feed(value){feeding=value;aquariumPlayer?.feed(value);pondPlayer?.feed?.(value);pondPlayer?.update?.({feeding:value});},selectPond(id){selectedPond=id;signature='';if(snapshot)update(snapshot);},destroy(){destroyed=true;pondPlayer?.destroy();aquariumPlayer?.destroy();tackleBox?.destroy();page.removeEventListener('click',click);page.removeEventListener('change',change);page.remove();}};
  }
  root.TracerFishingView={create};
})(typeof window!=='undefined'?window:globalThis);
