(function(root){
  'use strict';
  root.TracerStickerShop=function(host,onAction){
    const el=(tag,cls,parent)=>{const n=document.createElement(tag);n.className=cls;parent?.appendChild(n);return n;},button=(parent,action)=>{const n=el('button','store-button',parent);n.type='button';n.dataset.stickerShop=action;return n;};
    const box=el('section','sticker-shop',host),heading=el('div','store-department-heading',box),eyebrow=el('p','store-eyebrow',heading),title=el('h2','',heading),help=el('p','',heading),banner=el('div','sticker-shop-banner',box),filters=el('div','sticker-shop-filters',box),grid=el('div','sticker-shop-grid',box),empty=el('p','store-empty',box),notice=el('p','sticker-shop-status',box);
    notice.setAttribute('role','status');const groups=new Map(),cards=new Map();let state={},active='all',pending=false,selected=null,dead=false;
    const tr=(zh,en)=>state.language==='en'?en:zh,local=a=>a?.[state.language==='en'?1:0]||'';
    for(const id of ['all','garden','slow','stars','celebrate','owned']){const b=button(filters,'filter');b.dataset.group=id;groups.set(id,b);}
    const dialog=el('dialog','sticker-detail',box),close=button(dialog,'close'),art=el('img','sticker-detail-art',dialog),name=el('h2','',dialog),description=el('p','',dialog),policy=el('p','sticker-detail-policy',dialog),action=button(dialog,'buy');name.id='sticker-detail-name';dialog.setAttribute('aria-labelledby',name.id);art.alt='';close.autofocus=true;
    function renderDetail(){const item=state.stickers?.items.find(i=>i.id===selected);if(!item)return;art.src='/sticker-art/'+item.id+'-v1.png';name.textContent=local(item.name);description.textContent=local(item.description);close.textContent=tr('关闭','Close');policy.textContent=tr('一次收藏，无限次使用。仅可贴在 Note 笔记里，随时调整与取下。','Collect once, use as often as you like. Decorate your Notes, then move or remove freely.');action.dataset.itemId=item.id;action.dataset.stickerShop=item.owned?'use':'buy';action.textContent=item.owned?tr('到笔记里贴 →','Decorate a note →'):'◈ '+item.price+tr(' 金币 · 收入背包',' coins · Add to backpack');action.disabled=pending||state.busy||!!state.error||!item.owned&&(state.economy?.balance||0)<item.price;}
    function render(){if(dead)return;const data=state.stickers;if(!data)return;
      eyebrow.textContent='PAPER GOODS / STICKER CORNER';title.textContent=tr('一张小贴纸，一点小欢喜。','Little stickers. Little joys.');help.textContent=tr('留给笔记的小心情。点开看看纸边里的小故事。','A little mood for your notes. Discover a little story inside every paper edge.');banner.textContent=tr('✧ 永久收藏 · 可重复贴用 · 购买后收入 Note 专属背包','✧ Yours forever · Reusable · Find your backpack in Notes');
      const labels={all:tr('全部贴纸','All stickers'),garden:tr('花园来信','Garden letters'),slow:tr('慢慢日常','Slow days'),stars:tr('星光旅行','Starlight'),celebrate:tr('小小庆祝','Celebrate'),owned:tr('我的收藏','Collected')};for(const [id,b]of groups){b.textContent=labels[id];b.setAttribute('aria-pressed',String(id===active));}
      let count=0;for(const item of data.items){let card=cards.get(item.id);if(!card){const node=el('article','sticker-shop-card',grid),preview=button(node,'inspect'),image=el('img','',preview),copy=el('div','sticker-shop-copy',node),label=el('span','store-eyebrow',copy),title=el('h3','',copy),text=el('p','',copy),buy=button(copy,'buy');node.dataset.stickerId=item.id;preview.classList.add('sticker-shop-art');preview.dataset.itemId=buy.dataset.itemId=item.id;image.src='/sticker-art/'+item.id+'-v1.png';image.alt='';image.loading='lazy';card={node,preview,label,title,text,buy};cards.set(item.id,card);}
        card.node.hidden=!(active==='all'||active==='owned'&&item.owned||item.setId===active);if(!card.node.hidden)count++;card.node.dataset.series=item.setId;card.preview.setAttribute('aria-label',tr('查看贴纸：','Preview sticker: ')+local(item.name));card.label.textContent=item.owned?tr('已在背包 · 无限使用','IN YOUR BAG · REUSABLE'):labels[item.setId];card.title.textContent=local(item.name);card.text.textContent=local(item.description);card.buy.dataset.stickerShop=item.owned?'use':'buy';card.buy.textContent=item.owned?tr('到笔记里贴 →','Use in Notes →'):'◈ '+item.price+tr(' 金币 · 收藏',' coins · Collect');card.buy.disabled=pending||state.busy||!!state.error||!item.owned&&(state.economy?.balance||0)<item.price;
      }empty.hidden=count>0;empty.textContent=tr('还没有收藏贴纸，去挑一张喜欢的吧。','No stickers yet. Find one you love.');notice.textContent=state.error||(pending?tr('正在放入背包…','Adding to your backpack…'):'');renderDetail();
    }
    async function click(e){const b=e.target.closest('[data-sticker-shop]');if(!b||b.disabled)return;const what=b.dataset.stickerShop;if(what==='close'){dialog.close();return;}if(what==='filter'){active=b.dataset.group;render();return;}const item=state.stickers?.items.find(i=>i.id===b.dataset.itemId);if(!item)return;
      if(what==='inspect'){selected=item.id;renderDetail();dialog.showModal();return;}if(what==='use'){dialog.close();root.Tracer.stickers.choose(item.id);return;}
      if(pending)return;pending=true;render();try{await onAction('buy-sticker',{itemId:item.id});}finally{pending=false;render();root.Tracer.stickers?.refresh();}
    }
    dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});box.addEventListener('click',click);
    return{update(next){state=next;render();},destroy(){dead=true;if(dialog.open)dialog.close();box.remove();}};
  };
})(window);
