(function () {
 'use strict';
 const bridge=window.TracerLocalVfx;
 if(!bridge)return;
 let state=null,dialog=null,busy=false,unsubscribe=null,lastError='',menuState=null,menuError='';
 const zh=()=>document.documentElement.lang.startsWith('zh'),tr=(a,b)=>zh()?a:b;
 async function call(value){const result=await bridge.request(value);if(!result?.ok)throw Error(result?.error||'local-vfx-unavailable');state=result;return result;}

 async function menuCall(action){const result=await bridge.requestMenu({action});if(!result?.ok)throw Error(result?.error||'registry-operation-failed');menuState=result;return result;}
 async function refreshMenu(){if(typeof bridge.requestMenu!=='function')return;try{await menuCall('status');menuError='';}catch(error){menuError=error.message;}}
 function drawMenu(){
  if(!dialog)return;const install=dialog.querySelector('#local-vfx-menu-install'),remove=dialog.querySelector('#local-vfx-menu-remove'),message=dialog.querySelector('#local-vfx-menu-status');
  const available=typeof bridge.requestMenu==='function'&&menuError!=='local-menu-forbidden',registered=menuState?.registered===true,partial=menuState?.entries?.some(entry=>entry.registered);
  install.hidden=remove.hidden=!available;install.disabled=busy||registered;remove.disabled=busy||(!registered&&!partial&&!menuError&&!menuState?.parentsPending);
  message.textContent=!available?tr('桌面菜单仅支持本地 Windows 版本。','Desktop menus are available in the local Windows version.'):menuError==='local-menu-conflict'?tr('检测到菜单内容冲突；未覆盖其他程序的内容。','Menu content conflicts with this registration; existing content was preserved.'):menuError==='local-menu-rollback-blocked'?tr('部分回滚未完成；保留了冲突内容，请先检查再重试移除。','Rollback was incomplete; conflicting content was preserved. Review it before retrying removal.'):menuError==='parents-receipt-busy'?tr('另一个菜单操作正在执行，或上次中断的操作需要检查。','Another menu operation is running, or an interrupted operation needs review.'):menuError?tr('桌面菜单操作未完成，可重试。','The desktop menu operation did not complete. You can retry.'):registered?tr('桌面空白处右键菜单已注册；释放后点击选点。','Desktop background menu registered. After Release, click to choose a point.'):menuState?.parentsPending?tr('菜单已移除，仍有记录的共享项；其他程序使用的内容会保留，可稍后再次移除。','Menu removed; recorded shared keys remain. Content used by other programs is preserved; removal can be retried later.'):tr('桌面右键菜单未注册；可单独注册或移除，不改变播放设置。','Desktop background menu is not registered. Registering or removing it preserves playback preferences.');
 }
 async function runMenu(action){if(busy)return;busy=true;menuError='';draw();try{await menuCall(action);}catch(error){menuError=error?.message||'registry-operation-failed';const failure=menuError;try{await menuCall('status');}catch{}menuError=failure;}finally{busy=false;draw();}}
 function offer(){const top=document.querySelector('.pet-dialog .pet-top');if(!state?.allowed||!top||top.querySelector('[data-local-vfx-open]'))return;const button=document.createElement('button');button.type='button';button.dataset.localVfxOpen='true';button.textContent=tr('本地特效','Local effects');button.onclick=()=>open().catch(()=>{});top.append(button);}
 function notice(){
  const reason=lastError||state.notice;
  if(reason==='local-vfx-invoke-point-unavailable')return tr('无法获取桌面右键的原始位置，特效未播放。原点接线尚未启用。','The original desktop context-menu location is unavailable; no effect played. Position integration is not enabled.');
  if(reason==='local-vfx-assets-failed')return tr('素材加载失败，特效窗口已关闭。','Assets could not load. The effect window was closed.');
  if(reason==='local-vfx-display-changed')return tr('屏幕配置发生变化，特效已结束；没有重新定位或残留窗口。','The display changed. The effect ended without repositioning or leaving a window behind.');
  if(reason==='local-vfx-storage-unavailable')return tr('设置保存失败，原设置仍保留。','Settings could not be saved. Previous settings were preserved.');
  if(reason==='local-vfx-disabled')return tr('请先启用本地特效。','Enable local effects first.');
  if(lastError)return tr('操作未完成。特效没有启动，请稍后重试。','The operation did not complete. No new effect started.');
  if(!state.assetsReady)return tr('此特效素材待接入，释放暂不可用。','Assets for this effect are pending; release is unavailable.');
  if(state.placing)return tr('左键点击哪里，就从哪里升起；Esc 或 20 秒超时取消。','Click once to choose where it rises. Esc or a 20-second timeout cancels.');
  if(reason==='local-vfx-placement-timeout')return tr('选点已超时，选择层已关闭。','Selection timed out; the picker closed.');
  if(reason==='local-vfx-placement-cancelled')return tr('已取消选点，未释放效果。','Selection cancelled; no effect was released.');
  if(reason==='local-vfx-placement-unavailable')return tr('选点未能启动，未释放效果。','Selection could not start; no effect was released.');
  if(state.active)return tr('播放中，结束后自动关闭；可随时取消。','Playing; it closes automatically and can be cancelled.');
  return tr('释放后左键选择落点，特效从该点原地升起。选点时可按 Esc 取消；播放时鼠标穿透。','After Release, left-click a ground point to rise there. Escape cancels selection; playback passes mouse input through.');
 }
 function draw(){if(!dialog||!state)return;const s=state.settings;for(const [key,value]of Object.entries(s)){const control=dialog.querySelector('#local-vfx-'+key);if(['enabled','atmosphere'].includes(key))control.checked=value;else control.value=key==='strength'?value*100:value;control.disabled=busy;}dialog.querySelector('#local-vfx-strength-value').textContent=Math.round(s.strength*100)+'%';dialog.querySelector('#local-vfx-play').disabled=busy||!s.enabled||!state.assetsReady||state.requiresInvocationPoint===true;dialog.querySelector('#local-vfx-notice').textContent=notice();dialog.querySelector('#local-vfx-cancel').disabled=busy||(!state.active&&!state.placing);dialog.querySelector('#local-vfx-cancel').textContent=state.placing?tr('取消选点','Cancel selection'):tr('取消播放','Cancel playback');drawMenu();}
 async function run(job){if(busy)return;busy=true;lastError='';draw();try{await job();}catch(error){lastError=error?.message||'local-vfx-unavailable';}finally{busy=false;draw();}}
 async function open(){await call({action:'status'});if(!state.allowed)return;await refreshMenu();if(dialog){if(!dialog.open)dialog.showModal();draw();return;}
 dialog=document.createElement('dialog');dialog.className='modal local-vfx-dialog';dialog.innerHTML='<form method="dialog"><h2>'+tr('本地特效','Local visual effects')+'</h2><p>'+tr('实验播放器默认关闭，仅限本地，不随商业版分发。这是参考演示的独立重制，非官方游戏素材。','The experimental player is off by default, local only, and excluded from commercial releases. It is an independent reference remake, not official game assets.')+'</p><label><input id="local-vfx-enabled" type="checkbox">'+tr('启用本地特效','Enable local effect playback')+'</label><label>'+tr('特效','Effect')+'<select id="local-vfx-effect"></select></label><label>'+tr('氛围强度','Atmosphere strength')+' <output id="local-vfx-strength-value"></output><input id="local-vfx-strength" type="range" min="0" max="60" step="5"></label><label><input id="local-vfx-atmosphere" type="checkbox">'+tr('动态屏幕边缘氛围','Animated screen edge atmosphere')+'</label><label>'+tr('主体尺寸','Object size')+'<input id="local-vfx-size" type="range" min="40" max="200" step="10"></label><label>'+tr('动效','Motion')+'<select id="local-vfx-motion"><option value="system">'+tr('跟随系统','Follow system')+'</option><option value="normal">'+tr('正常','Normal')+'</option><option value="reduced">'+tr('减弱','Reduced')+'</option></select></label><p>'+tr('桌面空白处右键选择释放，再左键点击选点；Esc 或 20 秒超时取消。','Choose Release from the desktop background menu, then left-click a ground point. Esc or a 20-second timeout cancels selection.')+'</p><p id="local-vfx-menu-status" role="status"></p><div class="local-vfx-actions"><button type="button" id="local-vfx-menu-install">'+tr('注册桌面右键菜单','Register desktop background menu')+'</button><button type="button" id="local-vfx-menu-remove">'+tr('移除桌面右键菜单','Remove desktop background menu')+'</button></div><p id="local-vfx-notice" role="status"></p><div class="local-vfx-actions"><button type="button" id="local-vfx-play">'+tr('释放后点击选点','Release, then click to choose a point')+'</button><button type="button" id="local-vfx-cancel">'+tr('取消特效','Cancel effect')+'</button><button type="submit">'+tr('关闭','Close')+'</button></div></form>';
 document.body.append(dialog);
 for(const effect of state.effects){const option=document.createElement('option');option.value=effect.id;option.textContent=effect.name+(effect.id==='haunt'?'':tr('（素材待接入）',' (assets pending)'));dialog.querySelector('#local-vfx-effect').append(option);}
 for(const key of ['enabled','effect','strength','atmosphere','size','motion'])dialog.querySelector('#local-vfx-'+key).addEventListener('change',()=>{if(busy)return;const settings={enabled:dialog.querySelector('#local-vfx-enabled').checked,effect:dialog.querySelector('#local-vfx-effect').value,strength:Number(dialog.querySelector('#local-vfx-strength').value)/100,atmosphere:dialog.querySelector('#local-vfx-atmosphere').checked,size:Number(dialog.querySelector('#local-vfx-size').value),motion:dialog.querySelector('#local-vfx-motion').value};run(()=>call({action:'settings',settings}));});
 dialog.querySelector('#local-vfx-menu-install').onclick=()=>runMenu('install');dialog.querySelector('#local-vfx-menu-remove').onclick=()=>runMenu('remove');
 dialog.querySelector('#local-vfx-play').onclick=()=>run(()=>call({action:'play'}));dialog.querySelector('#local-vfx-cancel').onclick=()=>run(()=>call({action:'cancel'}));unsubscribe=bridge.onState?.(value=>{state={...value,ok:true};draw();});dialog.showModal();draw();}
 const unsubscribeOpen=bridge.onOpen?.(()=>open().catch(()=>{}));
 call({action:'status'}).then(()=>{offer();const observer=new MutationObserver(offer);observer.observe(document.body,{childList:true,subtree:true});addEventListener('pagehide',()=>{observer.disconnect();unsubscribe?.();unsubscribeOpen?.();},{once:true});}).catch(()=>{});
})();
