'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),Images=require('./pet-image');
const fail=code=>Object.assign(new Error(code),{code,status:code==='backup-too-large'?413:code==='backup-art-conflict'||code==='backup-art-missing'?409:400});
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
function urls(preferences){const state=preferences['tracer.pet.v1']?JSON.parse(preferences['tracer.pet.v1']):null;return [...new Set((state?.customs||[]).flatMap(p=>p.animation?.pages||[p.image]))].sort();}
function validate(assets,preferences){if(!Array.isArray(assets)||assets.length>512)throw fail('backup-invalid-assets');const expected=urls(preferences);if(assets.length!==expected.length)throw fail('backup-invalid-assets');return assets.map((a,i)=>{if(!a||Object.keys(a).sort().join(',')!=='data,sha256,url'||a.url!==expected[i]||!Images.ASSET_RE.test(a.url)||typeof a.data!=='string'||! /^[A-Za-z0-9+/]+={0,2}$/.test(a.data))throw fail('backup-invalid-assets');const bytes=Buffer.from(a.data,'base64');if(bytes.toString('base64')!==a.data||digest(bytes)!==a.sha256)throw fail('backup-invalid-assets');const profiles=preferences['tracer.pet.v1']?JSON.parse(preferences['tracer.pet.v1']).customs:[];const animated=profiles.find(p=>p.animation?.pages.includes(a.url));Images.generatedBytes(bytes,animated?{animation:true,animationVersion:animated.animation.version}:{});return{url:a.url,bytes};});}
async function collect(directory,preferences){const assets=[];for(const url of urls(preferences)){const bytes=await Images.readAsset(directory,url);if(!bytes)throw fail('backup-art-missing');assets.push({url,sha256:digest(bytes),data:bytes.toString('base64')});if(Buffer.byteLength(JSON.stringify(assets))>6*1024*1024)throw fail('backup-too-large');}return assets;}
async function stage(directory,assets,preferences){const rows=validate(assets,preferences),created=[];const folder=path.join(directory,'.pet-art');await fs.mkdir(folder,{recursive:true});if((await fs.lstat(folder)).isSymbolicLink()||path.resolve(await fs.realpath(folder))!==path.resolve(await fs.realpath(directory),'.pet-art'))throw fail('backup-art-conflict');try{for(const {url,bytes}of rows){const existing=await Images.readAsset(directory,url);if(existing){if(digest(existing)!==digest(bytes))throw fail('backup-art-conflict');continue;}const file=path.join(directory,'.pet-art',url.split('/').at(-1));await fs.writeFile(file,bytes,{flag:'wx',mode:0o600});created.push(file);}return async()=>{for(const file of created)await fs.unlink(file).catch(()=>{});};}catch(e){for(const file of created)await fs.unlink(file).catch(()=>{});throw e;}}
module.exports={urls,validate,collect,stage};
